### ISSUE TITLE
[FR] SRT version API function

### ISSUE THREAD

**Issue by maxsharabayko** [Haivision/srt#1016]
As a user of SRT library, I would like to be abe to get the version of SRT in runtime.

Would be useful to have an API function `srt_version()` or `srt_get_version()` that returns version string (`const char *`).

I would also like to have the git commit ID in that version info.

Current state:
At the moment there is only `SRT_VERSION_STRING` from version.h, that can't be used in runtime.

### Update

PR #1024 adds `uint32_t srt_getversion()` to get SRT library version.

See alse #987: a request for API version info.

From the discussion with @jeandube and @ethouris 

**@jeandube :**
Still need a wat to get the 160 bit git commit. Or we can keep the MSB 0 and use int32_t. 
Or something we can add ourself and document the meaning elsewhere (ex 1.4.1n) (n: jeandube/srt, 264f4e10935825878db004ee46c9230ed03b28a1)

**@ethouris : 5:20 PM:**
I simply think that for that purpose we better add some more elaborate function. Something like:
int srt_property(int tag, void* out_val, int* out_len);
so that you can obtain the git tag id by 
`srt_property(SRT_PROP_SCMTAG, tagval, &tagval_size);`
and you get your tagval filled.

**Comment by jeandube** [comment]
On my side I would like to also have a function returning the version in int format like the SRTO_VERSION option (which unfortunately requires a SRT socket).

**Comment by ethouris** [comment]
Is that for a case when you have compiled your application with a version that is older than the version of the currently used shared library?

And if you check this version, what would you like to use this information for? Because:

1. If your compiled-in version is older than the runtime version, you are still limited to the features provided by the version you compiled with. If you use any deprecated features, your application should still work the same way as before. If it doesn't work, it means it's a bug. If you use any feature removed already, it usually means that you use a too new major version, but then your application shouldn't be allowed to link against this version of the shared library.

2. If your compiled-in version is newer than the runtime version, I'd only agree that the application should crash in the very beginning.

3. If you use some deprecated options, setting them should simply have no effect, if you link against a shared library that has them already deprecated. If you compile with this version, you should have a deprecation warning - but you can work this out by checking the version at compile time.

In order to check the version at compile time, you have `SRT_VERSION_`* macros ended with `MAJOR`, `MINOR` and `PATCH`. This comes from a generated file `version.h`.

**Comment by StephaneStH** [comment]
"Is that for a case when you have compiled your application with a version that is older than the version of the currently used shared library?"
It's probably for a case where you want to know what the version of the library you are running on top of is. Your question is literally what such an API would answer.

" If you use any deprecated features, your application should still work the same way as before. If it doesn't work, it means it's a bug."
"should" is the key word there, but if there ever is a bug, the version API would at least tell you what you were running on.

"In order to check the version at compile time"
Sure but the info on what headers you compiled with and what you are actually running on top of are two distinct data points.
