### ISSUE TITLE
the second parameters not work

### ISSUE THREAD

**Issue by yyantony** [Haivision/srt#1043]
only enable heavy logging when configure,version is  v1.4.1,but when i run these two commands,look like the maxbw not work,did i miss something?
NETWORK environment：
tc  qdsic add dev enp1s0 root netem delay 100ms loss 40%

./srt-live-transmit udp://127.0.0.1:3000 'srt://192.168.2.122:5201?maxbw=20000000' -v -loglevel:debug 2>LOG

./srt-live-transmit 'srt://@:5201?latency=1000ms&maxbw=20000000' udp://127.0.0.1:5000 -v -loglevel:debug 2>LOG

the bitrate of send side over 20Mbps,the udp rate only 10Mbps
![image](https://user-images.githubusercontent.com/59468869/71713358-56f87a00-2e44-11ea-8f8b-c6031c99ca47.png)

this is the log of send side.
[LOG.tar.gz](https://github.com/Haivision/srt/files/4018481/LOG.tar.gz)
only the latency parameters can work .

i reduce the maxbw to 1500000, still not working.
and when i set this command the speed still high ,  look like fec not enabled.   
'url?packetfilter=fec,rows:20,cols:20'

**Comment by yyantony** [comment]
is this problem too easy so no one help?

**Comment by ethouris** [comment]
I don't understand where the problem is.

Network impaired for 40% loss is usually not expected to be capable of delivering live streams.

**Comment by yyantony** [comment]
thank you ,ethouris, i just want to know why can not make fec or maxbw function enable?
is there any erros in my commands or build ?

**Comment by ethouris** [comment]
I don't understand. Why do you think this is not enabled?

If you try to use `srt-live-transmit` with `-v` option, just with the address that cannot be contacted, you should see the options to be set additionally displayed. If you can see them, they are definitely set.

**Comment by yyantony** [comment]
Hi,ethouris,thank you for reply,perhaps i did not express my question clearly,let me repeat it in other way.
I run this command "./srt-live-transmit udp://127.0.0.1:3000 'srt://192.168.2.122:5201?maxbw=2000000"
The bit rate of the stream should not exceed 16mbps，right?
Now the bit rate is over 16mps. Is it because I don't have disable tsbpd or need to do other operations?

**Comment by AlexandreLicinio** [comment]
why are you doing **maxbw** ?

**Comment by ethouris** [comment]
Not the bitrate. It's the upper value for the network bandwidth.

In live mode the only meaning of this value is that your bitrate must be below that value and the excessive bandwidth is predicted for potential retransmission. In practice this setting simply slows down retransmitted packets so that the speed doesn't exceed this bandwidth. It's simply because if your normal streaming rate already exceeds it, you simply get connection broken after a few seconds.

**Comment by yyantony** [comment]
i see,so if i want to reduce the bandwidth and the delay in the same network condition,should i enable fec? and  can the below command take effect?
./srt-live-transmit udp://127.0.0.1:3000 'srt://192.168.2.122:5201?packetfilter=fec,rows:20,cols:20'
./srt-live-transmit srt://:5201?packetfilter=fec udp://127.0.0.1:4000

**Comment by ethouris** [comment]
By using FEC you actually increase the bitrate.

The practical difference between FEC and ARQ (retransmission on request) is that:

FEC: Your overhead is constant (as a percentage of input bitrate), reliability depends on the loss percentage towards the group sizes - still, your overhead will be always bigger than the number of recovered losses.

ARQ: Your overhead is variable and it depends on the loss percentage. Reliability depends on the loss percentage towards the input bitrate and the combination of latency and your current network RTT - more practically speaking, the probability of dropping packets instead of recovering by retransmission increases with higher RTT and lower latency, and also the higher the loss percentage in the network, the more probable are second-time losses, or a "pushback" (a situation when retransmissions cause increased bandwidth usage, which results with even more losses).

With FEC (and `arq=none`) the bandwidth control is rather useless - you'll get an all-time constant overhead, so your effective network bitrate will be as constant as your stream bitrate. It may be important in case of ARQ, as the overhead in this case has a variable character so spikes in the network bitrate can be expected. The bandwidth limit allows in this case to spread the retransmitted packets better in time so that the overall network bitrate doesn't exceed given bandwidth limit.

**Comment by yyantony** [comment]
Yes, but I understand that if ARQ + FEC is opened at the same time, when the packet loss is large, the overhead will be small，right？

**Comment by ethouris** [comment]
I don't understand what you mean by "small". For the mode of FEC with ARQ in "onreq" mode (default) you'll get the usual constant overhead from FEC (as usual, and this doesn't change regardless of the other settings or network characteristics) plus the overhead from ARQ. The latter should be usually smaller than in case of ARQ only, however if you have a larger contiguous packet loss (meaning, such that exceeds the size of one horizontal FEC group), this loss could only be recovered by retransmission - and in this case you'll have temporarily such a high overhead as for normal ARQ, **plus** the overhead that you have for the sake of FEC anyway.

**Comment by yyantony** [comment]
Thank you for your detailed explanation.By the way how to enabel FEC with ARQ in "onreq" mode,these commands are right?should i do anything else?
./srt-live-transmit udp://127.0.0.1:3000 'srt://192.168.2.122:5201?packetfilter=fec,rows:20,cols:20'
./srt-live-transmit srt://:5201?packetfilter=fec udp://127.0.0.1:4000

**Comment by ethouris** [comment]
Yes, that should work.

**Comment by ypp1104** [comment]
> 是的，这应该有效。

Hello, I would like to ask whether your test packet loss rate has dropped, in the settings:
./srt-live-transmit udp://127.0.0.1:3000'srt://192.168.2.122:5201?packetfilter=fec,rows:20,cols:20'
./srt-live-transmit srt:// :5201?packetfilter=fec udp://127.0.0.1:4000
In this case, your ARQ is onreq by default;
Have you tested it again
1) When only fec is turned on and arq:never is in the state, packet loss
2) In the state of arq only, packet loss
3) When fec, arq: never are not set, the packet loss situation
In comparison with the packet loss situation, when I was doing the above test, 2) The number of packets lost was the largest. I don’t understand why.

**Comment by ypp1104** [comment]
> 谢谢你的详细解释。顺便说一下如何在“onreq”模式下使用ARQ启用FEC，这些命令是对的？我还应该做些什么吗？ ./srt-live-transmit udp://127.0.0.1:3000 'srt://192.168.2.122:5201?packetfilter=fec,rows:20,cols:20' ./srt-live-transmit srt:// :5201?packetfilter=fec udp://127.0.0.1:4000

Hello, I would like to ask whether your test packet loss rate has dropped, in the settings:
./srt-live-transmit udp://127.0.0.1:3000'srt://192.168.2.122:5201?packetfilter=fec,rows:20,cols:20'
./srt-live-transmit srt:// :5201?packetfilter=fec udp://127.0.0.1:4000
In this case, your ARQ is onreq by default;
Have you tested it again
1) When only fec is turned on and arq:never is in the state, packet loss
2) In the state of arq only, packet loss
3) When fec, arq: never are not set, the packet loss situation
In comparison with the packet loss situation, when I was doing the above test, 2) The number of packets lost was the largest. I don’t understand why.

**Comment by ypp1104** [comment]
Hello, I would like to ask whether your test packet loss rate has dropped, in the settings:
./srt-live-transmit udp://127.0.0.1:3000'srt://192.168.2.122:5201?packetfilter=fec,rows:20,cols:20'
./srt-live-transmit srt:// :5201?packetfilter=fec udp://127.0.0.1:4000
In this case, your ARQ is onreq by default;
Have you tested it again
1) When only fec is turned on and arq:never is in the state, packet loss
2) In the state of arq only, packet loss
3) When fec, arq: never are not set, the packet loss situation
In comparison with the packet loss situation, when I was doing the above test, 2) The number of packets lost was the largest. I don’t understand why.
