### ISSUE TITLE
Fix warnings in TravisCI OSX and MinGW builds

### ISSUE THREAD

**Issue by maxsharabayko** [Haivision/srt#1081]
See the latest Travis build for OSX and MinGW.

### OSX
```
srt/apps/verbose.hpp:62:10: warning: private field 'noeol' is not used [-Wunused-private-field]
333
    bool noeol;
334
         ^
```

### MinGW warnings
```
srt/srtcore/epoll.cpp:190:2: warning: #warning "Unsupported system for epoll. The epoll_add_ssock() API call won't work on this platform." [-Wcpp]
2642
 #warning "Unsupported system for epoll. The epoll_add_ssock() API call won't work on this platform."
2643
  ^
```

```

/srt/srtcore/epoll.cpp:132:5: warning: unused parameter ‘events’ [-Wunused-parameter]
2645
 int CEPoll::add_ssock(const int eid, const SYSSOCKET& s, const int* events)
2646
     ^
```

```
In file included from /Users/travis/build/Haivision/srt/apps/srt-live-transmit.cpp:74:
435
/srt/apps/verbose.hpp:62:10: warning: private field 'noeol' is not used [-Wunused-private-field]
436
    bool noeol;
```
etc.

**Comment by ethouris** [comment]
This complain about unused `noeol` is some sorry bullshit. The `Verbose::Log::operator<<(LogNoEol)` method does use this field, it's just implemented in `verbose.cpp` file, so from the perspective of the header file the use is not visible.

I could move one method back to the header file - the short ones should do the job and will clear out the warning. By the way I've seen there could be a problem with uninitialized `ErrLog::noeol` - both could be fixed in one PR.

The warning for the unsupported system for epoll is something we can't do a thing about until we provide the proper implementation for epoll, which will include all platforms. The next warning for the `events` parameter is a consequence of the former; both can be solved with the proper epoll implementation.
