### ISSUE TITLE
Associating SRT_LOG_HANDLER_FN with session/socket

### ISSUE THREAD

**Issue by peterlee-inca** [Haivision/srt#1158]
Is there a way to determine which socket a loghandler callback message is associated with? For example, here are a couple of messages that I would like to know which sessions they are coming from:

[2020-02-26 20:57:28] [../src/srtcore/core.cpp:5306(checkNeedDrop)]{3} 20:57:28.606332*E:SRT.d: SND-DROPPED 7 packets - lost delaying for 1030ms
[2020-02-21 15:02:34] [../src/srtcore/core.cpp:8610(processConnectRequest)]{3} 15:02:34.254700*E:SRT.c: UU:newConnection: rsp(REJECT): 1010 - Incorrect passphrase

Or, is there a way to subscribe to the log handler on a per-socket basis?

Thank you.

**Comment by ethouris** [comment]
Unfortunately, no. Especially that many things happen to be logged regardless of the particular socket they concern. Even if you'd normally use one multiplexer per socket, note that sender and receiver queues are still per multiplexer. It is being taken care of the best way possible to contain the socket information in the logs, but this information may be not always available at the place where the log is being printed. If it is possible, the socket for the sake of which the activity happens is printed in the beginning with `@` character and ended with `:`. For example, here is the content of the normal logger line printed by default:

```
19:25:27.741529/SRT:RcvQ:w2 D:SRT.c: @25582811:updateCC: emitting signal for EVENT:checktimer
```

where
```
19:25:27.741529 - time of the event
SRT:RcvQ:w2 - thread name (this '2' here is an ordinal number, but assigned to a multiplexer)
 D  - "debug" level (space as marker, followed by D. For example, error level has * marker)
SRT.c  - control/management activity (unfortunately majority of the logs)
@25582811 - socket ID for the sake of which the activity happens (optional)
updateCC  - function or shorthand for a functionality where the log occurs (optional)
```

For logs like `SND-DROPPED` it was simply not taken care enough, probably this could be fixed. If you look through the code you'll probably see `CONID()` call in the logs - this is where it requests this `@25582811:` to be printed.

**Comment by peterlee-inca** [comment]
Thanks ethouris for your suggestion. Adding CONID()/m_SocketID to the log message did provide the socket info.

Now, I also noticed this comment in <core.cpp>:
```
   // This is listener - m_RejectReason need not be set
   // because listener has no functionality of giving the app
   // insight into rejected callers.
```

I was actually working on getting the various configuration/handshake/connection events (e.g. incorrect passphrase, unsupported version, connection broken, etc) from the library so that we can provide an appropriate message to the end-user through our app. From my limited experience with the srt library, I see the following mechanisms for retrieving these events:
- Check return value from an API call, e.g. 
        srt_listen: Operation not supported: Another socket is already listening on the same port
- Check epoll event, e.g. 
        socket_status=SRTS_BROKEN if passphrase is incorrect when mode=caller: rejectreason=<10>, rejectreason_msg=<Incorrect passphrase>
- Catch exception - not sure about this one.
- Process loghandler messages (my initial question), e.g.
        we see the following messages when mode=listener and caller's passphrase is incorrect:
```
        [2020-02-21 15:02:34] [../src/srtcore/crypto.cpp:217(processSrtMsg_KMREQ)]{3} 15:02:34.251962*E:SRT.c: KMREQ/rcv: (snd) Rx process failure - BADSECRET
        [2020-02-21 15:02:34] [../src/srtcore/core.cpp:2622(interpretSrtHandshake)]{3} 15:02:34.254623*E:SRT.c: interpretSrtHandshake: KMREQ result abnornal - rejecting per strict encryption
        [2020-02-21 15:02:34] [../src/srtcore/api.cpp:519(newConnection)]{3} 15:02:34.254675*E:SRT.c: @750109465:newConnection: connection rejected due to: CONNECTION REJECTED
        [2020-02-21 15:02:34] [../src/srtcore/core.cpp:8610(processConnectRequest)]{3} 15:02:34.254700*E:SRT.c: UU:newConnection: rsp(REJECT): 1010 - Incorrect passphrase
```

Ideally, it would be great if there was a single socket-based mechanism that allows us to obtain all these events for Listener/Caller/Rendezvous. Is there a better way of doing this, or maybe a better way of thinking about this?

Can I ask if Haivision's SRT App/UI provides info regarding these events, e.g. when a Listener detects a caller trying to connect with an incorrect passphrase?

**Comment by ethouris** [comment]
For the states of the socket you have:
* `srt_getsockstate` to obtain the status - `SRTS_*` values of `SRT_SOCKSTATUS` enum
* `srt_getrejectreason` only after you get `SRT_ECONNREJ` from `srt_getlasterror`, the `SRT_REJ_*` values of `SRT_REJECT_REASON` enum

See details in srt.h

BTW. The value 10 is `SRT_REJ_RDVCOOKIE`. This is something that should virtually never happen in a normal situation, but it actually does happen in case of a wrong configuration when you are trying to connect to yourself in rendezvous mode (that is, the target address used in `srt_connect` is your local address).

Now, the reject reason: you can't get the reject reason on the listener side. It's because the manners for the listener side is the same here as in TCP (except that TCP cannot reject a connection), that is, the accept call reports a connection that has been accepted, and beside that it can only report usage error. That is, this function doesn't report a situation that the connection has been rejected - it's just silent and does nothing, while the rejected connection is handled in the background.

In order to be able to report events like this, some other function would have to be used (implemented for it) and in a specific manner. Also it should be agreed that a history of such events cannot be stored - at best it can keep only the last one or some limited number of them. For that we haven't seen any need so far. Most important thing here is that this is an event that happens and there's currently no way to inform the application hosting the listener that such a thing has happened.

**Comment by peterlee-inca** [comment]
Hi ethouris,

Your explanation was helpful in understanding how the reject mechanism works as a Listener. I guess this would have to be a new "feature" to be considered in the future, if there is enough need for it. It would certainly be useful for us.

Also, I did try calling srt_getlasterror() and srt_getrejectreason() and observed the following as a Caller with an incorrect passphrase (based on srt lib v1.3.3):
    - An epoll event was triggered on the corresponding socket where srt_getsockstate() returned SRTS_BROKEN
    - Calling srt_getlasterror() returned 0, and srt_getlasterror_str() returned "Success"
    - Calling srt_getrejectreason() returned 10 and srt_rejectreason_str() returned "Incorrect passphrase"

I have yet to see srt_getlasterror() return SRT_ECONNREJ, although I have seen the following in a loghandler message:
    `20:37:37.573330/SRT:RcvQ:worker*E:SRT.c: UU:newConnection: rsp(REJECT): 1002`

Is this also an expected behaviour? Perhaps things changed after v1.3.3?

Thank you.

**Comment by ethouris** [comment]
Remember, in any case, that if you don't call `srt_getlasterror()` as exactly the next call after the function that reports failure, the "last error" will not be correct. Note that getting an ERR event on epoll or BROKEN socket state is not understood as "the function that reports failure". The problem is that in this situation you don't have any "function" you could call to get the error code.

OTOH I think you can safely state that when you get the ERR epoll code on the connecting socket before you get the OUT readiness, the reason is that the connection was rejected or timed out. Although this recognition should be definitely improved - I'll make a ticket for it.

**Comment by ethouris** [comment]
Just got the information: value 10 is not RDVCOOKIE, but BADSECRET. It means that the encryption password was set differently on the connection sides.
