### ISSUE TITLE
CTimer::triggerEvent()

### ISSUE THREAD

**Issue by xfayh** [Haivision/srt#1192]
SendCtrl (UMSG_ACK);There are two CTimer::triggerEvent() calls, one inside m_pRcvBuffer->ackData(acksize), one behind, why?

**Comment by maxsharabayko** [comment]
Hm... 🤔  Good question. It might be something to improve.

There are actually three such calls:
1. from `CRcvBuffer::ackData(..)`
2. from `ackDataUpTo::ackDataUpTo(..)`
3. from sendCtrl(UMSG_ACK)
These functions are executed in the given order and call `triggerEvent()`.

**Comment by xfayh** [comment]
Will multiple calls to triggerEvent() affect CUDTUnited::selectEx efficiency?

**Comment by ethouris** [comment]
This is what happens:

1. select/selectEx/epoll_wait functions after having seen that none of the sockets reported readiness, enter the waiting by calling `waitForEvent`. After exitting this function, they check readiness again, and possible again fall asleep here. This sleeping happens up to some limited time (10ms).

2. When `trigggerEvent` is called, the above call to `waitForEvent` (although only one in the process, AFAIK, as it uses `notify_one`) exits prematurely. Otherwise it waits up to full 10ms.

This means that it would worsen performance only on case when the wakeup by `triggerEvent` is effectively spurious - that is, even though `triggerEvent` has fired, the reported event didn't touch upon any sockets for which this function is waiting. If you have only one thread and one case of bar-readiness-waiting call in your application, this shouldn't be a case at all. This might be a case if you had multiple various "socket sets" used in different threads and you check them separately - in this case you might have a case when the trigger touches upon a socket that belongs to a different set, while all waiters for all sets are being forced to recheck sockets prematurely.

OTOH don't forget that this trigger is used only if the readiness state has changed, so this call is necessary in order to have a good enough time accuracy between the moment when the event has happened and the moment when it's handled.
