### ISSUE TITLE
[BUG] Invalid pktRcvAvgBelatedTime value 

### ISSUE THREAD

**Issue by ddv2005** [Haivision/srt#1220]
On packets loss pktRcvAvgBelatedTime value is invalid (for example 9.00201e+15 or 6640827866535294.00)
**To Reproduce**
Run srt-live-transmit on two machines and simulate packet loss by iptables -A INPUT -m statistic --mode random --probability 0.01 -j DROP

**Screenshots**
======= SRT STATS: sid=148595896
PACKETS     SENT:           0  RECEIVED:         10060
LOST PKT    SENT:           0  RECEIVED:            55
REXMIT      SENT:           0  RECEIVED:            62
DROP PKT    SENT:           0  RECEIVED:             0
FILTER EXTRA  TX:           0        RX:             0
FILTER RX  SUPPL:           0  RX  LOSS:             0
RATE     SENDING:           0  RECEIVING:      3.14875
BELATED RECEIVED:           4  AVG TIME:   9.00201e+15
REORDER DISTANCE:           0
WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           1
LINK         RTT:     7.993ms  BANDWIDTH:   111.84Mb/s
BUFFERLEFT:  SND:    12288000  RCV:           12211500

**Comment by mbakholdina** [comment]
Hi @ddv2005 ,
- Please describe in more details the test setup you are using,
- I would appreciate if you could collect both receiver and sender statistics in `.csv` format for further analysis. To do so please use the following options of `srt-live-transmit`: `--statsfile [filename].csv --pf csv --s 1000` where
```
-statsout - SRT statistics output: filename. Without this option specified, the statistics will be printed to the standard output.
-pf, -statspf - SRT statistics print format. Values: json, csv, default.
-s, -stats, -stats-report-frequency - The frequency of SRT statistics collection, in packets.
```
- Do you mean `AVG TIME` in front of `BELATED RECEIVED`? Where exactly do you see the problem? Please provide some details.

`AVG TIME` corresponds to [pktRcvAvgBelatedTime](https://github.com/Haivision/srt/blob/master/docs/statistics.md#pktrcvavgbelatedtime), `BELATED RECEIVED` corresponds to [pktRcvBelated](https://github.com/Haivision/srt/blob/master/docs/statistics.md#pktrcvbelated). Maybe this answers your question.

Please also feel free to use the script [srt-stats-plotting](https://github.com/mbakholdina/srt-stats-plotting) for the SRT statistics visualization and analysis.

**Comment by mbakholdina** [comment]
Some notes on the topic:

1. According to the documentation `pktRcvAvgBelatedTime` is "Accumulated difference between the current time and the time-to-play of a packet that is received late". First mismatch: “accumulated” and Avg notation. Should be corrected.

2. The intention for this statistic was to present the average time between the expected delivery time (TSBPD time) and the time when the packet arrived, counted for all BELATED packets (that is, packets that arrived too late to be taken into account). This statistic was intended to be a hint for the user as to how much too optimistic their latency setting is.

3. How the calculation is currently being done according to the code
```
delta = Tnow - Tplay,

if (pktRcvAvgBelatedTime == 0)
    pktRcvAvgBelatedTime = delta;
else
    pktRcvAvgBelatedTime = pktRcvAvgBelatedTime + 0.2 * (delta - pktRcvAvgBelatedTime)
```
where `Tplay` - expected play time of the belated packet, `Tnow` - current time.

4. Suggested improvements.

According to @ethouris :
It is probably incorrectly calculated. It was introduced during the research done for the needs of the packet reordering problems. Actually I'm not exactly sure about it. It should be rather something like the maximum observed belated time, but limited in time. This would require collecting it in an array and remembering the time of the measurement, probably shifted to the left as new data are added, and recalculating from scratch if the last remembered value becomes outdated. As, I think, the most interesting thing for a user would be how much latency penalty it costs them to ensure that there are no drops.

A suggestion from @mbakholdina :
```
error = Tnow - Tplay
pktRcvAvgBelatedTime[0] = abs(error[0])
pktRcvAvgBelatedTime[t] = (pktRcvAvgBelatedTime[t-1] + abs(error[t])) / 2
```

If there is a need to assign a weight, I would suggest assigning higher weight to the latest error `abs(error[t])` value rather than the older `pktRcvAvgBelatedTime[t-1]` value.

Additionally, we can calculate the maximum absolute error.

**Comment by mbakholdina** [comment]
Hi @ddv2005, 
Do you have any updates on the comment I left you on April, 20?
