### ISSUE TITLE
[BUG]coredump,because srt_create_socket() return number is too small,(negative number not -1)

### ISSUE THREAD

**Issue by kyolong** [Haivision/srt#1221]
In one if my tests, first srt socketet id  is 103600.
when i  call srt_create_socket()   more then  103600 times
return value  is 0
next -1, -2 -3 

when srt_close() the srt socket id -3,  coredump

**Comment by ddv2005** [comment]
Looks like it is already fixed in master. What version you are using?

**Comment by kyolong** [comment]
1.4.1

**Comment by ethouris** [comment]
There was a problem since the original UDT code that there was no check as to how much the generated number can be changed. The procedure is that the first one is random-generated and all next ones by decrementing this number - and there was no check for it.

This problem will be fixed in 1.5.0. The incoming socket groups support required that socket groups also get generated IDs and this problem was discovered at that time, so beside the group support in this generation, this problem is fixed, too.

**Comment by maxsharabayko** [comment]
Closing as fixed in the current master.
