### ISSUE TITLE
[BUG] srt_epoll_wait() is triggered too often when two system file descriptors are added

### ISSUE THREAD

**Issue by peterlee-inca** [Haivision/srt#1251]
If we add 2 System FD's through srt_epoll_add_ssock(), then srt_epoll_wait() will get triggered continuously even though we call a read() on both FD's. This issue has been observed with the following System FD's (but not limited to):
1. Add 1 EventFD and 1 TimerFD
2. Add 2 TimerFD's

Please advise if there is a known issue with regards to this behavior or if the way that the SRT API used is incorrect.

1. Update <srt-live-transmit.cpp> with 2 Timer FD's. Please see attached file, which was based on v1.4.1 and the code added are marked with "New test code". Note that timer_fd_01 has a period of 3 seconds and timer_fd_02 has a period of 2 seconds.
2. Compile and run test using "srt-live-transmit udp://239.222.111.43:1234 -o "srt://10.239.253.161:1235?mode=caller""
3. See the following output:
    Media path: 'udp://239.222.111.43:1234' --> 'srt://10.239.253.161:1235?mode=caller'
    TEST> add timer_fd_01 to pollid result: 0
    TEST> add timer_fd_02 to pollid result: 0
    TEST> received timer_fd_02 signal, timestamp = Wed Apr 22 15:37:56 2020
    TEST> received timer_fd_01 signal, timestamp = Wed Apr 22 15:37:57 2020
    TEST> received timer_fd_02 signal, timestamp = Wed Apr 22 15:37:58 2020
    TEST> received timer_fd_01 signal, timestamp = Wed Apr 22 15:38:00 2020
    TEST> received timer_fd_02 signal, timestamp = Wed Apr 22 15:38:00 2020
    TEST> received timer_fd_02 signal, timestamp = Wed Apr 22 15:38:00 2020
    TEST> received timer_fd_02 signal, timestamp = Wed Apr 22 15:38:00 2020
    TEST> received timer_fd_02 signal, timestamp = Wed Apr 22 15:38:00 2020
    TEST> received timer_fd_02 signal, timestamp = Wed Apr 22 15:38:00 2020
    TEST> received timer_fd_02 signal, timestamp = Wed Apr 22 15:38:00 2020
    TEST> received timer_fd_02 signal, timestamp = Wed Apr 22 15:38:00 2020
    TEST> received timer_fd_02 signal, timestamp = Wed Apr 22 15:38:00 2020
    TEST> received timer_fd_02 signal, timestamp = Wed Apr 22 15:38:00 2020
    TEST> received timer_fd_02 signal, timestamp = Wed Apr 22 15:38:00 2020
    TEST> received timer_fd_02 signal, timestamp = Wed Apr 22 15:38:00 2020
    TEST> received timer_fd_02 signal, timestamp = Wed Apr 22 15:38:00 2020
    TEST> received timer_fd_02 signal, timestamp = Wed Apr 22 15:38:00 2020
    TEST> received timer_fd_02 signal, timestamp = Wed Apr 22 15:38:00 2020
    TEST> received timer_fd_02 signal, timestamp = Wed Apr 22 15:38:00 2020
    ...
4. Observe that timer_fd_02 is triggered correctly for the first two events, but gets triggered continuously after the third event.

**Expected behavior**
The expected behavior is to see the timer signal triggered just once per period and work reliably over time.

**Desktop (please provide the following information):**
 - OS: Debian 4.7.2-5 with gcc 4.7.2
 - SRT Version / commit ID: 1.3.3 and 1.4.1

[srt-live-transmit_cpp.txt](https://github.com/Haivision/srt/files/4519410/srt-live-transmit_cpp.txt)

**Comment by ethouris** [comment]
Did you try to code and test the expected behavior as well?

This is Linux, so epoll system is used to check readiness on system sockets. This can be then done by creating simultaneously a system epoll container and add the same FDs to it, then whenever SRT waiting function reports readiness, check the readiness (by waiting with 0 timeout) also on the system epoll.

**Comment by peterlee-inca** [comment]
Yes, I believe calling the system epoll right after calling srt_epoll_wait could work. I have not tested with epoll, but did test with poll by itself in a separate thread.

I'm not sure if I would want to add more than one system socket on the srt_epoll at this point, as that would trigger too many unwanted events, but your suggestion did give me another idea where I could call srt_epoll_wait and then poll (one after the other, instead of one inside the other) where poll would handle all the other system sockets that needs monitoring. This would work as long as the timeout of srt_epoll_wait is short enough and the "jitter" that may be introduced by the activities between srt_epoll_wait and poll can be acceptable. Right now, I have one high resolution Event FD that I need to keep under srt_epoll and two other low resolution Timer FD's that I can move to poll, and I think this could be a reasonable workaround.

Thank you.

**Comment by ethouris** [comment]
Mind first of all how the epoll waiting in SRT is implemented.

It simply waits for any readiness on the SRT sockets, up to the timeout of 10ms. If the time elapses - or it was interrupted by `triggerEvent` - the system sockets readiness is being checked by the system waiting function with timeout 0. This function then simply reports directly what the system function has provided.

Any error in the implementation in SRT could be when our SRT waiting function reports different state than can be otherwise obtained by the system waiting function.

Note that the SRT waiting function need not be really accurate because of that implementation. People often prefer therefore to track exclusively SRT sockets in the SRT waiting function, while tracking system sockets in another thread with a system waiting function.

**Comment by ethouris** [comment]
Ok, I did that for you. I made more fixes - like for example I'm clearing out the system sockets array after the readiness is handled because you don't check the number of ready sockets in the array and therefore your check gets a misleading result when checking `sysrfds[1]` after `srt_epoll_wait` returned 1. Zeroing the array doesn't fix the problem, but at least clears off the previous fd information (as you don't read from stdin :D).

Hard to say as to how my results are expected, however I can see no spurious readiness reports here.
```
TEST> add timer_fd_01 to pollid result: 0
TEST> add timer_fd_02 to pollid result: 0
TEST> received timer_fd_02 signal, timestamp = Mon Apr 27 18:39:48 2020
TEST> ... also ready in epoll
TEST> ... read: =8 v=1
TEST> received timer_fd_01 signal, timestamp = Mon Apr 27 18:39:49 2020
TEST> ... also ready in epoll
TEST> ... read: =8 v=1
TEST> received timer_fd_02 signal, timestamp = Mon Apr 27 18:39:50 2020
TEST> ... also ready in epoll
TEST> ... read: =8 v=1
TEST> received timer_fd_01 signal, timestamp = Mon Apr 27 18:39:52 2020
TEST> ... also ready in epoll
TEST> ... read: =8 v=1
TEST> received timer_fd_02 signal, timestamp = Mon Apr 27 18:39:52 2020
TEST> ... also ready in epoll
TEST> ... read: =8 v=1
TEST> received timer_fd_02 signal, timestamp = Mon Apr 27 18:39:54 2020
TEST> ... also ready in epoll
TEST> ... read: =8 v=1
TEST> received timer_fd_01 signal, timestamp = Mon Apr 27 18:39:55 2020
TEST> ... also ready in epoll
TEST> ... read: =8 v=1
TEST> received timer_fd_02 signal, timestamp = Mon Apr 27 18:39:56 2020
TEST> ... also ready in epoll
TEST> ... read: =8 v=1
TEST> received timer_fd_01 signal, timestamp = Mon Apr 27 18:39:58 2020
TEST> ... also ready in epoll
TEST> ... read: =8 v=1
TEST> received timer_fd_02 signal, timestamp = Mon Apr 27 18:39:58 2020
TEST> ... also ready in epoll
TEST> ... read: =8 v=1
TEST> received timer_fd_02 signal, timestamp = Mon Apr 27 18:40:00 2020
TEST> ... also ready in epoll
TEST> ... read: =8 v=1
TEST> received timer_fd_01 signal, timestamp = Mon Apr 27 18:40:01 2020
TEST> ... also ready in epoll
TEST> ... read: =8 v=1
TEST> received timer_fd_02 signal, timestamp = Mon Apr 27 18:40:02 2020
TEST> ... also ready in epoll
TEST> ... read: =8 v=1
TEST> received timer_fd_01 signal, timestamp = Mon Apr 27 18:40:04 2020
TEST> ... also ready in epoll
TEST> ... read: =8 v=1
TEST> received timer_fd_02 signal, timestamp = Mon Apr 27 18:40:04 2020
TEST> ... also ready in epoll
TEST> ... read: =8 v=1
TEST> received timer_fd_02 signal, timestamp = Mon Apr 27 18:40:06 2020
TEST> ... also ready in epoll
TEST> ... read: =8 v=1
TEST> received timer_fd_01 signal, timestamp = Mon Apr 27 18:40:07 2020
TEST> ... also ready in epoll
TEST> ... read: =8 v=1
```
[srt-live-transmit_cpp.txt](https://github.com/Haivision/srt/files/4540950/srt-live-transmit_cpp.txt)

**Comment by peterlee-inca** [comment]
Hi ethouris,

Thank you for providing the updated sample code!

I wasn't aware that I needed to check the number of ready sockets in the array. Tried your code and it's working well.
