### ISSUE TITLE
Queries regarding Socket group connections

### ISSUE THREAD

**Issue by vasudevavarun** [Haivision/srt#1268]
Greetings,

I am using "**srt-test-live**" for testing of primary to backup switching in case of failure, I've been stuck with nothing but errors, Can you guys help me with that?
**System:**
OS: Centos 7.7 x64

**Transmitter:**
While using group connect, I'm receiving the following:

> ./srt-test-live udp://225.1.1.52:5152 -g "srt://0.0.0.0:8888?mode=server&groupconnect=true" -v
> Multicast: home address: INADDR_ANY:5152
> Multicast(POSIX): will bind to IGMP address: 225.1.1.52
> SRT parameters specified:
> 
>         groupconnect = 'true'
> 
>         mode = 'server'
> 
> Opening SRT target listener(blocking, backlog=10) on 0.0.0.0:8888
> WARNING: failed to set options: 
> groupconnect, 
> 
> ERROR (app): ConfigurePre
> Open FAILED - closing SRT sockets
> MEDIA CREATION FAILED: ConfigurePre - exiting.

I've tried with and without using '-g' and 'mode=server' but the result are same.
Although, If I remove **groupconnect=true**, The socket seems to be waiting for connection.

> srt-test-live udp://225.1.1.52:5152 -g "srt://0.0.0.0:8888?mode=server" -v
> Multicast: home address: INADDR_ANY:5152
> Multicast(POSIX): will bind to IGMP address: 225.1.1.52
> SRT parameters specified:
> 
>         mode = 'server'
> 
> Opening SRT target listener(blocking, backlog=1) on 0.0.0.0:8888
> Binding a server on 0.0.0.0:8888 ...
>  listen...  accept...  accept...

Now with using the command without groupconnect=true option on the transmitter, I am having the following errors on the receiver.

> srt-test-live "srt://*?type=broadcast&latency=500" "srt://x.x.x.x:8888" -g udp://224.1.1.1:4111 -v
> NOTE: INPUT specification set as: srt:////group?latency=500&type=broadcast&nodes=x.x.x.x:8888,
> SRT parameters specified:
> 
>         latency = '500'
> 
>         nodes = 'x.x.x.x:8888,'
> 
>         type = 'broadcast'
> 
> Opening SRT source caller(blocking, backlog=1) on :0
> REDUNDANT connections with 1 nodes:
> Connecting to nodes:
>         [1] x.x.x.x:8888?weight=0 ... 14:34:48.570550/SRT:RcvQ:w1*E:SRT.c: processAsyncConnectRequest: REJECT reported from HS processing, not processing further.
> 14:34:48.571226/SRT:RcvQ:w1*E:SRT.c: RendezvousQueue: processAsyncConnectRequest FAILED. Setting TTL as EXPIRED.
> FAILURE
> srt_connect_group: [1002] Connection rejected: [0]: Unknown or erroneous
> Open FAILED - closing SRT sockets
> MEDIA CREATION FAILED: error: srt_connect_group: Connection setup failure: connection rejected - exiting.

and connection get rejected on the Transmitter:

> srt-test-live udp://225.1.1.52:5152 -g "srt://0.0.0.0:8888?mode=server" -v
> Multicast: home address: INADDR_ANY:5152
> Multicast(POSIX): will bind to IGMP address: 225.1.1.52
> SRT parameters specified:
> 
>         mode = 'server'
> 
> Opening SRT target listener(blocking, backlog=1) on 0.0.0.0:8888
> Binding a server on 0.0.0.0:8888 ...
>  listen...  accept...  accept...19:04:47.146692/SRT:RcvQ:w1*E:SRT.c: HS/GROUP: this socket is not allowed for group connect.                                                            
> 19:04:47.147083/SRT:RcvQ:w1*E:SRT.c: @316651550:newConnection: connection rejected due to: CONNECTION REJECTED                                                                          
> 19:04:47.147177/SRT:RcvQ:w1*E:SRT.c: UU:newConnection: rsp(REJECT): 1015 - Group settings collision

Will really appreciate the help.
Thanks in advance, Stay Safe.

**Comment by ethouris** [comment]
The SRT socket group code is currently experimental and it's under development. This will be available in the next release; the current latest version may contain some intermediate-experimental version, which may still undergo changes.

First, we changed the data type of `groupconnect` option - it is now integer and possible values are 0 (default) or 1. This option should be set on the **listener** socket, so you set it only on the URI that specifies `mode=listener` (or "server"). When set to 1 it allows the listener to accept group connections.

The `-g` option on the other hand is intended for the **caller** side only, and it allows to specify the group connection with multiple addresses. In order to avoid very easily made mistakes, it is recommended to use the following syntax at the caller side:

`-g 'srt://*?type=backup&<other-options...>' <IP1:port1> <IP2:port2>...`

The last specifications you made are probably ok, you just need to add `groupconnect=1` in this last command:

srt-test-live udp://225.1.1.52:5152 -g "srt://0.0.0.0:8888?mode=server **&groupconnect=1** " -v

(spaces are here visible to allow BOLD in markdown so that it is highlighted)

Note also that in order to enforce the listener mode, you can simply omit the "host" part in the URI, which makes `mode` default to `server`:

`srt://:8888?groupconnect=1`

**Comment by ethouris** [comment]
The SRT socket group code is currently experimental and it's under development. This will be available in the next release; the current latest version may contain some intermediate-experimental version, which may still undergo changes.

First, we changed the data type of `groupconnect` option - it is now integer and possible values are 0 (default) or 1. This option should be set on the **listener** socket, so you set it only on the URI that specifies `mode=listener` (or "server"). When set to 1 it allows the listener to accept group connections.

The `-g` option on the other hand is intended for the **caller** side only, and it allows to specify the group connection with multiple addresses. In order to avoid very easily made mistakes, it is recommended to use the following syntax at the caller side:

`-g 'srt://*?type=backup&<other-options...>' <IP1:port1> <IP2:port2>...`

The last specifications you made are probably ok, you just need to add `groupconnect=1` in this last command:

srt-test-live udp://225.1.1.52:5152 -g "srt://0.0.0.0:8888?mode=server **&groupconnect=1** " -v

(spaces are here visible to allow BOLD in markdown so that it is highlighted)

Note also that in order to enforce the listener mode, you can simply omit the "host" part in the URI, which makes `mode` default to `server`:

`srt://:8888?groupconnect=1`

Note also that this allows for the "all-interface-binding" mode, that is, the listener binds to all interfaces, and you are using different network interfaces for particular link over a different network path. The other method is to use multiple listener sockets, each one bound to exactly one interface. To try out this method, you can use `srt-test-mpbond` application.

**Comment by vasudevavarun** [comment]
Hello @ethouris,
Thank you for reply. I'm trying to test a fail-over scenario here in which the srt application can auto switch to backup stream in case it fails to get data from primary stream.
With the commands you mentioned above in the comment, I have got the following response.

**Transmitter** 

> ./srt-test-live udp://225.1.1.52:5152 "srt://0.0.0.0:8888?mode=listener" -v
> Multicast: home address: INADDR_ANY:5152
> Multicast(POSIX): will bind to IGMP address: 225.1.1.52
> SRT parameters specified:
> 
>         mode = 'listener'
> 
> Opening SRT target listener(blocking, backlog=1) on 0.0.0.0:8888
> Binding a server on 0.0.0.0:8888 ...
>  listen...  accept...  accept...

**Caller**

> ./srt-test-live -g 'srt://*?type=backup' IP1:8888?pri=0 IP2:8888?pri=1 udp://225.1.1.99:9900 -v                                                                                        
> NOTE: INPUT specification set as: srt:////group?type=backup&nodes=IP1:8888?pri=0,IP2:8888?pri=1,                                                                                                  
> SRT parameters specified:
> 
>         nodes = 'IP1:8888?pri=0,IP2:8888?pri=1,'
> 
>         type = 'backup'
> 
> 
> ERROR (app): With //group, only type=broadcast is currently supported
> MEDIA CREATION FAILED: With //group, only type=broadcast is currently supported - exiting.

Although, While using type=broadcast it is working almost fine just getting some error while switching from primary to backup sometimes.

**Comment by ethouris** [comment]
The `type=broadcast` isn't switching. It simply sends the same stream over every link specified in the group. There's no logic, no triggering, nothing. It should simply continue on remaining alive link as long as it still has at least one. In this mode it also tries to reconnect a broken link.

**Comment by vasudevavarun** [comment]
As you have mentioned **type=backup**, but any mode other than broadcast is not working as stated in logs above.

**Comment by ethouris** [comment]
This message might be misleading. We had intermediate steps with merging particular parts. Currently broadcast and backup groups are supported, balancing are waiting for the final fixes.

Just note that until the version is released, changes in the experimental version might break backward compatibility with earlier experimental versions - so when updating, make sure that all involved devices get the exactly same version of experimental SRT.

**Comment by KvanSteijn** [comment]
We are using keepalived on system niveau for managing incoming traffic. If the main primary server failed, everyone wil switch automatisch to the backup server. Only thing is that everyone need to reconnect again and do the handshake with SRT. Your implementation of groups with failover is only useful if we are using one server with multiple out coming uplinks if i understand it correctly?

**Comment by ethouris** [comment]
In practice, every link should use a different network path - so that a link break on one path doesn't influence the health of the other link.

And the "backup" type is used exactly for that purpose. In this case you have all links connected, but only one is transmitting. In this case you don't reconnect again - you have all links connected, just only one of them is transmitting, unless this one gets broken, in which case the traffic is switched immediately to another link - just describing in short.

**Comment by KvanSteijn** [comment]
Thank you for your advise, but still all links are connection to **one** server if i understand correctly. It's not possible to share the socket information between servers to prevent a disconnect?

**Comment by ethouris** [comment]
Not sure what you mean by "share socket information". Even in the system you cannot bind multiple UDP sockets to one port - and the port information must be used as defined by the other side.

Or I don't understand what you mean by "one server". I think it's obvious that the receiver over these multiple connections must be on one device and the same application. But it does't mean it can only use one service port - multiple listener ports, especially if you want to bind on only selected NICs, are possible.

**Comment by maxsharabayko** [comment]
I think, @KvanSteijn means having 2 redundant servers instead of 1 server with two NICs.
It is possible but has to be done on an application level, not the library level. You just establish two SRT connection, and, e.g. stream the same content over those two links.

**Comment by KvanSteijn** [comment]
The setup looks like that you have lister that is pushing streams to clients one (physical) host/server. The SRT implementation is running on this (physical) server. If one of your netwerk links are down, you can configure with group socket to failover automatic to second network link. But if you (physical) server have hardware problems and the host is completely down. Then is also the application with SRT down. With keepalived you can fix this problem to traffic all data to other server, but you will get disconencted from your client. It's should be nice if SRT can send information about SRT connections/clients between servers with crossovers. That the backup server have exactly the same information as the main server. When the main server is down that the clients doesn't disconnect and have the same behaviour as backup solution in groups.

**Comment by ethouris** [comment]
The question is however how the active and redundant server exchange information between one another. Because it's easy to define stream continuity when you have all instances in one application - another question is how it is defined when you have potentially two different network endpoints, each one with its own application, and intend to receive the same stream, and the reception process is defined as one, regardless who the physical receiver is.

Currently there's no way how to solve it now inside SRT, at least we'd need to understand the full use case better. But it can be done within one application by simply maintaining multiple connections, just use only one at a time for transmission. However the application would have to somehow also detect the early link broken state.

**Comment by J-Rogmann** [comment]
Hello @vasudevavarun 
I'm currently working through older tickets and found yours here, which seemed to not have been answered completely.

There was a small mistake in your setup. 
in your first part you created a SRT listener, however only for a single connection, not a bonded group: 
`./srt-test-live udp://225.1.1.52:5152 "srt://0.0.0.0:8888?mode=listener" -v` should be changed to following:
`./srt-test-live udp://225.1.1.52:5152 "srt://:8888?groupconnect=1" -v`

The Caller should be configured like following:
`./srt-test-live  '-g' 'srt://*?type=backup' 'IP1:8888?weight=80' 'IP2:8888?weight=20' udp://225.1.1.99:9900 -v`

Please note a couple of changes introduced in 1.4.2:
- priority of a link is set by `weight`... the higher the `weight`, the more important a link is and should be used first by the protocol
- to enable bonding feature, you need to compile with: `--enable-experimental-bonding`

Please also note, that bonding is still in experimental phase and should not be used for production purpose yet. 

It would be nice, if you could let us know, if that works for you and if the ticket can be closed.

best regards,
Justus


> Hello @ethouris,
> Thank you for reply. I'm trying to test a fail-over scenario here in which the srt application can auto switch to backup stream in case it fails to get data from primary stream.
> With the commands you mentioned above in the comment, I have got the following response.
> 
> **Transmitter**
> 
> > ./srt-test-live udp://225.1.1.52:5152 "srt://0.0.0.0:8888?mode=listener" -v
> > Multicast: home address: INADDR_ANY:5152
> > Multicast(POSIX): will bind to IGMP address: 225.1.1.52
> > SRT parameters specified:
> > ```
> >     mode = 'listener'
> > ```
> > 
> > 
> > Opening SRT target listener(blocking, backlog=1) on 0.0.0.0:8888
> > Binding a server on 0.0.0.0:8888 ...
> > listen...  accept...  accept...
> 
> **Caller**
> 
> > ./srt-test-live -g 'srt://*?type=backup' IP1:8888?pri=0 IP2:8888?pri=1 udp://225.1.1.99:9900 -v
> > NOTE: INPUT specification set as: srt:////group?type=backup&nodes=IP1:8888?pri=0,IP2:8888?pri=1,
> > SRT parameters specified:
> > ```
> >     nodes = 'IP1:8888?pri=0,IP2:8888?pri=1,'
> > 
> >     type = 'backup'
> > ```
> > 
> > 
> > ERROR (app): With //group, only type=broadcast is currently supported
> > MEDIA CREATION FAILED: With //group, only type=broadcast is currently supported - exiting.
> 
> Although, While using type=broadcast it is working almost fine just getting some error while switching from primary to backup sometimes.

**Comment by J-Rogmann** [comment]
Hello @vasudevavarun

Do you have any updates on this ticket, or can it be closed?
Please let us know, if you still need help or how you solved it, in case you found the cause of the issue.

best regards,
Justus
