### ISSUE TITLE
[handshark] why Listener response to caller the timestamp is 0?

### ISSUE THREAD

**Issue by chllcy** [Haivision/srt#1273]
![image](https://user-images.githubusercontent.com/12612758/81402310-bc96a300-9163-11ea-99f9-a55764703d8f.png)

I find the problem,and The Conclusion Phase the listener response to caller the timestamp is 0. then the caller get CRcvBuffer::getTsbPdTimeBase not correct.because m_tsTsbPdTimeBase is set by setRcvTsbPdMod, and m_tsRcvPeerStartTime is zero。

so it‘s need to add setPacketTS(response, steady_clock::now()); in CUDT::acceptAndRespond ?

**Comment by maxsharabayko** [comment]
Please add details on which SRT version you use.

**Comment by ethouris** [comment]
`CUDT::open`, which is called at the binding time (included automatic one when you don't specify the bind address for the caller socket) calls `CUDT::clearData`, which sets `m_tsRcvPeerStartTime` to the current time. At the listener the same is done when you do bind, obligatory this time. It's then not possible that this field be 0.

What is important for timestamp in the handshake packet is that times are not recorded in fields basing on the timestamp from the packet, but it's simply taken as current time at the moment when the packet comes in.

Setting and interpreting the timestamp field makes sense only when you know exactly when it was set at the moment of some interesting event which's time you need to know, and when you know that the packet was sent immediately thereafter. With handshake the problem is that one side may take some time to process the request and in some cases the delay may be even extended, in which case this time would not be reliable anyway. What is more, in order to reliably interpret the time from the timestamp you need to KNOW the base time towards which the distance will be calculated (the timestamp field in the packet contains a 32-bit relative time towards the base, moreover, an overflow and rollback of this 32-bit value after about 2.5 minutes is also taken into account). It's therefore useless to set this timestamp to any value, and its value in the handshake is disregarded.

**Comment by chllcy** [comment]
thanks.It's true that the time is not reliable anyway.
today I test used tc to drop packet random. I find a problem that listener response( Conclusion Phase ) to caller with error HS Extension type.the first packet response was droped.so it's second time to response to caller.
read the log,I find second response in CUDT::processConnectRequest, with log "processConnectRequest: sending ABNORMAL handshake info"
so is it correct? normally it's SRT_CMD_HSRPS.
![image](https://user-images.githubusercontent.com/12612758/81694376-d4d42e00-9493-11ea-836c-f9ddd1776705.png)

**Comment by ethouris** [comment]
That looks strange indded. The log attached to "sending ABNORMAL handshake info" sends back the handshake, but it should contain no extensions.

Have you seen also a log with `acceptAndRespond: creating CONCLUSION response`?

I suspect here is a bug in the size setting. I have even found that once and there's a fix provided for it in an incoming PR.
https://github.com/Haivision/srt/pull/1170/files#r388474533

**Comment by chllcy** [comment]
yes,the first time response to caller,the log is "14:40:37.458434/SRT:RcvQ:w1 D:SRT.c:  [-281700608] [core.cpp:5866] acceptAndRespond: creating CONCLUSION response (HSv5: with HSRSP/KMRSP) buffer size=1456"
but this packet was droped.

so after 1s,the caller send another conclusion,the listener come into "sending ABNORMAL handshake info".

**Comment by ethouris** [comment]
Yes, there was a bug there, which simply set wrong size on the packet so the packet came forward with added extensions. The fix just came in. That packet should state that the connection was rejected, although it's hard to imagine for me that there was once sent a proper connection response, the packet got lost, and then the connection was rejected.

**Comment by chllcy** [comment]
ok,thanks.

**Comment by zhouxiaojun2008** [comment]
> `CUDT::open`, which is called at the binding time (included automatic one when you don't specify the bind address for the caller socket) calls `CUDT::clearData`, which sets `m_tsRcvPeerStartTime` to the current time. At the listener the same is done when you do bind, obligatory this time. It's then not possible that this field be 0.
> 
> What is important for timestamp in the handshake packet is that times are not recorded in fields basing on the timestamp from the packet, but it's simply taken as current time at the moment when the packet comes in.
> 
> Setting and interpreting the timestamp field makes sense only when you know exactly when it was set at the moment of some interesting event which's time you need to know, and when you know that the packet was sent immediately thereafter. With handshake the problem is that one side may take some time to process the request and in some cases the delay may be even extended, in which case this time would not be reliable anyway. What is more, in order to reliably interpret the time from the timestamp you need to KNOW the base time towards which the distance will be calculated (the timestamp field in the packet contains a 32-bit relative time towards the base, moreover, an overflow and rollback of this 32-bit value after about 2.5 minutes is also taken into account). It's therefore useless to set this timestamp to any value, and its value in the handshake is disregarded.

I'm a little confused。The Conclusion Phase the listener response to caller the timestamp is 0，
Consider the following scenario,
When acting as a server and a data sender, there are the following codes (V1.4.1) in the processSrtMsg_HSRSP function,
“m_ullRcvPeerStartTime = CTimer::getTime()-(uint64_t)((uint32_t)ts);“
Now that the ts value is 0, is it a bit unprepared?
