### ISSUE TITLE
Authenticating an SRT Stream for Distribution

### ISSUE THREAD

**Issue by innerop** [Haivision/srt#1313]
I looked at the source and the recent IETF spec and could not find a clear answer for how we would specify a key for the SRT stream for authentication and authorization purposes. 

I want to ingest an SRT stream coming from one authenticated publisher and distribute to N non-authenticated consumers, via an SRT Server, which will convert it to SLDP for low-latency delivery to the consumers. The stream publisher typically needs to be authenticated so the stream can be tied to their account for billing purposes. 

Since it's UDP based, I can't use the auth_request module in NGINX to frontend the SRT Server. I am not aware of any other module and frankly I have not worked with UDP before as a protocol, so I have no clue how to implement a way to accept or reject the stream. 

I've noticed fields like Auth and KEKI in the spec submitted to IETF but I've not been able to find any explanation.

Please point me in the right direction.

Thank you.

**Comment by maxsharabayko** [comment]
Hi @innerop 
SRT Access Control Guidelines can be found in the following document: [link](https://github.com/Haivision/srt/blob/master/docs/AccessControl.md).
In short, in SRT-to-SRT connection, each user can have an individual passphrase known to the server. So that the server can tell this passphrase to SRT (via listener callback). SRT will check authentification, and accept or reject the user's connection attempt.

**Comment by ethouris** [comment]
Just for starters: SRT isn't "UDP-based". SRT uses UDP instrumentally for its transport purposes. Whatever extra would have to be done with the sent data (including encryption), it must be something between the application that produces the data and SRT library, not on the UDP protocol.

I have problems with proper understanding the description. You said you want that the authenticated publisher distribute the stream to N non-authenticated consumers, but the stream publisher needs to be authenticated. Whatever authentication needs to be done here, what counts for SRT is that SRT connection currently supports a PSK-based encryption. Using this, the following methods can be used:

1. One single password for everyone. Simply set the password on the listener side and callers must use it to connect.

2. Implement user-password database using the listener callback (you can find an example in the applications) so that per a user specified in StreamID you will set up an appropriate password in the listener callback so that the authentication is then verified against the right password.

3. Advanced authentication. First, make an SRT connection in file mode to interchange the authentication data, in result of which the client should receive a random-generated password for the session. The client then makes next the "real" SRT connection for stream transmission and this password (the listener callback will set the right password for the session).

**Comment by innerop** [comment]
Thank you for the link @maxsharabayko :-)

Hi @ethouris 

In my scenario, I bill only when someone publishes a stream. This is for a very niche app so I don't expect to have an issue using method #1 you mention to control the number of viewers for each stream. But I'm not sure the current HTML5 SLDP player supports sending a password.

For publisher authentication, method #3 looks ideal for my case but I'm have a web app so the exchange of authentication information would be done normally via HTTPS not via SRT. Once the client has the random generated token/password for the session it can send that with the SRT data.

**Comment by innerop** [comment]
@maxsharabayko 

I have some follow up questions :-)

" in SRT-to-SRT connection, each user can have an individual passphrase known to the server. So that the server can tell this passphrase to SRT (via listener callback). SRT will check authentification, and accept or reject the user's connection attempt."

This is what I need and the passphrase in my case is a signed token generated after the user authenticates via web/https path by entering their username and password into a web app that returns the signed token. The signed token has an expiration time and can be sent to publisher with the SRT data and it can also be stored on the server in a database, so that when publisher sends the token in the SRT stream it can be validated and the user_id  can be identified (from the token->user_id mapping or verifying the token is valid and was assigned to the user_id given in the SRT stream data, if there such a field in SRT data for user_id)

The idea of the SRT callback for verifying user is authenticated via token/passphrase is perfect.

Is there an implementation of such callback in this library?

**Comment by innerop** [comment]
FWIW, I like Alex' idea to use DTLS along with stream_id. Only comment is that I would expect user_id to be part of the stream data since stream_id maybe a randomly generated signed token (like JWT) so we'd need to look up in our database by user_id to associate with user (for authorization level etc) Same as done with any JWT based scheme, commonly used on the web.

**Comment by innerop** [comment]
Closing in favor of #1297

**Comment by maxsharabayko** [comment]
>I don't have much knowledge of PSK encryption, or how you'd prove that the expiration date in the passphrase hasn't been modified. If the password doesn't expire then it's akin to a hashed password, and that's totally fine if MITM attack scenario (to steal the token) is not possible or not in scope for this feature.

Both user and server have to only know the passphrase (e.g. "mysuperstrongpass").
Server just tells this passphrase to SRT, and SRT itself generates the key. This key is being updated during the transmission with a certain period.
The expiration of the passphrase per user or a group of users, if required, should be managed by the server.

Regarding the sample, let me share @ethouris recent reply in a thread of slack channel.

The [srt-test-live](https://github.com/Haivision/srt/blob/master/testing/srt-test-live.cpp) application contains an example hook for user-password authentication. Run the application with SRT listener as a medium and add -hook user-password option. This will install a listener callback that is implemented in a SrtUserPasswordHook function in the main source file of this application. This works very simple way:
1. Extract the username from the contents of StreamID of the incoming connection
2. For that username, find it in the database. If not found, return false (or allow an exception to be thrown), which will result in rejection
3. If found, set the passphrase onto the pending accepted socket. The handshake will then continue and the incoming connection will be checked against this password.
