### ISSUE TITLE
Recommended approach for decoding/buffering when playing an SRT stream?

### ISSUE THREAD

**Issue by oviano** [Haivision/srt#1450]
Is the intention that when you receive SRT packets that these should be decoded and displayed immediately, or should you always have a small buffer to account for the time it takes to decode, jitter, etc and schedule according to the PTS?

I was just wondering how the official SRT player apps do it.

In my player app I’ve been using a buffer of around 100ms (5 frames in a 50 FPS stream) to be on the safe side, but I’m wondering if this is too conservative, and I only need to keep a couple of frames at most

**Comment by ethouris** [comment]
The intention is that you should pack the packets into a buffer and make the splitter carve the frames, and put them into the decoder immediately. As I saw, ffmpeg for example collects 6 frames (possibly that's so by default) before it ships at least one decoded frame. Note also that frames are not necessarily sent in the playing order, so buffering a few frames inside the decoder is necessary anyway.

Generally the intention is that when you reassemble the first I-frame when the transmission starts, since this moment every frame should be submitted to the decoder once it's reassembled. Of course, P and B frames might be ready much in advance towards the play time, but that's not significant here - the most important is the time when the last packet of an I-frame arrives because this is the moment when the splitter submits the frame to the decoder. Should that be the question, then yes, this I-frame should be submitted immediately.

Note though that this relies on the fact that this last packet of an I-frame - like any other packet - is not given up to the application until the time comes - which time is defined in the packet's timestamp and defined at the sender side.

**Comment by oviano** [comment]
Thanks - so I submit packets immediately to the decoder as they come out of the SRT buffer, then my Q was really what is best practice for actually displaying the decoded frames that come out of the decoder. One of the key points of SRT is that if you feed it a live stream, that the packets coming out will be spaced the same as they went in, so I think there should only be a need for a small buffer of decoded frames?

I mean, compare that to lets say a TCP stream where packets might be delayed many amount of time, so you'd still decode packets as soon as you receive them, but you'd need a larger buffer to account for uneven spacing between packets caused by delays, resends etc.

**Comment by ethouris** [comment]
That's right. Actually the intention is that the time when the video frame should be played should be in a constant distance to the time when the last packet of the I-frame has been given up to the application and vary only a little (as much as the platform's timer accuracy allows).

**Comment by oviano** [comment]
Thank you. In practice, I have found it's necessary to dynamically monitor/adjust the number of frames buffered until the stream settles down.

Typically at the start, at least in my application, some of the initial frames may be sent closer together than normal (I think due to filter/encoder initialisation), and likewise on the player if you end up using a container format like mpeg-ts it ends up having to parse a certain amount of the data in order to get the required codec parameters for decoder initialisation, so again, this can cause the initial frames to arrive in a group from the decoder.

The optimum solution for low latency that seems to work for me is to aim for a certain number of frames buffered, say 2, and be ready to skip forward, or repeat frames if the number buffered goes too high (say 4) or too low (zero). I find after this that once the stream settles down after the first few seconds, and assuming a stable connection that things work well with minimal latency.

That is my approach, I'd be interested to hear about any others.

**Comment by ethouris** [comment]
For me it's hard to say. SRT is doing its best to keep the timing of packet delivery as accurate as possible. However this accuracy has limits in the form of what the user application can do and how reliable the platform is. This can be due to platform's internal timers accuracy, accurate thread switching and also doing system calls at the right time. The more the performance (and throughput) of the machine, the less jitter you'll have due to that, still up to some limit.
