### ISSUE TITLE
srt_sendmsg2 error code 2002 - sometimes recovers, sometimes doesn't

### ISSUE THREAD

**Issue by kavyarav** [Haivision/srt#1468]
Hi,
I am seeing a srt_sendmsg2() error with  `Connection does not exist, 2002` in the beginning of the connection regularly but after a few error messages, the send seems to work fine. On the other hand, sometimes the send never succeeds. Is there a way to distinguish between the two cases to trigger a reconnect. I am currently ignoring this error, but it causes no reconnect in cases when it never recovers.
For more context, I am using live mode to stream video images produced from an encoder onto a receiving station. Kindly let me know if you need more info from my side.

**Comment by ethouris** [comment]
Please show some code snippet that would suggest what you are doing.

I can imagine this to happen in one situation, when you use non-blocking mode (`SRTO_SNDSYN` and `SRTO_RCVSYN` set to false), if the application calls `srt_connect` and then after successful return it tries blindly to send data without checking if the socket is ready to write. This is a different situation to a sender buffer full situation reported by `SRT_EASYNCSND`.

That's my best guess, but to be sure, I'd have to understand what exactly your application is doing.

**Comment by kavyarav** [comment]
Hi, sorry for the delayed follow-up. You were right, we were using non-blocking mode. Also, as you suggested, we are trying to figure out if the socket is ready to write before writing.
We check if the socket state is SRTS_INIT or  SRTS_OPENED or SRTS_CONNECTING or SRTS_LISTENING to wait and not write yet. This seems to have helped us mitigate send failures with errors at the beginning of connection.

**Comment by ethouris** [comment]
Typically for recognition that the connecting socket becomes connected and ready for operation, you should check the ready-to-write status in epoll (SRT_EPOLL_OUT); using epoll allows you to also wait for the first ready socket.

Note also important thing that checking the status in epoll is the only way to get the "connection failed" status because even if the socket fails to connect, it doesn't turn into `SRTS_BROKEN` state, but remains in `SRTS_CONNECTING` state.

Typically then it is recommended that if you want to have asynchronous connection in your application, you should first subscribe the socket in epoll for OUT and ERR, then at the moment when you want to check it, verify if the socket is reported in read and write ready sockets in the epoll waiting function (note that there is no place to receive error-ready, but if there's an error on the socket, it's reported in both read-ready and write-ready, so as you didn't subscribe it for IN, then presence in read-ready means connection failure). After you get the write-readiness and NOT read-readiness, it means that your socket is connected and ready for operation, so if you are going to only READ from this socket, resubscribe it to IN and ERR (if you intend to write, just leave as is).
