### ISSUE TITLE
Need clarification on UDP medium

### ISSUE THREAD

**Issue by kmudide** [Haivision/srt#155]
The document stransmit.md states as follows:

**UDP can only be used in listening mode for reading, and in calling mode for writing.** 

That means I can't use stransmit as follows? 

Computer 1:
./stransmit udp://:11111 srt://10.1.50.7:22222?mode=caller

Computer 2(10.1.50.7):
./stransmit  srt://:22222?mode=listener udp://:11111

Above, on computer 1, stransmit reads from UDP in caller mode and on computer 2, stransmit writes to udp in listener mode, which is a contradiction to the document.

Also my understanding is that SRT encoder is the caller/client and decoder is the listener/server.

Please correct me, if I am wrong.

**Comment by ethouris** [comment]
There is no such thing as "writing to UDP in listener mode" because when you use the UDP socket for writing, you're just writing. Nothing is being received on it (at least in `stransmit` because it transmit the data in one direction only, from "source" to "target").

The terms of "caller mode" and "listener mode" state what exactly the host and port parameter passed in the URI mean:
- listener mode: the given host and port designate that address to bind locally, and the only "remote address" is meaningful only when someone "connects" (or sends) to it and it's the address of the remote party
- caller mode: the given host and port designate the remote address to which the socket will be connected (or to which packets will be sent)

The "mode" that you have specified in the above commands touches upon the SRT connection only (that's why it's a parameter passed in the URI, not a command-line option). That is, for example, in the first command, you use SRT in caller mode for writing, and UDP in the same command is used for reading in listening mode (that is, the host/port pair you have used in the URI specification have been used to `bind()` the socket to given host and port, with host designating the network device, here it's empty which translates to 0.0.0.0, understood by the system as `INADDR_ANY`, that is, it listens on all devices on given port). In the second command the UDP URI is target, and so it is used for writing in caller mode, that is, the socket isn't called `bind()` on at all, and the host and port in the URI designates the address that will be used as an argument to `sendto()` call. Here you have empty host as well, which is 0.0.0.0, and in this case it's interpreted as `localhost` (carefully with that statement though, this is not exactly portable).

Not sure how the latest version exposes that to the user, but at least in the system it is possible for a socket in caller mode to `bind()` as well; this can be used to set the outgoing port for the socket. There are only specific situations when it can be used; usually you simply left the socket unbound, when you want to use it in caller mode, and the outgoing port is "generated" by the system.

**Comment by kmudide** [comment]
I was thinking that mode is applied for both URIs and that is not true. Thanks for the explanation. I was confused with following commands, which are posted https://github.com/Haivision/srt/issues/86.

How would following command would work?

Computer1 (terminal2) 192.168.1.48:

./stransmit -v udp://:5000 "srt://192.168.1.48:9000?mode=server"

Computer2 (terminal1) 192.168.1.129:
./stransmit "srt://192.168.1.48:9000?mode=client" "file://con" | ffplay -

**Comment by ethouris** [comment]
AFAIK, this should work. client/server symbols are alternative to caller/listener.

This first command should read the live stream from the local UDP port 5000, then resend to a local SRT listener on port 9000 (if you have just one network device, you can simply skip the host part here). Note that this command will not start until the connection to this listener is made.

**Comment by kmudide** [comment]
On computer 1, stransmit is binding to 5000 (UDP listener) and 9000 (SRT listener) and On computer 2, stransmit is calling recvfrom with 192.168.1.129:9000?

**Comment by ethouris** [comment]
On computer 2 you don't use UDP, so you have no recvfrom. This is SRT, so it does `srt_connect()` to the given host/port (this is caller mode). The fact that it's then doing `srt_recvmsg` to read from it is a separate thing (SRT is connection-oriented, so it can work with whatever direction).

**Comment by kmudide** [comment]
Thanks. The SRT stream is coming from computer 1 to computer 2?

**Comment by ethouris** [comment]
Well, that's at least what results from binding these two commands by SRT.

**Comment by kmudide** [comment]
Thanks a lot for your time. Could you please respond to #154.

**Comment by kmudide** [comment]
That means following two sets have same affect?

SET 1:
    Computer1 (terminal2) 192.168.1.48:
     ./stransmit -v udp://:5000 "srt://192.168.1.48:9000?mode=server"
    Computer2 (terminal1) 192.168.1.129:
    ./stransmit "srt://192.168.1.48:9000?mode=client" "file://con" | ffplay -

SET 2:
    Computer1 (terminal2) 192.168.1.48:
     ./stransmit -v udp://:5000 "srt://192.168.1.129:9000?mode=client"
    Computer2 (terminal1) 192.168.1.129:
    ./stransmit "srt://:9000?mode=server" "file://con" | ffplay -

**Comment by ethouris** [comment]
From the functional point of view, actually yes. Maybe except the fact that - as long as you're not going to hit Enter on both computers at perfectly the same time - the command that specifies listener (server) mode for SRT should be started first.

**Comment by kmudide** [comment]
That brings another issue. In my case, server computer and client computer can be turned off and on  at anytime. Boot up script on these computers starts stransmit. 

I want  stransmit (client/server mode) running on one computer wait for another stranmist (server/client mode) running on another computer and keep running even when peer's computer turned off.

When I used conntimeo, stransmit is waiting for peer to come up, but exits as soon as peer's computer turned off. 

-t:-1 option has no impact.

**Comment by ethouris** [comment]
Well, I'm just changing the option handling in stransmit and I found out that the help text should be really improved indeed. The `-t` option defines the "transmission timeout", that is, the application will exit when no data are being received from the input for that long time (in seconds). Setting it to -1 turns it off. Default is 30.

If you want to make either of them connect another, the best way is to use the rendezvous mode:

Computer1 (terminal2) 192.168.1.48:
`./stransmit -v udp://:5000 "srt://192.168.1.129:9000?mode=rendezvous"`
Computer2 (terminal1) 192.168.1.129:
`./stransmit "srt://192.168.1.48:9000?mode=rendezvous" "file://con" | ffplay -`

**Comment by kmudide** [comment]
Thanks again. I really appreciate. I will test and let you know.

**Comment by adamyellen** [comment]
Hi @kmudide. Did you have an opportunity to test?
