### ISSUE TITLE
can't get udp respon on ubuntu

### ISSUE THREAD

**Issue by Misaki4115** [Haivision/srt#1656]
srt-live-transmit "srt://:4444?latency=0.1&congestion=live&transtype=live" udp://4445 -buffering=1 -s

using ffmepg&ffplay to stream&pull it can work on my macbook, but on ubutu server udp pull it not work anymore,always no respone , i try use 

srt-live-transmit "srt://:4444?latency=0.1&congestion=live&transtype=live" srt://4445 -buffering=1 -s

and change ffplay to srt and work again,is anyone get idea for it

**Comment by maxsharabayko** [comment]
Try `udp://:4445`. Please refer to the [URI syntax docs](https://github.com/Haivision/srt/blob/master/docs/srt-live-transmit.md#uri-syntax).

**Comment by Misaki4115** [comment]
thank first,but still not work , ffplay just no respone

**Comment by maxsharabayko** [comment]
I am afraid this command is incorrect. The destination in the case of UDP must explicitly define the target IP.
SRT determines the peer IP because it is a connection-based protocol, so `srt://:4445` will work.
In the case of UDP `srt-live-transmit` does not know where to send data to, therefore `udp://:4445` does not work.

```shell
srt-live-transmit "srt://:4444?latency=0.1&congestion=live&transtype=live" udp://4445 -buffering=1 -s
```

### TODO

- [ ] Do not allow to set destination UDP in `srt-live-transmit` without a host. Report an error.

**Comment by ethouris** [comment]
The specification of `udp://4445` is perfectly OK with the URI parser from SRT Support library - `udp://:4445` is simply the same thing.

Note that `udp://:4445` is a synonym for `udp://0.0.0.0:4445`, and this one need not be understood as one may thing on particular system. You should use statements like `udp://localhost:4445` or directly `udp://127.0.0.1:4445`. In general, `0.0.0.0` is used as a general IP matching mask, not an address, and using this address as a destination address is not portable, or even more precisely, whether it works, it depends on system configuration.
