### ISSUE TITLE
Bad behaviour with LTE connection

### ISSUE THREAD

**Issue by olivierayache** [Haivision/srt#1661]
Hello I am currently working with SRT for developping a live streaming solution. 

I have some problems with this specific configuration:
Client: Android phone on LTE network
Server: FFmpeg or srt-live-transmit (Ubuntu 18.04 and 20.04)

This configuration works for 5 to 10 seconds and then the connection seems to be broken.

I have already try to specify a packet size lower than the MTU of my LTE network interface (it seems to be 1300).

By analysing a network capture with Wireshark it seems threre is some problems with USMG_ACK packets. All of these packets are like this. I seems that the receive rate and speed is null.

![image](https://user-images.githubusercontent.com/7905861/99253035-4e1c5700-2810-11eb-90f3-c81388d11aa6.png)

On the other side when I use my Wifi network on the Android phone everything is ok. Here is the USMG_ACK packet

![image](https://user-images.githubusercontent.com/7905861/99253218-ab180d00-2810-11eb-92c1-383c6d621875.png)

I have already tried to increase the latency and the receive buffer size.

When I use my client on LTE network with a cloud system like Wowza Cloud everything is ok.

**Comment by mbakholdina** [comment]
Hi @olivierayache,
- What commands do you use when launching srt-live-transmit and ffmpeg as a server?
- What's your network conditions on LTE connection (RTT, etc.)?
- Could you please collect SRT statistics in .csv format from srt-live-transmit? And at the same time Wireshark dump, on both ends if possible and share with me?

**Comment by olivierayache** [comment]
Hi @mbakholdina thank you for your answer

For FFmpeg it is not a command, I use directly FFmpeg APIs in my projects but the equivalent line could be 
ffmpeg -i srt://IP:10000?mode=listener&latency=1000000 ...

For srt-live-transmit I use the following command ./srt-live-transmit -loglevel:debug srt://:10000?latency=1000 udp://127.0.0.1:1234

I have tried various latency since it is not easy to determine my RTT between the Android phone and my server.
I have tested various sizes of packets (1316 and 1128)

The knowledge I can give you about my LTE network are:
- MTU of physical interface on phone: 1300
- Ping 30 ms
- Download BW 63Mb/s
- Upload BW 9.5Mb/s

I will start a test on server side with srt-xtransmit application
I can't easily do a test on client side

**Comment by olivierayache** [comment]
Here is the results with srt-xtransmit:

```
17:51:23.722480 [I] Log level set to debug
17:51:23.722907/srt-xtransmit D:SRT.sm: generateSocketID: : @31343808
17:51:23.723006/srt-xtransmit D:SRT.km: CHANNEL: Bound to local address: 0.0.0.0:10000
17:51:23.723270 [D] SOCKET::SRT 0x1DE44C0 (srt://:10000) Listening
17:51:23.723308 [D] SOCKET::SRT 0x1DE44C0 (srt://:10000) ASYNC Waiting for incoming connection
17:51:29.403885/SRT:RcvQ:w1.N:SRT.cn: PASSING request from: 176.180.84.137:31387 to agent:31343808
17:51:29.404063/SRT:RcvQ:w1.N:SRT.cn: Listener managed the connection request from: 176.180.84.137:31387 result:waveahand
17:51:29.504251/SRT:RcvQ:w1.N:SRT.cn: PASSING request from: 176.180.84.137:31387 to agent:31343808
17:51:29.504368/SRT:RcvQ:w1 D:SRT.sm: generateSocketID: : @31343807
17:51:29.505467/SRT:RcvQ:w1.N:SRT.cn: HSREQ/rcv: cmd=1(HSREQ) len=12 vers=0x10401 opts=0xbf delay=120
17:51:29.505562/SRT:RcvQ:w1.N:SRT.cn: listen ret: -1 - conclusion
17:51:29.505587/SRT:RcvQ:w1.N:SRT.cn: Listener managed the connection request from: 176.180.84.137:31387 result:waveahand
17:51:29.505633 [D] SOCKET::SRT 0x1DE44C0 (srt://:10000) Accepted connection 0x1DE44BF
17:51:36.239171 [D] SOCKET::SRT 0x1DE44BF read::recv ERROR 2001 Connection was broken
17:51:36.239252 [W] RECEIVE read::recv: Connection was broken
17:51:36.323256 [D] SOCKET::SRT 0x1DE44BF Closing. Releasing epolls
17:51:36.323294 [D] SOCKET::SRT 0x1DE44BF Closing
17:51:36.323346 [D] SOCKET::SRT 0x1DE44C0 Closing. Releasing epolls
17:51:36.323374 [D] SOCKET::SRT 0x1DE44C0 Closing
```

**Comment by olivierayache** [comment]
[LteSrtXtransmit.dump.log](https://github.com/Haivision/srt/files/5548462/LteSrtXtransmit.dump.log)

[stats-rcv.csv.txt](https://github.com/Haivision/srt/files/5548471/stats-rcv.csv.txt)

**Comment by olivierayache** [comment]
Hi @mbakholdina 

I try some new tests yesterday and I finally found a systematic case of reproduction by using only srt-xtransmit.

I use a 4G hotspot to connect the client to the Internet. I launch srt-xtransmit on the client with `generate`, on the server with `receive`.

I obtain the same behaviour than with FFmpeg or srt-live-transmit.

I think there are two options: 
- a problem of configuration on the server side
- a bug in srt-core

I am trying with previous version of libsrt (just in case of regressions)

**Comment by mbakholdina** [comment]
Hi @olivierayache,
Thank you for collected statistics and Wireshark dump. 

Here are my observations. The problem place is the lines 55-56. From handshakes we can see that negotiated port is 31429 and before the line 56 all the traffic between receiver and sender is going through 31429 port. Line 55 - data packet 99321153 is the latest packet sent via this port.
<img width="1363" alt="Screenshot 2020-11-18 at 12 09 10" src="https://user-images.githubusercontent.com/41019697/99523372-4935df80-2997-11eb-95b8-a4b56118171d.png">

Line 56 - data packet 99321154 - the source port changes to 31263 (timestamp 1,39 s since the start of connection). All the traffic from sender to receiver is sent then via 31263 port.
<img width="1417" alt="Screenshot 2020-11-18 at 12 09 27" src="https://user-images.githubusercontent.com/41019697/99523722-bba6bf80-2997-11eb-9226-373afe78ea4f.png">

However, as we can see from acknowledgements (UMSG_ACK) which are sent from receiver to sender, they are sent via the original port 31429.
<img width="1368" alt="Screenshot 2020-11-18 at 12 09 44" src="https://user-images.githubusercontent.com/41019697/99523958-0fb1a400-2998-11eb-8060-4f4c7782c728.png">

Since line 56, receiver continues sending ACKs each 10 s (acknowledging packet 99321153 which is the latest received via port 31429 packet). However, it doesn't receive ACKACK back. After 5 s which is the default timeout (see [SRTO_PEERIDLETIMEO](https://github.com/mbakholdina/srt/blob/mbakholdina/outpace-mode-doc/docs/APISocketOptions.md#srto_peeridletimeo)) there is a shutdown and connection becomes broken.

This is an expected behaviour of SRT since we do not support seamless switching yet. There is a FR #1539 created for this.

Do you know the reason of port being changed at the sender side? I've mentioned that it actually changes at least twice. Is it possible to freeze the port in your case?

**Comment by olivierayache** [comment]
Thank for your answer there is no reason for port changing except in case of detection of broken connection because I have implemented auto reconnection on my client

**Comment by mbakholdina** [comment]
Hi @olivierayache 

I do not see any reconnections in Wireshark dump because there is only one handshakes exchange at the very beginning.

Could you please describe me your setup in details? And what you are doing with reconnections on ffmpeg side so that I have a bit more details.

Regarding reproduction with srt-xtransmit would be very helpful if you could collect dumps on both snd and rcv sides and share with me, I’ll take another look + statistics on both ends.

**Comment by olivierayache** [comment]
Hi @mbakholdina 

In fact I have implemented reconnection for caller in FFmpeg. This is intented to be use in Android caller in case of lose of network or in case of crash on server side.

For srt xtransmit I send you dumps as soon as possible.

**Comment by mbakholdina** [comment]
Hi @olivierayache,
Have you had a chance to collect Wireshark dumps and SRT statistics when you reproduce the problem with srt-xtransmit on both ends?

**Comment by olivierayache** [comment]
Hi @mbakholdina sorry for my late answer, by analysing different dumps I finally found two major problems:
- IP packet fragmentation on 4G network
- ACK is never received on Client side, ICMP destination unreachable on server side 

To resolve the first problem I set MSS on server with a small value (536) to be sure there is no more fragmentation.
For the second problem it should be a problem due to NAT and IP/Port translation and I don't understand how but if I use the FQDN to contact the server and not its IP the problem vanishes.

**Comment by ethouris** [comment]
Just to hint something, should that be anyhow helpful. In order that SRT work correctly, the UDP "channel" (defined as a pair of two ADDRESS:PORT specifications) must work unchanged and bidirectionally. This means that, for example, if there's NAT or packet fragmentation, it must work bidirectionally and transparently (that is, the network inside, whatever it does, it must behave like a "black box"): NAT should translate in both directions using the symmetric rule, fragmented packets should be reassembled to the same form.

For example, if ACK packets are not received, it means that the network configuration inside doesn't grant the bidirectional transmission on the UDP channel, or different things happen (that is, not symmetric) depending on the direction of sending.
