### ISSUE TITLE
[BUG] -DENABLE_MONOTONIC_CLOCK=ON / -DENABLE_STDCXX_SYNC=ON require different handling in application code but build configuration not available via the headers or API

### ISSUE THREAD

**Issue by sdroege** [Haivision/srt#1702]
Depending on whether the library is built with `-DENABLE_MONOTONIC_CLOCK=ON` / `-DENABLE_STDCXX_SYNC=ON` or the default, the time values provided are based on the real-time clock, the monotonic clock, or the C++11 APIs.

In application code these cases have to be handled differently as one can only make proper use of the clock times provided by libsrt if it is known from which clock they actually come.

Ideally there would be API that allows to query this at runtime from libsrt, or otherwise at least a `#define` in the headers.

**Comment by ethouris** [comment]
For that case you have two functions at your disposal:

* `srt_time_now()` - returns current time
* `srt_connection_time()` - returns the time when the socket was connected

The time is returned in the same domain and units as used by srctime for packets.

**Comment by sdroege** [comment]
That doesn't give you the information according to which clock this time is though. You could use `srt_time_now()` and other API to guess which clock it actually is, but that's rather ugly.

Being able to know what clock the time corresponds to is needed for proper integration into synchronization mechanisms provided by multimedia frameworks.

**Comment by maxsharabayko** [comment]
Hi @sdroege 
Could you please provide more details on your use case?
The motivation behind `srt_time_now()` and `srt_connection_time()` was that an application must not know which clock is actually used. Furthermore, it should rather treat SRT time as a separate source of timing.
`srt_time_now()` gives a timestamp in microseconds as of SRT internal clock. Then an application can use it to measure e.g. time intervals.

If you would like to convert a timestamp coming from some multimedia framework, then a time elapsed in the framework's clock can be used to get the corresponding time in the clock of SRT. Although it also provides some inaccuracy.
The question is, whether such inaccuracy is affordable in the use case?

**Comment by ethouris** [comment]
It's not that the application "must not" know it. There are simply no portable standards to return this information to the application. Even a monotonic clock from POSIX (`clock_gettime`) need not return you values from the same domain as the C++11 monotonic clock. There's simply no possible implementation to tell the application "which clock was used". Also no possibility to return anything like the "time base" because this could only be returned as a difference between two different clocks. There could be only given a guarantee that if SRT is compiled with C++11 clocks, the clock being used is the C++11 standard monotonic clock - that's about all.

The simplest method to have a guessed time conversion is to get the current time from the clock that is being used certainly by the multimedia framework and compare it against the result of `srt_time_now()`. Inaccuracy could be eliminated by multiple probing. That's the only method you can use if you don't know the clock domains.

The only other option is to know which exactly clock was used to compile SRT, and which exactly clock is being used by the multimedia library.

**Comment by maxsharabayko** [comment]
> There are simply no portable standards to return this information to the application.

As I understand, the question is not in returning the timestamp, but in providing an indication of which time source is used, so that an application can use the same time source to prepare a timestamp on its own following the same approach as SRT does internally.
The timestamp SRT returns is either one of [these sources](https://github.com/Haivision/srt/blob/master/srtcore/sync_posix.cpp#L45), or C++11 steady clock time elapsed since the epoch.

But exactly the lack of a standard and portable way to return the time and the time base are the reason why the application must not know the source of SRT time, but use the provided API functions instead.
It provides an opportunity to use any time base and any time-stamping conventions needed by SRT internally without the need to conduct those to the application.

**Comment by ethouris** [comment]
What I wrote was about a possibility to tell the application "which clock" has been used.

We might make something that could help an application know, with which clock to be used as the SRT clock the SRT library was compiled, should this be not known to the application from other sources. Something of a kind of enumeration for various options and then the exact value will be added to the generated `version.h` file. Like it is done for `BYTE_ORDER` that could be compared against `BIG_ENDIAN`, both being macros defined as numbers.

**Comment by maxsharabayko** [comment]
Hi @sdroege 
The question about your use case is still topical. Can you use `srt_time_now()` to convert between multimedia framework time and SRT time?

**Comment by sdroege** [comment]
Yes, that's what is done currently. It's a bit suboptimal in case both clocks actually match (which wouldn't be too uncommon in case of the monotonic clock) but could be worse.

**Comment by ethouris** [comment]
My idea is more-less like this:
1. Introduced 3 enum macros (in `srt.h`)
```
#define SRT_SYNC_USE_POSIX 1
#define SRT_SYNC_USE_MONOTONIC 2
#define SRT_SYNC_USE_STDCXX 3
```

2. Then, whichever of them is in use, will be generated in `version.h` file:
```
#define SRT_SYNC_USE_CLOCK 3 // If compiled with `--enable-stdc++-sync`
```

The application can then do
```
#if SRT_SYNC_USE_CLOCK == SRT_SYNC_USE_STDCXX
// you can use `std::chrono::steady_clock::now()` equally with `srt_clock_now()`.
```

etc.

I'm not exactly sure that this is enough helpful. What I understand from the usage is that you have another library that is also using a clock and you want to know if this clock can be used, relying on that it is in the same clock domain. In this case your only option is something like:

```
#if SRT_SYNC_USE_CLOCK != SRT_SYNC_USE_POSIX
#error SRT is using wrong clock - please setup SRT to use POSIX clock and recompile
#endif 
```
Not sure if this is what you need.

**Comment by sdroege** [comment]
If it was something that could be queried at runtime instead of compile-time then this would solve my problem, yes. Having this information available only at compile time would mean that updates to libsrt could silently change the clock that is used without the code that used the macros noticing that.

> In this case your only option is something like: [...]

The fallback case wouldn't be an error but what @maxsharabayko suggested, which causes some inaccuracy.

**Comment by ethouris** [comment]
But what are you going to do with this information at runtime, stating it will be provided?

How do you know which clock is being used by the other library and whether it's the same clock as the one used by SRT or not?

No problem, this `SRT_SYNC_USE_CLOCK` could be as well provided as a global constant so that you can also read it at runtime (maybe available under a differnt name). So you can use it as:

```
if (SRT_SYNC_USE_CLOCK_RT == SRT_SYNC_USE_CXX11)
...
```
Then what?

**Comment by sdroege** [comment]
If the SRT clock happens to be the same one as used for synchronization of other parts then times could be used without lossy translation between clocks.
