### ISSUE TITLE
rcvbuf for UDP and SRT [question]

### ISSUE THREAD

**Issue by Litrona** [Haivision/srt#1715]
Looking at the doc: https://github.com/Haivision/srt/blob/master/docs/srt-live-transmit.md
I've seen a rcvbuf = SRTO_RCVBUF, and sndbuf = SRTO_SNDBUF. 
Are these options related to SO_RCVBUF and SO_SNDBUF, the UDP socket buffers used in SRT ?
So can be used for SRT in the way is used in UDP: "udp://:4200?rcvbuf=67108864", to handle high and bursty data rates ?
I mean "srt://:4200?rcvbuf=67108864" (at the receiver side in this case).
Thanks.

**Comment by maxsharabayko** [comment]
Receive and send buffer sizes of the underlying UDP transport can be set with [SRTO_UDP_RCVBUF](https://github.com/Haivision/srt/blob/master/docs/APISocketOptions.md#SRTO_UDP_RCVBUF) and [SRTO_UDP_SNDBUF](https://github.com/Haivision/srt/blob/master/docs/APISocketOptions.md#SRTO_UDP_SNDBUF).
SRTO_SNDBUF and SRTO_RCVBUF set only corresponding SRT buffer sizes.

Handling high and bursty data rates is one purpose of SRT buffers. In general, SRT receiver buffer is needed to store incoming packets until the application can read them. SRT sender buffer is needed to store outgoing packets until the receiver acknowledges their reception so that they no longer need to be retransmitted.
In live streaming, SRT receiver also needs to buffer incoming packets to maintain a fixed end-to-end latency.
See [this configuration guide](https://github.com/Haivision/srt/issues/703#issuecomment-495570496).

**Comment by Litrona** [comment]
OK, thanks for the info. Mabbe the config guide should be in the docs folder.

**Comment by maxsharabayko** [comment]
Occasionally stumbled on this thread.
The configuration guideline is now in the docs folder.
https://github.com/Haivision/srt/blob/master/docs/API/configuration-guidelines.md
