### ISSUE TITLE
Minimizing latency in ffmpeg

### ISSUE THREAD

**Issue by llamafilm** [Haivision/srt#1729]
Howdy!  I’m trying to receive an SRT stream with `ffplay` with minimal latency.  I'm testing on a 1Gb LAN with 0.4ms ping times so I have set buffer and latency options to (crazy) minimum values.  I want to find out how fast it can go here first before testing over the internet.

With this command-line, it takes about 3 seconds to display the first frame, and then the latency is about 1.5 seconds after that.
`% ffplay -protocol_whitelist srt -probesize 32 -analyzeduration 0 -i "srt://192.168.4.3:8888?transtype=live&latency=0&recv_buffer_size=0" -an -loglevel debug`

Is there anything else that can be adjusted to reduce latency?  I built the latest SRT (df25ca8) and ffmpeg (f4bdedd) but didn't see any improvement over the release version.  Stream info is like this, but it's actually 24fps, I don't know why ffplay detects 90k.
```
Input #0, mpegts, from 'srt://192.168.4.3:8888?transtype=live&latency=0&recv_buffer_size=0':
  Duration: N/A, start: 2370.893667, bitrate: 319 kb/s
  Program 1 
    Stream #0:0[0x3e9], 0, 1/90000: Video: hevc, 1 reference frame ([36][0][0][0] / 0x0024), none, 90k tbr, 90k tbn, 90k tbc
    Stream #0:1[0x3ea], 1, 1/90000: Audio: aac (HE-AAC) ([15][0][0][0] / 0x000F), 48000 Hz, 7.1, fltp, 319 kb/s
```

Because of such small `analyzeduration` I get this error about unspecified size, but the image still looks okay.
`[mpegts @ 0x7fd170853000] Could not find codec parameters for stream 0 (Video: hevc ([36][0][0][0] / 0x0024), none): unspecified size`

When I first run ffplay, it takes about 2.5 seconds to display the first frame.  With loglevel trace, I see the longest delay is about 1.5 seconds at this line.  I tried searching for this string in the source to investigate but couldn't find it.
`[NULL @ 0x7fdafb840200] Opening 'srt://192.168.4.3:8888?transtype=live&latency=0&recv_buffer_size=0' for reading`

**Comment by J-Rogmann** [comment]
Hi llamafilm
In a first thought I don't think SRT is adding much latency to your chain here. I'm not to familiar with ffplay, especially the `-probesize 32 -analyzeduration 0` parameters and if they add latency themselves. Are those just measuring the latency from the moment a packet is received up to when data is sent to the display?

From your ffplay command I can see, that you set `latency=0` which would disable the ability for the SRT protocol to re-transmit lost packets. Unless you want to use encryption, you could also use MPEG-TS instead, since with `latency=0`there is almost same transmission behavior. (I know you minimized this value for testing purpose)

Did you compare your ffplay command also with a MPEG-TS stream, just to see where the latency comes from? I suspect it comes from the ffplay decoding process itself and not necessarily from the SRT protocol. I'm pretty sure, that you will find similar values. 

In case of nearly no difference between MPEG-TS and SRT, you should dig into other ffplay options relating the actual decoding process.

best regards,
Justus

**Comment by llamafilm** [comment]
I think you're right, most of it comes from ffplay.  I tested a raw UDP stream and it has about 0.9 seconds latency, vs 1.5 seconds with SRT.  Anyway 1.5 seconds is quite good, I was curious.
