### ISSUE TITLE
[BUG] srt-file-transmit mode, only part of a file is received 

### ISSUE THREAD

**Issue by douguixiao** [Haivision/srt#1764]
the srt order is:
srt-file-transmit.exe -v file:///./1.mpd srt://5555 
srt-file-transmit.exe -v srt://127.0.0.1:5555 file:///./1.mpd

send log:
upload: 1456 --> 1456
upload: 1456 --> 1456
upload: 220 --> 220
File sent
Buffers flushed

receive log:
download: -->1456
download: -->1456
Source disconnected
Dodownload exit

**Comment by ethouris** [comment]
May I ask for extra help? I found some random possibility for this to reproduce (sometimes it loses the only last packet, sometimes to last ones, but most often it works fine), but the problem slips through my hands. Could you try to achieve the same thing using `srt-test-file` application (you need to `--enable-testing`). The latter uses blocking mode and I suspect that the reading part is setting the epoll ERR flag prematurely before it could read all available packets, that's why this problem can be seen on srt-file-transmit.

**Comment by douguixiao** [comment]
this problem occurs if the file to be sent is large.the cause of this problem is that the file upload speed is faster but the download speed is slow.if I change "goto exit" in "case SRTS_CLOSED" in DoDownload function,this problem is solved.

…
case SRTS_NONEXIST:
case SRTS_CLOSED:
{
         //goto exit;
         connected = true;
}

**Comment by ethouris** [comment]
Well, I've just suspected the same thing :)

It's not exactly the solution, however this was likely the problem - the socket may become SRTS_BROKEN, but still have data to read, the application qualified it as non-readable too prematurely. For NONEXIST and CLOSED states it took the right action, although this could be possible only in case when the transmission could not even start. Thanks a lot, I'll make the final test and the fix is going to be ready.

**Comment by ethouris** [comment]
Got it. Confirmed fix. `Connection closed, reading buffer remains` - is printed when the BROKEN state was achieved, in which case it is still allowed to read.

```
Source connected (caller), id []
Writing output to [/home/Admin/Projects/opensrt-ethouris.git/build-cygwin/./TESTFILE.out]
Download: --> 1456
Event with status 5

Download: --> 1456
Event with status 6

Connection closed, reading buffer remains
Download: --> 200
Event with status 6

Connection closed, reading buffer remains
Download COMPLETE.
```
