### ISSUE TITLE
[BUG] CUDT::sendmsg2(..)` does not report an error on wrong MSG_CTRL.pktseq

### ISSUE THREAD

**Issue by maxsharabayko** [Haivision/srt#1810]
` CUDT::sendmsg2(..)` does not report an error, and even behaves as if a sending operation was successful.

If some invalid `MSG_CTRL.pktseq` value is submitted, then `srt_sendmsg2(..)` returns the payload size like if it was successfully added to the sending buffer, and does not write an error message to `stderr`.

```c++
// Check if seqno has been set, in case when this is a group sender.
// If the sequence is from the past towards the "next sequence",
// simply return the size, pretending that it has been sent.
if (w_mctrl.pktseq != SRT_SEQNO_NONE && m_iSndNextSeqNo != SRT_SEQNO_NONE)
{
    if (CSeqNo::seqcmp(w_mctrl.pktseq, seqno) < 0)
    {
        HLOGC(aslog.Debug, log << CONID() << "sock:SENDING (NOT): group-req %" << w_mctrl.pktseq
                << " OLDER THAN next expected %" << seqno << " - FAKE-SENDING.");
        return size;
    }
}
```

It was likely done to suppress error messages from a socket that is a member of a group when it was initialized with some ahead initial sequence number.

However, this hides an error from a regular use case (single SRT socket), when an invalid `MSG_CTR` structure is passed to the function.

Also, docs say `pktseq` is not used for sending, expecting the value should be ignored.

 - SRT Version / commit ID: v1.4.2 and the latest master.

**Comment by maxsharabayko** [comment]
Potential workaround: do this check only if a socket is a member of a group, and is not a group socket itself.

**Comment by ethouris** [comment]
As far as I remember in the documentation, values that are "not used" by particular part of the code, should remain initialized to the default values. It is intentionally mentioned here that this value is of no use so that users supply always the defaults there. It is of no use for regular uses, and the fact that it is used now is that the simplified implementation of the group sender has been created, which uses the original socket's sending function.

If there is a method in the future to not use the original socket sender function, setting pktseq would be of no use at all and the verification could be provided.

**Comment by ethouris** [comment]
Ok, I added a fix that checks these fields in the API access function. The group code is using directly the `CUDT::sendmsg2` internal function, so it bypasses this check. This way one can be sure that if the sequence number isn't -1, then it was called from the internal group code. For that case, this behavior is correct.
