### ISSUE TITLE
SocketOption::POST option may not applied for group member

### ISSUE THREAD

**Issue by yunhuali** [Haivision/srt#1821]
SocketOption::POST option may not applied to all group member. such as drifttracer=0

**To Reproduce**
Run SRT group server with multiple member, POST option sometime only applied to some member.

after srt_connect_group returned, waited for 1s, then call srt_setsockopt() to set POST option.  such as drifttracer=0
but some member connection may not established yet. 
void CUDTGroup::setOpt() {
   for (gli_t gi = m_Group.begin(); gi != m_Group.end(); ++gi) {
        gi->ps->core().setOpt(optName, optval, optlen);
   }
}
then the chance will get some member with driftracer enabled, some with drifttracer disabled.

**Comment by ethouris** [comment]
There was a merge error in one of the latest version and it was fixed yesterday. Please retest if you didn't take the latest, or specify the version which you used for the test. Actually there shouldn't be any difference when set for the group because it uses the same `CUDT::setOpt` function for it.

**Comment by maxsharabayko** [comment]
I don't see `SRTO_DRIFTTRACER` marked for a POST action in the code.
[See `SrtOptionAction()`](https://github.com/Haivision/srt/blob/master/srtcore/core.cpp#L253)
While it has a POST action assigned in [the docs](https://github.com/Haivision/srt/blob/master/docs/APISocketOptions.md).

@ethouris Given the latest errors introduced in #1776, please go through all socket options and check if they have appropriate flags assigned.

**Comment by yunhuali** [comment]
https://github.com/Haivision/srt/blob/master/apps/socketoptions.hpp#L234
 { "drifttracer", 0, SRTO_DRIFTTRACER, SocketOption::POST, SocketOption::BOOL, nullptr},
it marked as POST action in this file.

**Comment by maxsharabayko** [comment]
@yunhuali I meant that the library should also have this POST flag assigned to this option. [See `SrtOptionAction()`](https://github.com/Haivision/srt/blob/master/srtcore/core.cpp#L253). It looks like `SRTO_DRIFFTRACER` is missing.

socketoptions.hpp defines application-level logic. So that if `drifttracer=off` is passed in URI, it is applied on a post-connection step. Still, if the library does not handle it correctly, there will be an error.

**Comment by ethouris** [comment]
Right. The latest revision on the option has changed some restrictions, in both directions actually. The option facility in the apps deserves an update.
