### ISSUE TITLE
[TS Duck] Operation not supported: Bad parameters

### ISSUE THREAD

**Issue by Plombirius** [Haivision/srt#1875]
Hi!

When we use tsduck and libsrt 1.4.3 with lines from [Cockbook ](https://srtlab.github.io/srt-cookbook/apps/tsduck/) `tsp -I .... -O srt "192.168.2.3:4900" --transtype live --messageapi` and `tsp -I srt 192.168.2.3:4900 --transtype live --messageapi -O ...` we get error `Operation not supported: Bad parameters` on sender side. We have asked about it @;elegard in [tsduck/tsduck](https://github.com/tsduck/tsduck/issues/738). He has tested it too and discovered that same issue has happened with libsrt 1.4.2, but hasn't happened with 1.4.1. On 1.4.1 it works fine with present lines.
What lines should we use with libsrt above 1.4.1?

**Comment by lelegard** [comment]
This issue has been handled in https://github.com/tsduck/tsduck/issues/738.
The author of the SRT plugin in TSDuck fixed the issue.
We can close this one.

**Comment by maxsharabayko** [comment]
Thanks @lelegard 

Copying the reason here:
> A missing initialization on int *addrlen of srt_accept() cause a bad paremeters error (SRT_EINVPARAM).

[The check](https://github.com/Haivision/srt/blob/v1.4.2/srtcore/api.cpp#L1159) for the value of the `addrlen ` argument was added in PR #1017, and is present in SRT since v1.4.2. It validates that the size of the `sockaddr` structure is enough to fill it with the address of the accepted socket.

**Comment by maxsharabayko** [comment]
Related issue #1880: improve error logs for `srt_accept`
