### ISSUE TITLE
Dev branch: SRT-LIVE-TRANSMIT dumps exception errors when abruptly interrupted with crtl-c or with other means

### ISSUE THREAD

**Issue by alexanderdevm** [Haivision/srt#188]
When srt-live-transmit is interrupted with crtl-c or any other mean, it dumps exception errors in the console.

Steps:
1. With live stream from port 5001 execute: `./srt-live-transmit srt://:5001 srt://:5002`
2. Wait 10-15 seconds
3. CRTL-C or any other mean to interrupt

Results:
```
-------- REQUESTED INTERRUPT!
17:06:36.152666/SRT:RcvQ:worker!!FATAL!!: SRT.c: recvmsg: UNEXPECTED EXCEPTION: St13runtime_error: Requested exception interrupt
ERROR #-1000: Unknown error.
STD EXCEPTION: error: recvmsg: Unknown error.
Waiting 5s for possible cleanup...
```

or

```
-------- REQUESTED INTERRUPT!
17:03:57.296504/SRT:RcvQ:worker!!FATAL!!: SRT.c: accept: UNEXPECTED EXCEPTION: St13runtime_error: Requested exception interrupt

ERROR #-1000: Unknown error.
```

Abruptly terminating srt-live-transmit should not dump exceptions errors into console.

**Comment by ethouris** [comment]
Solved in #187

**Comment by ethouris** [comment]
It's a feature. Generally this application wasn't used for anything else than testing. Interrupting is here implemented by throwing an exception from within the signal handler, then the whole thing is handled by the internal exception handling in SRT. So it's kinda emulated. There wasn't predicted so far any way to interrupt SRT, and all other media that `stransmit` is using are system-handled, so they get closed painlessly. Applications never use this way - instead they simply close the socket.

Interrupting by request on sinal using some "civilised way" (that is, using at least some exception that is properly handled inside SRT and at worst results in something kind-of `EINTR` error) is currently desired, but wasn't planned yet. A potential problem here is that SRT uses multiple threads, and the rules concerning POSIX signals are such that the signal handler runs in one of randomly selected threads. So, to plan this, every thread must be capable of carrying over this interrupting action and spread to the rest of the application, and rather with least trouble to it (that is, it shouldn't do with the application anything more than just reporting error by reading/writing functions, possibly kill threads only those that are part of SRT, and it's also to be decided as to whether the socket should be usable after this event, or not).

**Comment by rndi** [comment]
The current implementation is maddening and is, in fact, preventing testing. Throwing exceptions, reporting "unknown" errors, dumping core, and plainly refusing to cooperate is no way for properly designed application to behave when it asked to terminate nicely. Please indicate if these shortcomings can be addressed or if an alternative application should be developed that that is suitable for automated testing.

**Comment by ethouris** [comment]
In order to "nicely ask" to do anything, including exitting, the application would have to be armed in some command interpreter, and `stransmit` doesn't have anything like that. The only external communication is POSIX signals, but it's not a coincidence that a function to send a signal is called `kill()` and by no means can mean "nicely asking". Every application normally exits with an error code when killed by a signal.

If we want to have some application that will "nicely ask" the transmission to stop, we need either some wrapper script, which will kill the application by itself and hide this fact in its guts, or another application for testing, which will support this transmission, and will interpret a command to stop, which will do it nice way by closing the descriptors. Possibly the latter may be also added as an alternative running mode for `stransmit` (that is, the whole action will run in a second thread, whereas the main thread will only wait for a command to enter).

**Comment by rndi** [comment]
There is no way we will be developing a "wrapper" application the sole intention of which is to hide shortcomings of the stransmit application. That leaves either fixing currently buggy stransmit or developing a new application that will completely replace stransmit in our SRT test suits.

**Comment by ethouris** [comment]
Should be taken care of in #190
