### ISSUE TITLE
Dev branch: SRT-LIVE-TRANSMIT internal buffer gets overrun when target no listening or receiving the stream 

### ISSUE THREAD

**Issue by alexanderdevm** [Haivision/srt#189]
When SRT-LIVE-TRANSMIT is trying to send SRT stream to a target that does not listen, then its buffers will overrun and it will start dumping errors into console.

Steps:
1. Receive an srt source at port 5001 and send it port 5002 which no one is listening 
`srt-live-transmit srt://:5001 srt://:5002`

Results:
```
...
17:03:50.431828/SRT:TsbPd*E: SRT.c: %763766263:No room to store incoming packet: offset=180 avail=0
17:03:50.431913/SRT:TsbPd*E: SRT.c: %763766263:No room to store incoming packet: offset=181 avail=0
17:03:50.445088/SRT:TsbPd*E: SRT.c: %763766263:No room to store incoming packet: offset=277 avail=0
17:03:50.445164/SRT:TsbPd*E: SRT.c: %763766263:No room to store incoming packet: offset=279 avail=0
17:03:50.445193/SRT:TsbPd*E: SRT.c: %763766263:No room to store incoming packet: offset=280 avail=0
17:03:50.445217/SRT:TsbPd*E: SRT.c: %763766263:No room to store incoming packet: offset=281 avail=0
17:03:50.445241/SRT:TsbPd*E: SRT.c: %763766263:No room to store incoming packet: offset=282 avail=0
17:03:50.459240/SRT:TsbPd*E: SRT.c: %763766263:No room to store incoming packet: offset=303 avail=0
17:03:50.459316/SRT:TsbPd*E: SRT.c: %763766263:No room to store incoming packet: offset=304 avail=0
17:03:50.480511/SRT:TsbPd*E: SRT.c: %763766263:No room to store incoming packet: offset=321 avail=0
17:03:50.480609/SRT:TsbPd*E: SRT.c: %763766263:No room to store incoming packet: offset=322 avail=0
17:03:50.531313/SRT:TsbPd*E: SRT.c: %763766263:No room to store incoming packet: offset=350 avail=0
17:03:50.531431/SRT:TsbPd*E: SRT.c: %763766263:No room to store incoming packet: offset=351 avail=0
17:03:50.558741/SRT:TsbPd*E: SRT.c: %763766263:No room to store incoming packet: offset=356 avail=0
17:03:50.558821/SRT:TsbPd*E: SRT.c: %763766263:No room to store incoming packet: offset=357 avail=0
17:03:50.579580/SRT:TsbPd*E: SRT.c: %763766263:No room to store incoming packet: offset=385 avail=0
17:03:50.579629/SRT:TsbPd*E: SRT.c: %763766263:No room to store incoming packet: offset=386 avail=0
etc ...
```

srt-live-transmit should empty buffers when nothing is connected on the output

**Comment by ethouris** [comment]
This has been pointed out as still a problem in the older versions. The problem is that this scenario hasn't been really developed yet.

The problem is that when the receiving application stops reading, it's not clear as to what should be done. The buffer in SRT is predicted to work only as a temporary "anteroom" for the packets, where they should stay until the time to play comes - but when time to play comes, the application should play it, otherwise the result is completely ridiculous. The Live mode in SRT was predicted to provide smoothly-timed packet delivery, but it won't work, if the application doesn't do its part, that is read immediately every packet that is ready to play.

The original implementation in UDT - as it was designed for file and message transfer - was such that the buffer space is reported with ACK messages, and when the ACK message reported that it has dropped to 0, the sender stops sending, until this situation is resolved. By various pragmatic reasons this transmission stopping has been lifted in SRT live mode, but this still seems to be a temporary solution. We need to decide, what exactly action should be undertaken by SRT in case when the application doesn't read the packets.

What I think about it is: when the application is given up a packet to play, and if there has been a next packet already qualified as ready to play, but the previous one still wasn't read by the application, the radical solution would be to drop the first packet and "propose" for delivery only the next packet, the one that has passed the play-readiness recently. A less radical solution might be to apply some delay in packet number, which when exceeded will cause dropping packets from the receiving buffer.

**Comment by rndi** [comment]
As @alexanderdevm has suggested, srt-live-transmit should empty receive buffers when nothing is connected on the output, at least when it is in polling mode.
