### ISSUE TITLE
questions about srt_connect_callback

### ISSUE THREAD

**Issue by cg82616424** [Haivision/srt#1903]
I install a connection callback to get some connect error message;
I found something wired:
on linux, after I call srt_close on a normal connection, srt_connect_callback never happened.
but on macos, after I call srt on a norman connection, srt_connect_callback sometimes triggered
is this a designed feature?

**Comment by maxsharabayko** [comment]
Hi @cg82616424 
The connection callback is called in two cases (as of the latest master):
1. SRT socket has failed to connect (caller mode)
2. SRT socket is broken due to peer idle timeout (see [SRTO_PEERIDLETIMEO](https://github.com/Haivision/srt/blob/master/docs/API/API-socket-options.md#SRTO_PEERIDLETIMEO)).
In both cases, error code would be `SRT_ECONNLOST`.

The main motivation for this callback was to detect a connection failure of a socket group member (SRT experimental bonding).
So in fact, only no.1 is the target use case. And it is still experimental.

> on linux, after I call srt_close on a normal connection, srt_connect_callback never happened.
Looks fine.

> on macos, after I call srt on a norman connection, srt_connect_callback sometimes triggered
This does not look correct.

**Comment by cg82616424** [comment]
Thanks for your reply;
so, on macos, it looks like a bug?

**Comment by maxsharabayko** [comment]
So far looks like a bug.
Could you provide steps to reproduce this behavior?

**Comment by ethouris** [comment]
It would be most helpful if you can grab the debug logs from the case on MacOS where the connect callback is called for a successful connection.

**Comment by maxsharabayko** [comment]
@cg82616424 
BTW just to double-check, both on your Linux and MacOS systems you have the same SRT version, right?
As I remember, SRT  v1.4.2 also called a callback on a successful connection.

**Comment by cg82616424** [comment]
@maxsharabayko yes, my current srt version is 1.4.3rc.

**Comment by maxsharabayko** [comment]
Hi @cg82616424 
Could you share if there is any update on the issue? Any guidance on reproduction steps would help a lot.

**Comment by maxsharabayko** [comment]
Closing as inactive. No reproduction steps were provided.
Please don't hesitate to reopen if still topical.
