### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by metairie** [Haivision/srt#191]
Hello
I get source normally
./configure
make 

I get an error after make instal
CMake Error at cmake_install.cmake:97 (FILE):
  file INSTALL cannot find
  "/tmp/srt/$<TARGET_FILE_DIR:srt-live-transmit>/stransmit".

**Comment by ethouris** [comment]
I knew cmake is stupid, but that it's unable to properly generate its own files, that's kinda higher level (see the line 97 in `cmake_install.cmake` after generation). This is a problem in cmake 2.8 - in cmake 3.0 it's fixed. Funny thing is that Makefile is generated correctly, so copying this file locally after linking `srt-live-transmit` works correctly; the problem is only with installation.

I made a fix in #193 (still checks-pending as I write). This makes the backward-compatible `stransmit` name a symbolic links on platforms where symlinks are supported. Otherwise cmake 3.0 is minimum required.

**Comment by metairie** [comment]
get cmake3. Works

**Comment by ethouris** [comment]
The fix is there, please recheck and close, if fixed.

**Comment by alexanderdevm** [comment]
The issue is still persistent on centos7 with cmake 2.8

```
Linking CXX shared library libsrt.so
[100%] Built target srt_shared
[ 30%] Built target haicrypt_virtual
[ 74%] Built target srt_virtual
[ 76%] Built target srt_static
[ 89%] Built target srtsupport_virtual
[ 92%] Built target srt-file-transmit
[ 94%] Built target srt-live-transmit
[ 97%] Built target srt-multiplex
[100%] Built target srt_shared
Install the project...
-- Install configuration: "Release"
-- Installing: /tmp/build/bins/ffmpeg_build/lib64/libsrt.so.1.3.2
-- Installing: /tmp/build/bins/ffmpeg_build/lib64/libsrt.so.1
-- Installing: /tmp/build/bins/ffmpeg_build/lib64/libsrt.so
-- Installing: /tmp/build/bins/ffmpeg_build/lib64/libsrt.a
-- Installing: /tmp/build/bins/ffmpeg_build/include/srt/version.h
-- Installing: /tmp/build/bins/ffmpeg_build/include/srt/srt.h
-- Installing: /tmp/build/bins/ffmpeg_build/include/srt/logging_api.h
-- Installing: /tmp/build/bins/ffmpeg_build/include/srt/platform_sys.h
-- Installing: /tmp/build/bins/ffmpeg_build/include/srt/udt.h
-- Installing: /tmp/build/bins/ffmpeg_build/include/srt/srt4udt.h
-- Installing: /tmp/build/bins/ffmpeg_build/lib64/pkgconfig/haisrt.pc
-- Installing: /tmp/build/bins/ffmpeg_build/lib64/pkgconfig/srt.pc
-- Installing: /tmp/build/bins/ffmpeg_build/bin/srt-live-transmit
-- Up-to-date: /tmp/build/bins/ffmpeg_build/bin/srt-live-transmit
CMake Error at cmake_install.cmake:123 (FILE):
  file INSTALL cannot find
  "/tmp/build/bins/ffmpeg_sources/srt/$<TARGET_FILE_DIR:srt-live-transmit>/stransmit".


make: *** [install] Error 1
[user@env dev]$ ll bins/ffmpeg_sources/
```

**Comment by rndi** [comment]
Could we please remove `stransmit` symlink from the build together with all that code needed to support that feature? `stransmit` has been renamed to `srt-live-transmit` for some time now, I think it is time for old name to go...
