### ISSUE TITLE
How to set default option for 'lossMaxTTL' to something higher than 0 without using the url? 

### ISSUE THREAD

**Issue by mrsydster** [Haivision/srt#1930]
I need to be able to increase the default option for lossmaxttl to about 40. Not the default 0. 

(I cannot set it using the url parameter)

**Comment by ethouris** [comment]
I don't understand the problem. In SRT library you should use `srt_setsockflag` (*opt, with old API) with `SRTO_LOSSMAXTTL`. Note that this option is important in a network that experiences UDP packet reordering.

**Comment by mrsydster** [comment]
Sorry for my bad explanation; 

In order to do network bonding, I need to set the lossMaxTTL. Normally the easiest would be in the URL. But now I need to set the option without adding it to the URL.

I assume I need to try to set the option using the` srt_setsockflag` to accomplish this. 
I basically want the socket to always use a lossMaxTTL of 40 without specifing it in the url

**Comment by ethouris** [comment]
I don't think this option has anything to do with network bonding at all - unless you are trying to do it on UDP level only and outside of the machines using SRT. This option allows the "loss TTL" to grow up to given value when packet reordering has been detected, and the value of "loss TTL" (seen internally) is the number of packets that must be received since the moment of loss detection (which is seen as a jumped-over sequence) before the loss report is sent.

The value of 40 sounds extreme; I don't think packet reordering can ever reach this value, and note also that this option doesn't control the loss TTL value, but the maximum value up to which loss TTL may grow, and loss TTL grows upon detection of a reordered packet, which is the packet that has a "belated" sequence number (less than the latest received one), but has no R (retransmission) flag set. For example:

```
100
101
103 <--- loss detected: lost packet = 102; loss REPORTED!
104
105
106
102 R <-- belated sequence, but R flag set - normal retransmission
107
109 <-- loss detected: lost packet = 108
110
111
108  <-- belated sequence, but R flag clear - this is a reordered packet: setting loss TTL = 111 - 108 = 3
112
113
115 <-- loss detected: lost packet = 114, but NOT SENDING LOSSREPORT yet. - seq = loss+0
116 <-- loss+1
117 <-- loss+2
118 <-- loss+3
119 <-- NOW sending LOSSREPORT for 114
120
121
122
114 R <--- now retransmitted lost 114
123
```

In the above example you have once seen a reordered packet, which caused loss TTL to grow, but the LOSSREPORT for that packet (mistakenly) has been already once sent. This mistake will not be repeated next time; if the lost 114 packet had arrived before 119 as reordered (that is with R flag clear), this would have cleared the hole - and hence the mistaken lossreport would be prevented.

Note however that it doesn't come for free. By having loss report belated your retransmission will be belated, too. You might want then increase the latency accordingly.

**Comment by mrsydster** [comment]
Thanks for the explenation. I am combining a custom lib ( https://github.com/BELABOX/srtla ) with SRT-Live-Server fork (https://github.com/Edward-Wu/srt-live-server).

They are using a value of 40 and it seems to work good for my use case. However, instead of the command.

```
path/to/srtla/srtla_rec 5000 127.0.0.1 5002 &
path/to/srt/srt-live-transmit -st:yes "srt://127.0.0.1:5002?mode=listener&lossmaxttl=40&latency=2000" "srt://0.0.0.0:5001?mode=listener"
```

Now instead of using `srt-live-transmit` I inject the stream directly into the Live Server. 
Just trying to figure out where I need to set the lossmaxttl option. Either on SRT itself, or on the SRT server...

**Comment by mrsydster** [comment]
In fact, using the `srt_setsockflag` on the receiver fixed my problem! thanks for the help!
