### ISSUE TITLE
Dev branch: "No room to store incoming packet" error appears from time to time when receiving an srt stream and sending it to console

### ISSUE THREAD

**Issue by alexanderdevm** [Haivision/srt#196]
When user receives an srt stream and then sends it to a console using the following command:
`./srt-live-transmit srt://:5001?mode=listener file://con | <...do something> pipe:0`
"No room to store incoming packet: offset=1517 avail=0" error would appear from time to time.

Error:
```
16:49:06.838803/SRT:TsbPd*E: SRT.c: %389795189:No room to store incoming packet: offset=1517 avail=0
16:49:06.854592/SRT:TsbPd*E: SRT.c: %389795189:No room to store incoming packet: offset=1550 avail=0
16:49:06.854670/SRT:TsbPd*E: SRT.c: %389795189:No room to store incoming packet: offset=1551 avail=0
```

**Comment by ethouris** [comment]
This message appears when the application that has established the connection does not call `srt_recvmsg` function to retrieve the data, so the data stay in the buffer, which eventually gets overflown.

In this configuration the only possibility is that the internal transmission loop has stalled due to stalled operation in the output medium, that is, the inter-process pipe is stuck due to not being emptied.

**Comment by jeandube** [comment]
I encountered this problem too and solved it not by changing the application but by compiling SRT without --enable-logging. I had this error while receiving a 7Mbps stream  and another one (tsbpd: DROPSEQ:...) at 4Mbps, no error at 1 Mbps. Without --enable-logging no errors logged (of course) with lower CPU usage and smoother video (with clean stats (no skip, no loss).
