### ISSUE TITLE
How to reduce srt streaming latency to microsecond ?

### ISSUE THREAD

**Issue by a8310262002** [Haivision/srt#1962]
Hi, I am using ipcam to do the srt streaming by ffmpeg.

OS:ubuntu:16.04
Ffmpeg version: 4.3.1
srt version: 1.4.3

[Ffmpeg-srt cookbook](https://srtlab.github.io/srt-cookbook/apps/ffmpeg/)

I have two command-line

1.
./srt-live-transmit udp://:1234 srt://:6000 -v

ffmpeg -i (ipcam rtsp) -fflags nobuffer -preset veryfast -tune zerolatency -f mpegts "udp://127.0.0.1:1234?pkt_size=1316"

./srt-live-transmit srt://my_pc_ip:6000 file://con | ffplay -probesize 32 -analyzeduration 0 -fflags -nobuffer - -flags low_delay

2.
ffmpeg -i (ipcam rtsp) -fflags nobuffer -preset veryfast -tune zerolatency -f mpegts "srt://my_pc_ip:6000?pkt_size=1316"

 ./srt-live-transmit srt://:6000 file://con | ffplay -probesize 32 -analyzeduration 0 -fflags -nobuffer - -flags low_delay

latency is about : 1-2 second

the following is  my test picture. In the morning and at night
![image](https://user-images.githubusercontent.com/32253339/115500828-ac100780-a2a4-11eb-8530-c712b7abe3df.png)

![image](https://user-images.githubusercontent.com/32253339/115500871-bd591400-a2a4-11eb-8c76-0d1a273b432f.png)

morning test is about 1-2 second
night test is about 3 second
Same command-line

How to reduce srt streaming latency to microsecond ?
Thanks

**Comment by J-Rogmann** [comment]
Hi @a8310262002 

the lowest latency you can set for buffer size is 20ms. It's recommended, that the latency buffers size should be 3-4x the RTT. So if all of you device are on the same local network or have very low latency ping times between each other, you can set 20ms as lowest value:

1)
`srt-live-transmit udp://:1234 srt://:6000?latency=20 -v`

`ffmpeg -i (ipcam rtsp) -fflags nobuffer -preset veryfast -tune zerolatency -f mpegts "udp://127.0.0.1:1234?pkt_size=1316"`

`./srt-live-transmit srt://my_pc_ip:6000?latency=20 file://con | ffplay -probesize 32 -analyzeduration 0 -fflags -nobuffer - -flags low_delay`

2)
`ffmpeg -i (ipcam rtsp) -fflags nobuffer -preset veryfast -tune zerolatency -f mpegts "srt://my_pc_ip:6000?pkt_size=1316&latency=20"`

`./srt-live-transmit srt://:6000?latency=20 file://con | ffplay -probesize 32 -analyzeduration 0 -fflags -nobuffer - -flags low_delay`

The default latency is 120ms. If you don't specify otherwise, this will be used. So in your setup, you should gain around 100ms. 
I'm pretty sure, that your observed 1-2 seconds of latency mainly driven by other factors like the RTSP camera and it's encoder and probably ffmpeg.

It's also strange, that your setup increased from 2 to 3 seconds of delay over night. Do you have SRT statistics on that long run? Typically, if packets arrive to late, they are dropped, so the stream can not pile up latency and "fall behind in time". They receiving side should have a constant delay.

**Comment by a8310262002** [comment]
Hi @J-Rogmann 

Thanks for your reply.
I have some questions.
My pc and ipcam are on the same local network.

1.
How to know the RTT from my command-line that I can set for buffer size?

2.How to check rtsp camera latency (my ipcam is h264)? About ffmpeg or ffplay latency I think is buffer. But in my command I already used -fflags -nobuffer. Do you have any idea to check buffer?

I am not sure that I have SRT statistics about packets arrive or not.
But I have log from command-line

My ffmpeg log
![image](https://user-images.githubusercontent.com/32253339/115593473-1eb1cf00-a307-11eb-960d-eae2c4fd391b.png)


My ffplay log
![image](https://user-images.githubusercontent.com/32253339/115593501-26717380-a307-11eb-80d3-dc175aaea308.png)

Thanks

**Comment by maxsharabayko** [comment]
@a8310262002 
> How to know the RTT from my command-line that I can set for buffer size?

If `ping` does not work, then you can get the RTT estimation of SRT.
For instance, `srt-live-transmit` provides regular SRT stats. See `-statsout`, `-pf` and `-s` [command-line options](https://github.com/Haivision/srt/blob/master/docs/apps/srt-live-transmit.md#command-line-options).
One more way is to do a network capture and check the RTT value in the [ACK packet](https://datatracker.ietf.org/doc/html/draft-sharabayko-srt-00#section-3.2.4).

> How to check rtsp camera latency (my ipcam is h264)?

Record some clock or timer and compare with what you see on the receiver display.
But in general, FFmpeg (ffplay) provides some notable delay, maybe even a second.
