### ISSUE TITLE
a problem about high cpu cost

### ISSUE THREAD

**Issue by cg82616424** [Haivision/srt#1963]
Hi : 
   I wrote a benchmark test case,but srt cpu cost is very high;
   my case details:
   1. create about 64 srt connections
   2. client send 1 pkt(20 byte)
   3. server response about 16 pkt(1024 byte)
   4. all connections are send and recv pkt concurrently
   5. case runs use async mode, msg api and file mode.
   6. I caputure a client`s  flame graph, the highest cpu cost inside srt, is some locks and __schedule
![image](https://user-images.githubusercontent.com/6222464/115539040-15a50b80-a2cf-11eb-8cd6-29471c460dff.png)
ps:
1. my client is running on a android device 32bitwidth, cpu mt8167s 

do you have any suggestions to optimise its cpu cost?

**Comment by maxsharabayko** [comment]
Hi @cg82616424. One "utilizer" of CPU on your chart is [the receiving queue](https://github.com/Haivision/srt/blob/v1.4.3/srtcore/queue.cpp#L1217). Architecturally, [it waits](https://github.com/Haivision/srt/blob/v1.4.3/srtcore/queue.cpp#L1379) for at most 10ms for an incoming UDP packet.
Whether it has or has not received the packet, after waking up it iterates over SRT sockets in the list and checks timers if more than 10 ms has elapsed since the last check on that socket. [See here](https://github.com/Haivision/srt/blob/v1.4.3/srtcore/queue.cpp#L1302). 

[ACK packet](https://tools.ietf.org/html/draft-sharabayko-srt-00#section-3.2.4) has to be sent at least every 10ms.
Checking ACK timer and sending acknowledgement packets looks like one of the most "heavy" things on your chart.

Do all your SRT connections use the same UDP port or a different one? If a different one, than each UDP multiplexer gets its own thread for receiving and sending. See [SRT threads](https://srtlab.github.io/srt-cookbook/protocol/threads/).

**Comment by cg82616424** [comment]
Hi @maxsharabayko ，thanks for your reply:
    about your question, yep, all my srt connections are use the same udp port; I can confirm that, there is only 3 srt thread: sender, receiver and garbage collection;
    In my opinion, the most reasonable way is to increase the time of each ack check and then do a test;

**Comment by cg82616424** [comment]
I figured out this problem; 
because I use file mode, and every packet are NOT make payload full. this triggered quick ACK;
