### ISSUE TITLE
[BUG] 1.4.3 breaks Telegram-desktop and Chromium

### ISSUE THREAD

**Issue by zhinu** [Haivision/srt#1986]
**Describe the bug**
##### Chromium

> /usr/lib/chromium/chromium: error while loading shared libraries: libsrt.so.1: cannot open shared object file: No such file or directory

##### Telegram

> telegram-desktop: error while loading shared libraries: libsrt.so.1: cannot open shared object file: No such file or directory

**Desktop (please provide the following information):**
 - OS: Arch
 - SRT Version / commit ID: 1.4.3-1

**Workaround**
Downgrading works :)

**Comment by maxsharabayko** [comment]
It is due to the new naming of the resulting SO (PR #1741).
`libsrt.so.1` symlink is no longer built.
Instead, the following `so`s are created:
- `libsrt.so.1.4.3`
- `libsrt.so.1.4`-> `libsrt.so.1.4.3`
- `libsrt.so` -> `libsrt.so.1.4.3`

This change enables potential API/ABI modifications in minor SRT versions (e.g. 1.4 -> 1.5).

See also #1983.

**Comment by alexpokotilo** [comment]
@zhinu,
Do you know for what SRT is used in chromium and telegram ?

**Comment by zhinu** [comment]
@alexpokotilo No clue sorry. (My guess would be embedded video player)

**Comment by alexpokotilo** [comment]
> @alexpokotilo No clue sorry. (My guess would be embedded video player)
do you use standard chromium/telegram from repos/snaps ? We're tried telegram for ubuntu 20.04 and it doesn't use srt library.

@maxsharabayko 
do you know for what SRT is used in chromium and telegram ? Is it cus

**Comment by zhinu** [comment]
@alexpokotilo  Yes, standard from AUR.

**Comment by alexpokotilo** [comment]
@maxsharabayko 
my guess is that both chromium/telegram and probably all media-related apps in Arch linux related to ffmpeg.
Most probably SRT is built-in dependency of ffmpeg on this OS. And all packages/programs related to ffmpeg will be broken like @zhinu said. I'm not 100% sure but I was able to find these messages about this problem like this:
https://bugs.archlinux.org/task/70686

If so, and you think it's a problem, I need to change my #1983 so that previous SONAME is the default one.
Maybe it's Arch linux ffmpeg maintainer that he has not released new ffmpeg compatible with 1.4.3. I not sure too.
But it looks like new SONAME schema will break some software during transition.

**Comment by maxsharabayko** [comment]
@alexpokotilo 
> If so, and you think it's a problem, I need to change my #1983 so that the previous SONAME is the default one.

It would be best to proceed with the current versioning started in v1.4.3. It is sad though it will produce integration difficulties.

As you know, there is no sense in having `libsrt.so.1` symlink, as the major SRT version is not expected to change in the near future. Some parts of SRT API have to be improved, which will make it not 100% backward-compliant. Having the minor version in SRT makes it possible to preserve the API compliance at least within patch releases.

I think #1983 might be a good solution for now, allowing to wait for further feedback.

**Comment by alexpokotilo** [comment]
> I think #1983 might be a good solution for now, allowing to wait for further feedback.
@maxsharabayko 
Completely agree with all provided points and understand that current SONAME choice related to library release frequency and version convention. That's the best default choice in current circumstances. But my points about library compatibility between 1.4.3 for software with dynamic linking is valid too. That's all for customers convenience sake. Please merge #1983 so we/others can cherry-pick commit from master instead of my-own branch.

**Comment by maxsharabayko** [comment]
The upcoming v1.5.0 release also changes the ABI version to 1.5. As a result upgrading to the newer SRT version is not as smooth as just replacing the dynamic library, but also requires rebuilding certain modules against the newer version.
That's the expected strategy to avoid more critical issues due to API/ABI incompatibility.
See also [SRT versioning](https://github.com/Haivision/srt/blob/master/docs/dev/developers-guide.md#versioning).
