### ISSUE TITLE
Add server example for the C API

### ISSUE THREAD

**Issue by chadnickbok** [Haivision/srt#20]
Howdy,

I'm trying to run some simple tests using the SRT C API, and started by trying out the `testcapi.c` app. I managed to get it to build, but I couldn't find an example of creating an actual server.

Here's my simple PR to add a test c api based server: https://github.com/Haivision/srt/pull/21

**Comment by rndi** [comment]
Hello @chadnickbok,

Welcome and thanks for giving SRT a shot!

Also thanks for the proposed sample server. Unfortunately I am not sure the original testcapi.c is done correctly: I think it may be missing a few manditory socket options for SRT stack to work correctly. We will look into fixing testcapi.c first and then adjust the new testcserver.c code accordingly before the merge.

**Comment by ethouris** [comment]
The `testapi.c` file I'm using only to make sure that I don't get compile errors. This isn't predicted to be an example application. The best application that can be used as code example is `stransmit`. Find the function designated as `SrtCommon::OpenServer()` (the method is defined inside the class, so search by the method name).

This actually isn't too different than setting a server for TCP, even the functions have similar names, which still began with the UDT4 API, I just followed these footsteps. The only thing "new" towards TCP is the rendezvous mode.

**Comment by gurtajs4** [comment]
Hi All,
First of all, Thanks for SRT :)

I am planing to Compile SRT library and use it for Android Application,

1. Is is possible to compile the srtcore and generate the shared library  and take the advantage of full SRT like the app Stransmit is doing?
2. Again, can I use the SRT C API's to take the advantage of full SRT similar to Stransmit?
3. Can I use the SRT C Socket API to send H264 UDP packet  to SRT Client on Android APP side  and take advantage of features like less latency, packet loss re-transmission and error correction?

Thanks & Regards,
Gurtaj

**Comment by ethouris** [comment]
Gurtaj,

1. The default configuration is to compile everything as needed into one shared library. The `haicrypt` subproject can be alternatively compiled into a separate library and a dependency of `libsrt`, which is compiled in this case out of files contained in `srtcore` and some parts in `common`. This can be also compiled as a static library, also either as one or as two separate ones. So, the default one should fit just perfectly.

2. AFAIR `stransmit` should rely exclusively on the SRT C API. The call to `UDT::setlogstream` is the only exception, but it gets an argument of `std::ostream` type. A C application can still take advantage of catching the logging messages by using `srt_setloghandler`.

3. If you are using the standard live transmission packet size of 1316 bytes for these UDP packets, should be no problem. Just remember that SRT works logically more like TCP - it supports connection, control communication in both directions etc.. Note also that it's "less latency" towards possibly TCP transmission, towards UDP transmission it introduces even an extra latency. The latency control in SRT is not that it's less towards UDP (it's greater actually), but rather that it's more stable - that is, time gaps between packets should be the same at the receiver side and server side. The extra latency is introduced in order to both smooth the network jitter and make the lost-and-retransmitted packet still make it on time.

**Comment by gurtajs4** [comment]
Hello,
Thanks for the reply, I was almost expecting this.

As a matter of fact, I did compiled srtcore for Android Library(.so JNI) and used raw srt_* socket API.
Please find my attached SRT Server code, which I am using to 
- Stream video from MP4 to UDP port 5000 using VLC.
- Receive the data from UDP 5000 port and use  srt_sendto  to send the data to Android device using srt_recvfrom API to receive the data.

I am streaming 1080p 30FPS video and facing some packet loss issue. I have also tried specifying the SRTO_TSBPDDELAY using the srt_setsockopt API.
 
I was expecting that I should not see any packet loss while streaming over PC(server) and Android Tablet( Wireless).

Is there any problem in my methodology? 
[testcapiServer.txt](https://github.com/Haivision/srt/files/1257164/testcapiServer.txt)

Regards,
Gurtaj

**Comment by ethouris** [comment]
There are no such functions `srt_sendto` and `srt_recvfrom`. You scared me as hell that you are using some "already destroyed" functionality :). You probably meant `srt_sendmsg` and `srt_recvmsg`.

Please remember also one thing: use UDP transmission only in the frames of exactly ONE MACHINE.

The packet loss is predicted to be done also in SRT, but this time in a controlled way. The SRTO_TLPKTDROP option should be on by default and it should make packets dropped only when they could not be retransmitted on time (that is, the next-to-lost packet is already waiting for delivery and its time has come). If your latency is large enough, this should not fire too often (it's predicted to be done only in extreme cases of extraordinary delays in order to not cause hangup on transmission).

The default latency is 125ms. May happen that you have to make it a little bit larger. The recommended latency is not less than 4*RTT. In a usual cable networks RTT should be more-less 30ms, but I remember that in wireless networks RTT happens to vary dramatically (sometimes 10ms, sometimes 250ms). I would try to measure the values of RTT first and try such a latency that is equal to 4*RTT with the worst experienced RTT.

**Comment by gurtajs4** [comment]
Hi,
Yes I meant srt_sendmsg and srt_recvmsg. Sorry for confusion.
Once I determine the RTT, I should use sockopt SRTO_TSBPDDELAY to set the latency parameter?

Also by disabling SRTO_TLPKTDROP, will SRT make sure that lost packet is always delivered to Client no matter whaterver is the extra latency added?

Regards,
Gurtaj

**Comment by gurtajs4** [comment]
Actually In the logs I see that the data is over 1316, I received over 1400 bytes from VLC UDP port and send it to SRT to transmit wirelessly.

Also, on Android side I have to write Android Makefile to compile the source and linked statically.
Enabling the Logs on the server side which runs on the PC should also help us in identifying the number of packet recovered and lost in the transaction ?

Regards,
Gurtaj

**Comment by ethouris** [comment]
Definitely the logs will be helpful - you can find any information there that concern transmission details, also retransmission and the reason of it.

Sorry for late answer, I have drowned in this file transfer support thing...

**Comment by lars18th** [comment]
Hi @ethouris ,

As this it's targeted in #267 & #276 , I suggest to close this issue. :smile:

**Comment by gokulkrishnasr** [comment]
Anyone tried to use SRT Version 1.3.1 static lib with android?
I'm not able to link and getting following error. Any help?

libstaticsrt.a(srt_c_api.cpp.o):srt/srtcore/srt_c_api.cpp:function _GLOBAL__sub_I_srt_c_api.cpp: error: undefined reference to 'std::ios_base::Init::Init()'
libstaticsrt.a(srt_c_api.cpp.o):srt/srtcore/srt_c_api.cpp:function _GLOBAL__sub_I_srt_c_api.cpp: error: undefined reference to 'std::ios_base::Init::~Init()'
libstaticsrt.a(api.cpp.o):srt/srtcore/api.cpp:function CUDTUnited::CONID(int): error: undefined reference to 'std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream(std::_Ios_Openmode)'
libstaticsrt.a(api.cpp.o):srt/srtcore/api.cpp:function CUDTUnited::CONID(int): error: undefined reference to 'std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)'
libstaticsrt.a(api.cpp.o):srt/srtcore/api.cpp:function CUDTUnited::CONID(int): error: undefined reference to 'std::ostream::operator<<(int)'
libstaticsrt.a(api.cpp.o):srt/srtcore/api.cpp:function CUDTUnited::CONID(int): error: undefined reference to 'std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)'
libstaticsrt.a(api.cpp.o):srt/srtcore/api.cpp:function CUDTUnited::CONID(int): error: undefined reference to 'std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const'
libstaticsrt.a(api.cpp.o):srt/srtcore/api.cpp:function CUDTUnited::CONID(int): error: undefined reference to 'VTT for std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >'

**Comment by maxlovic** [comment]
Closed with PR #276 merged.
