### ISSUE TITLE
Error in caller mode

### ISSUE THREAD

**Issue by tomasevic** [Haivision/srt#202]
Hi, i notice that if i start stransmit in caller mode, i need to be very quick and start stream from udp source otherwise , stransmit send few keepalive packets and stops, if stream comes later, stransmit throws error like this below.How can i raise number of keepalive packets, so my socket can not be destroyed??

`tomas@tomas-GB-BACE-3160:~$ stransmit -v -t:-1 -loglevel:debug udp://:1234?timeout=360 srt://188.120.114.2:5555/?mode=caller&conntimeo=20000
[1] 2293
tomas@tomas-GB-BACE-3160:~$ Parameters:
        mode = 'caller'
Opening SRT target caller(blocking) on 188.120.114.2:5555
Connecting to 188.120.114.2:5555 ...  connected.
STARTING TRANSMISSION: 'udp://:1234?timeout=360' --> 'srt://188.120.114.2:5555/?mode=caller'
09:37:31.742248/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
09:37:32.771380/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
09:37:33.800794/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
09:37:34.829856/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
09:37:35.861524/SRT:RcvQ:worker D: SRT.c: KEEPALIVE
 << 1316  ->  FAILURE
srt_sendmsg: [5004] Operation not supported: Invalid socket ID.
SrtCommon: DESTROYING CONNECTION, closing sockets
`

**Comment by ethouris** [comment]
That's not the matter of keepalive packets, that's just the connection timeout. Normally you should simply first start the command on the listener side - which can wait for the connection forever - and then the caller.

You can also try setting the `conntimeo` parameter (URI parameter for SRT) to some highly enormous value and so your caller will wait for the response much longer.

The handshake - just like in case of TCP - relies on sending the connection request packets in short time periods, and then it awaits response. If no response comes in in a specified time, then the listener is considered dead and the connection request returns with error.

(In TCP you have a "Connection refused" error immediately when you connect to a nonexistent listener only because TCP is a system protocol and has a system support, so it can return appropriate "rejection" message from the system just by the fact that the system knows that no application is listening on that port; in case of SRT you don't have a system support for it, so it may only rely on the response timeout).

**Comment by tomasevic** [comment]
Hm it's like wowza server i breaking connection in this case.When i try my own compiled binaries from both sides, everything works fine.Thanks for your explanation!
