### ISSUE TITLE
[BUG] Periodic packet loss

### ISSUE THREAD

**Issue by gizahNL** [Haivision/srt#2041]
**Describe the bug**
Git commit 9848d68371e22b29f9e32c52ad6cd0e1bb81cc88 has introduced stream breakage every 1hr and 11m where the stream breaks for exactly 3 seconds, and then seems to empty it's buffers on the output. Only the receiving side seems to be affected by this bug
https://github.com/Haivision/srtgo/issues/19

**To Reproduce**
Compile from commit 9848d68371e22b29f9e32c52ad6cd0e1bb81cc88 and upwards, setup a stream and receive it with the srt-live-transmit app build from commit 9848d68371e22b29f9e32c52ad6cd0e1bb81cc88, the stream will break 1hr and 11m after start of the connection for 3 seconds.

![image](https://user-images.githubusercontent.com/8005186/122347058-ec5cd080-cf49-11eb-96f4-e5780cc19bb2.png)

**Comment by oviano** [comment]
This is interesting, as since I grabbed uodated srt code a month or so ago, I have become aware of something like this happening. The stream seems to freeze for a few seconds before recovering. I had put it down to just general network issues, but perhaps it relates to this.

It’s rare, and I am now going to keep an eye out and see if it happens every one hour 11 minutes!

**Comment by maxsharabayko** [comment]
Hi @gizahNL 
Thanks for noticing and tracking down to the exact commit!
Indeed, this issue was introduced in PR #1968.
The fix is submitted in PR #2043.

**Comment by gizahNL** [comment]
> Hi @gizahNL
> Thanks for noticing and tracking down to the exact commit!
> Indeed, this issue was introduced in PR #1968.
> The fix is submitted in PR #2043.

Thanks!
