### ISSUE TITLE
Dynamic Video Resolution + Framerate

### ISSUE THREAD

**Issue by MrHamel** [Haivision/srt#2059]
Hello,

Does the SRT protocol allow for dynamically changing video resolutions and framerates for both sending and receiving? If the answer is yes, do you all think OBS or VLC supports it?

Thanks!

Ryan

**Comment by ethouris** [comment]
SRT is content agnostic. Whatever formats or configurations are to be supported by particular endpoints, it all depends on the applications that communicate over it. The only thing that might be here related to SRT is when you want to use bandwidth control using a method that is input rate dependent (see e.g. SRTO_INPUTBW option). Otherwise everything depends exclusively on the applications.

**Comment by mbakholdina** [comment]
A couple of useful links:
- [SRT Packet Pacing and Live Congestion Control (LiveCC)](https://datatracker.ietf.org/doc/html/draft-sharabayko-srt-00#section-5.1)
- [Adaptive Rate Control for Live streaming using SRT protocol](https://ieeexplore.ieee.org/document/9379708)
