### ISSUE TITLE
Error message: SEQUENCE DISCREPANCY. BREAKING CONNECTION.

### ISSUE THREAD

**Issue by richtertoralf** [Haivision/srt#2093]
I use:
```
srt-live-transmit 'srt://:40062?mode=listener&latency=1000' udp://localhost:50062
```
I use OBS-Studio to receive the UDP stream. After a short time I get the following error messages. What am I doing wrong?

```
7:32:27.252025/SRT:TsbPd!W:SRT.br: @990292802:RCV-DROPPED 8 packet(s), packet seqno %821793843 delayed for 1500.964 ms
17:32:27.696930/SRT:TsbPd!W:SRT.br: @990292802:RCV-DROPPED 24 packet(s), packet seqno %821794104 delayed for 1306.131 ms
17:32:27.995108/SRT:TsbPd!W:SRT.br: @990292802:RCV-DROPPED 127 packet(s), packet seqno %821794405 delayed for 1158.156 ms
17:32:28.130062/SRT:TsbPd!W:SRT.br: @990292802:RCV-DROPPED 81 packet(s), packet seqno %821794564 delayed for 961.694 ms
17:32:28.294127/SRT:TsbPd!W:SRT.br: @990292802:RCV-DROPPED 36 packet(s), packet seqno %821794685 delayed for 862.957 ms
17:32:28.472105/SRT:TsbPd!W:SRT.br: @990292802:RCV-DROPPED 50 packet(s), packet seqno %821794817 delayed for 669.290 ms
17:32:28.608236/SRT:TsbPd!W:SRT.br: @990292802:RCV-DROPPED 213 packet(s), packet seqno %821795111 delayed for 496.848 ms
17:32:28.712085/SRT:TsbPd!W:SRT.br: @990292802:RCV-DROPPED 73 packet(s), packet seqno %821795267 delayed for 235.790 ms
17:32:28.960049/SRT:TsbPd!W:SRT.br: @990292802:RCV-DROPPED 101 packet(s), packet seqno %821795454 delayed for 49.007 ms
17:32:42.634040/SRT:RcvQ:w1*E:SRT.qr: @990292802:SEQUENCE DISCREPANCY. BREAKING CONNECTION. seq=821803732 buffer=(821795541:821803731+821803732), 1 past max. Reception no longer possible. REQUESTING TO CLOSE.
SRT source disconnected

```

**Comment by maxsharabayko** [comment]
@snowgames95 
Please share more info on how to reproduce the issue.
- SRT version (`srt-live-transmit -version`),
- OBS Studio version.
- Encoding bitrate and configuration.
- Network for `srt://:40062` (localhost/remote), RTT.
- How quickly do those errors appear.
- ... Anything else that would help.

**Comment by snowgames95** [comment]
- SRT Library version: 1.4.3
- OBS Studio 27.0.1 (linux)
- OS Ubuntu 20.04
- Network: 
 1. Camcorder with 4G-Encoder Bitrate 2000 Mbits  
 2. WireGuard-Cloud-Server (only Portforwarding)
 3. my Computer with srt-live-transmit 'srt://:40062?mode=listener&latency=1000' udp://localhost:50062
 4. an also on my Computer OBS-Studio udp://0.0.0.0:50062
- "link":{"rtt":275.722,"bandwidth":7.5,"maxBandwidth":1000},  rtt between 70.000 and 290.000, bandwidth between 5000 and 8000 Mbits
I want to process multiple input streams (3 camcorders with 4G encoders, a smartphone with Larix Broadcaster and three PTZ IP cameras).
During the test, I only had the one camcorder or only one smartphone in use.

**Comment by maxsharabayko** [comment]
You are sending 2000 Mbits (2 Gbps) over SRT, right?
With 1-second latency buffer, according to [this guide](https://github.com/Haivision/srt/blob/master/docs/API/configuration-guidelines.md), you should also increase the limit for packets in flight (flow control) to `SRTO_FC` = 218465 and increase receiver buffer size to `SRTO_RCVBUF` = 321580480 bytes.
Or 
```shell
srt-live-transmit 'srt://:40062?mode=listener&latency=1000&fc=218465&rcvbuf=321580480' udp://localhost:50062 -loglevel warn
```
You might actually have not enough room to store incoming packets. This is a warning message. In some previous versions, warnings were not shown by `srt-live-transmit` by default. So using `-loglevel warn` they should become seen.

Also, the default `SRTO_MAXBW=1Gbps` would be not enough. But it is the sender-side option. I hope the sender has this option properly configured as well.

### If It Is Not the Lack of Buffer Space

> ... delayed for 1500.964 ms

Otherwise with RTT between 70 and 290 ms having packets dropped with a delay of 1.5 seconds is odd.
If it is not the buffer size, could you also collect:
1. Wireshark capture of the stream to analyze packet timing. The encrypted payload would also work if you would like to secure the content (SRT headers remain unencrypted).
2. Collect SRT stats from `srt-live-transmit` using `-pf csv -s 10000 -statsout srt-2Gbps-rcv.csv`

**Comment by snowgames95** [comment]
Sorry,
I send 2 Mbits. Not 2000 Mbits.
bandwidth between 5 Mbits and 8 Mbits

**Comment by maxsharabayko** [comment]
> I found that the error only occurs when I set a latency more than 3000 ms.

So with one-second latency as in [the example](https://github.com/Haivision/srt/issues/2093#issue-972823832), you don't have issues, but start having at latencies above 3 seconds?

How fast after the start does the issue take place?

Could you also collect:
1. Wireshark capture of the stream to analyze packet timing. The encrypted payload would also work if you would like to secure the content (SRT headers remain unencrypted).
2. SRT stats from `srt-live-transmit` using `-pf csv -s 10000 -statsout srt-2Gbps-rcv.csv`
