### ISSUE TITLE
dlopen failed: cannot locate symbol "in6addr_any" referenced by "/****/lib/arm64/libsrt.so"...

### ISSUE THREAD

**Issue by Hyun-Jegal** [Haivision/srt#2147]
Problem appears when running System.loadLibrary("srt") on LG G5 phone (android 6.0.1).

In srt module version 1.4.4 the problem is as follows:
logcat
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "in6addr_any" referenced by "/****/lib/arm64/libsrt.so"...
   at java.lang.Runtime.loadLibrary(Runtime.java:372)
   at java.lang.System.loadLibrary(System.java:1076)
   ...
   ...

The problem does not occur with srt module version 1.4.1.

**Comment by fallenhaivision** [comment]
Hi,
SRT 1.4.1 didn't have support for IPv6 and thus didn't have any references to in6addr_any. I'm not sure when Android add support for IPv6, Android 6.0.1 might be too old.

I have running into devices that don't have support for Multicast because the manufacturer didn't compile their Linux with Multicast support. Perhaps LG didn't compile support for IPv6 for the LG G5?

**Comment by maxsharabayko** [comment]
Hi @Hyun-Jegal! I wonder if you have an update on this topic?
If you happen to solve the issue, please share your solution here. That would be useful for the community.
