### ISSUE TITLE
[BUG] Connection timeout on macOS when using acquired UDP socket

### ISSUE THREAD

**Issue by acmanderson** [Haivision/srt#2178]
**Describe the bug**
On macOS, using `srt_bind_acquire` followed by `srt_connect` will fail with `SRT_ENOSERVER`. 

**To Reproduce**
1. On macOS, create a non-SRT UDP socket pointing to the listening address of an SRT server. I'm using `srtgo` with the following snippet to connect to the destination and return the socket's file descriptor:
    ```go
    func connect() (int, error) {
	    udpConn, err := net.DialUDP("udp", nil, &net.UDPAddr{IP: net.ParseIP("127.0.0.1"), Port: 7005})
	    if err != nil {
		return 0, err
	    }
	    var fd int
	    syscallConn, err := udpConn.SyscallConn()
	    if err != nil {
		return 0, err
	    }
	    if err := syscallConn.Control(func(_fd uintptr) {
		fd = int(_fd)
	    }); err != nil {
		return 0, err
	    }
	    return fd, nil
    }
    ```
2. Use `srt_bind_acquire` on the UDP socket.
3. Use `srt_connect` to attempt to connect to the server.
4. `SRT_ENOSERVER` should be returned.

**Expected behavior**
The UDP socket will be properly reused by the SRT library as the client socket. I'm not totally sure this is supported behavior, but it works when running on Linux.

**Desktop (please provide the following information):**
 - OS: macOS 11.6
 - SRT Version / commit ID: 1.4.3 and 1.4.4

**Additional context**
I've narrowed this down to a difference in the `sendmsg` syscall between Linux and macOS/FreeBSD. On macOS, calling `sendmsg` on a connected socket with a destination address in `msghdr` will fail with `EISCONN`. Per the [FreeBSD `sendmsg` man page](https://www.freebsd.org/cgi/man.cgi?query=sendmsg&sektion=2&n=1): 
> [EISCONN]	A destination address was specified and the socket is already connected.

Per the [Linux `sendmsg` man page](https://linux.die.net/man/2/sendmsg): 
> EISCONN The connection-mode socket was connected already but a recipient was specified. (Now either this error is returned, or the recipient specification is ignored.)

The [`srt::CChannel::sendto` function](https://github.com/Haivision/srt/blob/v1.4.4/srtcore/channel.cpp#L607-L616) always sets the destination address in its `sendmsg` call.

I'm not much of a C developer, but I was able to get around this issue by replacing the `sendmsg` call with the following:
```c++
int res = ::sendmsg(m_iSocket, &mh, 0);
if (res == -1 && errno == EISCONN)
{
    mh.msg_name = nullptr;
    mh.msg_namelen = 0;
    res = ::sendmsg(m_iSocket, &mh, 0);
}
```
I imagine this is a non-optimal solution to the problem, but it demonstrates the cause of the issue.

**Comment by Thulinma** [comment]
Hey all! So... it would actually be nice if this _was_ changed/supported to some degree.
For full details (including why you'd want it) you can watch [my FOSDEM talk about this](https://fosdem.org/2025/schedule/event/fosdem-2025-6052-how-mistserver-handles-srt-connections-in-independent-child-processes/) but the summary is this:
Sometimes, you want to be able to handle an incoming SRT connection in a separate process. To do this, you can create a connected UDP socket (pre-connected to either a calling or rendezvous peer) and pass it to `srt_bind_acquire`, then call `srt_listen` and `srt_accept_bond` to accept the incoming handshake(s), close the "first SRT socket" and keep only the "second SRT socket" (both of these of course use the same connected UDP socket internally, so this closes no underlying actual sockets).
The result is a properly functioning SRT connection with a single peer while you can keep listening for other incoming callers in an entirely different process! ✨

This works great as-is.... on Linux.

On Windows, this is a non-starter since their UDP implementation does not route packets to the most-specific socket (but rather to the last-opened socket, instead 😩)... nor does it work on MacOS, because MacOS throws an error (actually `EINVAL` in my experience, rather than `EISCONN`) when you call `sendmsg` with a destination set (Linux simply ignores it and does not complain at all).
So making a change similar to the suggested one in the original issue description above (or perhaps something a little cleaner..?) would enable this trick to work as well on MacOS.
Right now we're patching this into `srt` as a subproject of the software we're using this trick in specifically for MacOS users (a minority of the userbase, but still....), but not needing to do that would be pretty nice.

A version of `srt_bind_acquire` that combines all these steps specifically for the purpose of "accepting" a single incoming connection on a connected UDP socket would be even better of course - but that seems like a bigger ask (and a bigger change) and all this is probably fairly niche already. Totally happy to keep patching it in as well, but since the documentation specifically links to this issue referring to why you shouldn't use a connected UDP socket, I figured I'd drop a reply here and see what happens. 😁
