### ISSUE TITLE
stransmit traffic handle over multiple wan (gateways)

### ISSUE THREAD

**Issue by ggnull35** [Haivision/srt#226]
Hi Everyone,

I was testing strasnmit over multiple WANs.  I setup an environment with 4 WANs. 
1 DSL [names em1] +  3 LTE [named wwanX] conns.
My source stream is 1.2 Mbps (150 kBps) UDP mpegts.

I noticed a strange behaviour of stransmit:

Using only em1's GW, everthing is OK.
![image](https://user-images.githubusercontent.com/8988826/34941024-07448d7c-fa03-11e7-9510-6619abe76e9b.png)

If I change gw definition to multiple WAN using nexthop, I can see traffic is equally distributed:
![image](https://user-images.githubusercontent.com/8988826/34941059-30ccc880-fa03-11e7-8a3a-52cacdf3eba8.png)

(nexthop has wwan0, wwan1, wwan2. Does not include em1)

However, almost after 10 secs, stransmit quits:
FAILURE
srt_sendmsg: [2001] Connection was broken.
SrtCommon: DESTROYING CONNECTION, closing sockets
terminate called after throwing an instance of 'std::invalid_argument'
  what():  error in srt_sendmsg
Aborted

Additional Note:
em1 has still traffic due to;
15:04:01.908503 IP XXXX.10000 > 192.168.2.98.33022: UDP, length 44
15:04:02.327730 IP XXXX.10000 > 192.168.2.98.33022: UDP, length 44
15:04:02.738674 IP XXXX.10000 > 192.168.2.98.33022: UDP, length 44
15:04:03.141001 IP XXXX.10000 > 192.168.2.98.33022: UDP, length 44
server side query.

I found that stransmit fails due to em1 is not in default gw list. However; if I include gw to nexthop list, (wwan0 wwan1 wwan2 em1) then total traffic looks doubled:

![image](https://user-images.githubusercontent.com/8988826/34941182-b99da56c-fa03-11e7-821c-19b461294559.png)

I assue stransmit sends over a 150 kBps streams over wwan0 + sends a 2nd 150 kBps stream divided to 4 WAN interfaces by their weight.

As side;

Note 1:
If I push a simple UDP stream with above conditions, it is balanced by weight. No doubling. I checked my network settings again and this is a behaviour of stransmit.

Note 2:
The traffic behaviour changes if you change nexthop conf. while running stransmit compared to change nexthop conf. before running stransmit. I seems on stransmit init., stransmit checks gw 0.0.0.0 interfaces and makes "a" setup.

Note 3:
If you set down an interface n nexthop while strasnmit is running, stransmit quits giving a failure. Stransmit can not understand actually the packets are still being transmitted by other WAN interfaces.

(I am reporting this as there can be an enhancement. As of today, RTMP/flv is not a good option anymore live streaming. HLS/DASH has latency. People seek for low latency and SRT is an option.)

**Comment by ethouris** [comment]
Let me ask one question first, just to make sure we're on the same page: does this work with TCP?

I'm asking because you have mentioned some unusual configuration where you replicate UDP packets. Note that SRT is based on a statement that no one is doing any messup with UDP packets that SRT library wasn't explicitly tested against. Best to state is that UDP packets carrying SRT traffic should be transmitted straightforward way.

**Comment by ggnull35** [comment]
I didnt get your uestion completely. What do you mean exactly by TCP ?

Fyi; I didnt setup any iptables configuration. Even before all tests I did iptables -F, iptables -t nat -F.
So, there w no DNAT to make any UDP/TCP or vice versa convertions.

SRT command line;
/opt/penc/sbin/stransmit -r:1000 -s:1000 "udp://@239.210.10.1:1234" "srt://XXXXX10000" -v -k

UDP source is coming from FFmpeg:
/opt/ffmpeg/bin/ffmpeg -f lavfi -re  -i testsrc=size=720x576:rate=25 -f lavfi -re -i sine=frequency=1000:sample_rate=48000:beep_factor=1 -c:v:0 libx264  -preset ultrafast    -profile:v main   -vb 1000k -minrate 1000k -maxrate 1000k -bufsize 1000k -muxrate 1200k -pix_fmt yuv420p  -c:a:0 aac -b:a:0 128k -ac 2  -g 50 -f mpegts "udp://239.210.10.1:1234?pkt_size=1316&localaddr=127.0.0.1&bitrate=1200000&overrun_nonfatal=1"

IP route command examples:
ip route replace default scope global nexthop via 10.52.18.165 dev wwan0 weight 20 nexthop via 100.91.40.185 dev wwan1 weight 10 nexthop via 10.73.102.97 dev wwan2 weight 10

or 

ip route replace default scope global nexthop via 10.52.18.165 dev wwan0 weight 20 nexthop via 100.91.40.185 dev wwan1 weight 10 nexthop via 10.73.102.97 dev wwan2 weight 10 nexthop via 192.168.2.1 dev em1 weight 40

In short, I do not modify or mark or dnat packets. I just play with routing policy via ip route command. Stransmit is UDP based. So, IP route command changes the WAN interface of the packet being delivered, like a load balancing.

**Comment by ethouris** [comment]
The question "whether it works with TCP" was simple - can you copy a file to another server using the exact target address that was designated in the SRT uri using scp command. But this probably will work only due to the fact that TCP is seen as a separate protocol and this rule won't apply here, as well as probably the firewall facility is wise enough to not allow you to do this on TCP.

SRT is a connection-based protocol (just like TCP), just built on top of UDP, that is, using UDP instrumentally for both data and control communication. It utilizes then a "bidirectional UDP" communication, which the firewall software identifies as a kind-of "channel", which is defined by the fact that there's a UDP packet sent from address A to address B, and not a long time after a packet is coming from address B to address A. This "channel" disappears after some timeout of no communication in any direction. SRT requires that the UDP packets are sent along this exactly channel, and it you mess up anything here, SRT simply won't work. The initial packet may come from whatever source, but it must be then a handshake communication. Once the handshake is done, the packets to be considered for this connection must come from exactly this address that has been recognized in the handshake, otherwise they are treated as "out of the blue" (attack attempt) and rejected.

**Comment by ggnull35** [comment]
Thank you for the detailed email explanation. I got the picture very clearly. 

 So, for ex;  If i start an SRT instance over em1 wwan interface and switch packets to other 3 wwan interfaces like wwan0, wwan1 and wwan2., connection will fail as it happens now. 

And, if i start an SRT instance over em1 wwan interface and add other 3 wwan interfaces like wwan0, wwan1 and wwan2 to the default route, even wwan0, wwan1 and wwan2 send packets load balanced, actually they are dropped as source IP is different. Only packets coming from em1 will be accepted and connection will not drop as there is on going handshake.  Am I correct?

To use stransmit in the given goal, I think code needs to be modified to accept packets from other IP sources and make strasnmit to check handshake with other interfaces as well. 

I will try this.

**Comment by ethouris** [comment]
Theoretically you could do this, but this way you make SRT vulnerable for attacks. The idea of connection is also a protection area - packets from "anywhere" are accepted only if this is a connection request (and in caller-listener configuration this isn't taken lightly), and once the connection is established, only packets from the address registered during connection is allowed.

**Comment by ggnull35** [comment]
Thank you once again for details. I am going to close the ticket. If I succeed.in the code development, I will share a fork.

**Comment by mahdisalimi66** [comment]
Hi everyone
Is there a solution for SRT protocol (udp) load balancing (for multi WAN and Gateway) ?
