### ISSUE TITLE
TR 101 290 priority-1 and priority-2 errors during transfer

### ISSUE THREAD

**Issue by mks75** [Haivision/srt#233]
Hi,
During transfer, on receive side, I am seeing intermittent Priority-1 and Priority-2 error on TR 101 290, however the multicast mpeg-ts source is completely clean.
The idea is to have clean receive of the stream for broadcast compliance.
How can I fine tune the transfer? What are the factors that could cause this and related parameters that I can set on server and client side? The parameters are not very clear from the documentation. Please advise.
Thanks-

**Comment by alexpokotilo** [comment]
If it's constand bitrate, PAT/PMT send frequency or pcr sending frequency requirements - please us know.
I was not able to find appropriate info per these TR xx numbers unfortunately

**Comment by mks75** [comment]
Hi,
PSI/SI tables are correct in the stream. The error on the receive side is due to the packet loss during transport. Right now I haven't put any additional parameters either on Server or client side while using stransmit. Please advise, what all parameters should I check on my path (like latency or bandwidth) and how can I fine tune my transfer accordingly.
Thanks-

**Comment by ethouris** [comment]
Please show how you are running stransmit and we'll see what can be done.

**Comment by mks75** [comment]
Hi,
Following are the commands
The multicast mpegts source at server-1 Location-A is udp://238.1.1.1:1234

server-1 at Location-A (server side)
./stransmit -v udp://@238.1.1.1:1234 srt://server1-ip:38000?mode=server

server-2 at Location-B (client side)
./stransmit -v srt://server1-ip:38000?mode=client udp://@239.1.1.1:1234

Thanks-

**Comment by ethouris** [comment]
You have then three places where you can potentially lose packets:
1. The first command, it may lose UDP on multicast.
2. The SRT connection
3. The output to UDP multicast

For 1, try to run this command using a local filename as a destination, then check if you happen to have any errors in this stream.
For 3, similarly, try to repeat the same using a local mpeg-ts file on this server just replay it with `ffmpeg -re` through a pipeline to stransmit (use `file://con` as source to read from pipeline).

For 2, the SRT connection, packets may be lost under the following condition:
- packet was lost as UDP packet
- a subsequent-to-lost UDP packet is already delivered and the time has come for it to play

This behavior is controlled by SRTO_TLPKTDROP, it's on by default and it's usually an expected behavior. You can turn it off, but this will cause that the stream is allowed to pause if recovering a lost packet takes a long time.

How early a received UDP packet becomes ready to play, it's controlled by the SRTO_LATENCY option, which is 120ms by default. If you have a proof that packets are being lost on the SRT connection, try to increase the value of latency (e.g. add `latency=500` to SRT URI as parameter). Note that the 120ms latency is predicted to be ok for network that have an average pessimistic RTT 30ms.

**Comment by ggnull35** [comment]
I think this case is user specific. I use StreamXpert to monitor SRT out UDP traffic and I have no Priority-1 & 2 errors/warnings. (Additional note: I carry 2 channels to a satellite over open internet infrastructures, satellite platform monitors traffic as well and they have no error report as well.

(Documentation has a very well explanation on latency calculation. )

**Comment by mks75** [comment]
Thanks @ggnull35 for sharing your feedback. Are you using additional parameters in stransmit at server or client side? Please share.
Thanks @ethouris for the explanation. My test network has RTT of more than 250ms and looks congested and requires some fine tuning of the parameters.
Thanks-

**Comment by lars18th** [comment]
> My test network has RTT of more than 250ms and looks congested and requires some fine tuning of the parameters.

Yes! You need to add the parameter "&latency=" for increasing the latency and avoid errors. If you're using _open_ Internet, then I recommend to use between 8-10 times the _regular_ RTT. This avoid puntual congestions.

Please, close this issue if this solves your problem!

**Comment by mks75** [comment]
on my test network, with &latency=1000, the transport is now error free!
Thanks-
