### ISSUE TITLE
Streaming a file using gst-launch

### ISSUE THREAD

**Issue by Winneee** [Haivision/srt#2345]
Hi , I am trying to stream using srtsink and able to successfully stream from rtsp source and v4l2src , when trying the same from filesrc, not able to see any frame on vlc . 
Using below pipeline:-
 gst-launch-1.0 --gst-debug=3 filesrc location=./frame04d.mp4 ! qtdemux ! queue ! h264parse ! video/x-h264, stream-format=byte-stream ! mpegtsmux ! srtsink uri=srt://:8888

**Comment by Winneee** [comment]
Thanks @ethouris . this didn't solve my problem, i managed to stream but getting below warning frequently, due to which not able to stream, is it somehow related ?
0:00:00.327483100 20844     0x2c4bec60 WARN               srtobject gstsrtobject.c:1488:gst_srt_object_write_to_callers:<srtsink0> Dropping caller 316371121: Non-blocking call failure: no buffer available for sending
<flags GST_MESSAGE_EOS of type Gst.MessageType>

**Comment by ethouris** [comment]
This is the error that is reported by the call to `srt_send` in non-blocking mode when sending was no longer possible due to full sender buffer. This is usually the case when you try to send faster than the network can bear, and likely the fact that there is no "dampening" of the data read from file and lack of synchronization with the stream's timestamps.

That above was only to give you a hint where to search - you need to find a method to make a "live stream from a file". I don't know how to do it in GStreamer. You can try with ffmpeg and using the `-re` option, just to test if it can work. For example, flip this from file to UDP by `ffmpeg -re` and then use `udpsrc` element to read this by GStreamer (or you can use the pipeline for it if you can, but I don't know which element to use to read it).
