### ISSUE TITLE
[BUG] CUnitQueue::increase cost high CPU

### ISSUE THREAD

**Issue by kay1ess** [Haivision/srt#2346]
Hi, I have a question about  CUnitQueue::increase. In may case,  SRT:RcvQ cost CPU 99%, when the 100 srt streams 
published.  But other thread overload is very low. That make published streams is not very stable. 
this is perf my program text.

OS: Linux  5.11.0-49-generic #55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
libsrt version 1.4.2 & 1.4.4 have same quersion.

top:
3747274 root      20   0 3313012 916504   6828 R  98.7   0.7   0:08.73 SRT:RcvQ:w1                                                                                                                
3747264 root      20   0 3313012 916504   6828 S   0.7   0.7   0:00.03 media-gatew                                                                                                            
3747271 root      20   0 3313012 916504   6828 S   0.7   0.7   0:00.07 media-gatew                                                                                                            
3747251 root      20   0 3313012 916504   6828 S   0.3   0.7   0:00.08 media-gatew                                                                                                            
3747254 root      20   0 3313012 916504   6828 S   0.3   0.7   0:00.03 media-gatew

listening socket config:
    int lantency = 500;
    int ret = srt_setsockopt(fd_, 0, SRTO_LATENCY, &lantency, sizeof lantency);
    int fc = 350274;
    ret |= srt_setsockopt(fd_, 0, SRTO_FC, &fc, sizeof fc);
    size = fc * 1472;
    ret |= srt_setsockopt(fd_, 0, SRTO_RCVBUF, &size, sizeof size);

**Comment by ethouris** [comment]
If your application is receiving these 100 streams as a listener, it's quite possible that on certain machines it may take 99% CPU, although it's kinda weird. Please tell us also how your use case looks like, that is, what is this machine doing from which you took the data and how the streams are being sent.

**Comment by kay1ess** [comment]
sorry, it's long time to reply the message. @ethouris 

### cpuinfo
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
stepping	: 1
microcode	: 0xb00001f
cpu MHz		: 2100.000
cache size	: 20480 KB
physical id	: 0
```

I published 100 SRT streams from other machine by ffmpeg. 
the cmd:
```
./ffmpeg-4.2.2-amd64-static/ffmpeg -re -stream_loop -1 -i yangpian.flv -c copy  -f mpegts 'srt://10.68.81.134:1937/?streamid=#!::h=live-push.bilivideo.com,r=live-bvc/?streamname=fmp4_150,key=b13a2fe9c7e95fb8ed747e7ff1e506,pflag=1'
```
the example yangpian.flv metadata is
```
Metadata:
    encoder         : Lavf57.56.101
  Duration: 00:05:57.89, start: 0.000000, bitrate: 6179 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 62.50 fps, 59.94 tbr, 1k tbn, 119.88 tbc
    Stream #0:1: Audio: aac (LC), 48000 Hz, 5.1, fltp
```

100 streams, about 600Mbps.  when publish 100streams,  cost CPU of SRT:RcvQ:w1 is high, and is look like stable, But add more streams, may some stream will drop cause server not recv data in 10s.


The srt server listen a srt socket which will recv mpegts data, then product HLS. The HLS Segment writen on /dev/shm, so write disk is not a problem. 

Maybe my server is not complete, but would you tell me how many should handle srt streams(6Mbps) in normal server on like my machine?

And other question, why allow only a srt socket to listen, as i kown, multi thread can listen a socket in linux kernel?

**Comment by ethouris** [comment]
Ok, but there's still one key thing I didn't get - the machine, on which you have detected this problem, is sending or receiving these 100 streams? Because if sending, then the only role for the receiver queue thread is to receive ACK and LOSSREPORT messages, which is negligible in comparison to data transmission. There is a build option `USE_BUSY_WAITING`, which could cause this when turned on during building, but it is off in the default build options - you might want to check this thing in your case.

As per the multithread listen: this thing has been running around here for some time and short explanation is this: UDP sockets don't listen. You can only read and write through them. The SRT listening is its own mechanism written in userspace and has nothing to do with anything system-related in this case. And when a packet is being read in SRT from the UDP socket, SRT must recognize first what this thing is (a data packet, some control packet, or maybe a connection request) and pass it on further for processing. To take advantage of multithreaded reading, the whole mechanism of reading and dispatching would have to be reworked, so that the dispatching into either a receiver buffer or control processing (likely to be passed through a queue to another thread) can be done by one of the reader threads. This alone isn't very complicated, but the problem in the current implementation (unchanged since UDT codebase) is that the receiver thread is used for both reading data from the socket and performing various periodic communication tasks (such as sending keepalives, repeating async handshake responses, perform periodic NAKreport etc.). This would have to be separated from the receiver thread first, and this also requires organizing the communication between this thread and the others. That's also one of the reasons why the receiver thread is using non-blocking mode for the UDP socket and performs some other tasks between the checks of `select`.

**Comment by maxsharabayko** [comment]
Hi @kay1ess 
Could you check if PR #2395 makes any difference for your server application?

**Comment by ethouris** [comment]
Ok, so in this situation you may have 100 independent connections within SRT and they all will be handled by the same UDP socket. Then it's at least possible and easy to explain that works this way.

And there's no way to do anything about it on the listener side. In order to make the parallel reading on separate threads, you'd have to have a caller side on the receiving application, or use rendezvous connections (each connection on a separate port on both sides).

**Comment by kay1ess** [comment]
> Hi @kay1ess Could you check if PR #2395 makes any difference for your server application?

@maxsharabayko  ok, let me check it

**Comment by kay1ess** [comment]
> PR #2395

The patch works well.  Now My applicaiton could receive 160 streams stably about costing 90% cpu. 
It's a extremly improvement!!!

For my situtaion, maybe I need to use rendezvous connections.  I have to try it.

At last, Thanks !

**Comment by kay1ess** [comment]
> Ok, so in this situation you may have 100 independent connections within SRT and they all will be handled by the same UDP socket. Then it's at least possible and easy to explain that works this way.
> 
> And there's no way to do anything about it on the listener side. In order to make the parallel reading on separate threads, you'd have to have a caller side on the receiving application, or use rendezvous connections (each connection on a separate port on both sides).


On listener side,  Can I  listen different port by mulitthread, but only port for external,  in receving data, create rendezvous connection to assign to internal port?  Does it work? @ethouris

**Comment by ethouris** [comment]
As long as you manage that on the application level. SRT is thread safe, so you can use different threads for handling different streams on separate connections. Just note that the real system-level receiver is the receiver thread, and they are only separate if you use separate ports (which is not currently possible with the listener). So, you can, for example, use the SRT listener for the purpose of exchanging some information (like a port number), and then make the connection as rendezvous. This can also work if you want to try "callback method" (the listener is only to make the receiver side request a connection on receiver's listening port).
