### ISSUE TITLE
incorrect macro under windows

### ISSUE THREAD

**Issue by marakew** [Haivision/srt#2362]
srtcore\core.h(546): warning C4002: too many arguments for function-like macro invocation 'SRT_ATTR_REQUIRES'

https://github.com/Haivision/srt/blob/49fb18e2b039242e46b306f23b9886be692f074c/srtcore/core.h#L546

**Comment by maxsharabayko** [comment]
Sadly Clang TSA and SAL are not fully interchangeable.
Maye one of those has to be dropped sometime.

For example, I get errors reported by Visual Studio for `enterCS` and other, because MSVC expects `SRT_ATTR_EXCLUDES` to come before the function, while Clang TSA just does not see the variable `m` in that case.

Having something like the following does not look good to me:
```c++
#ifdef _WIN32
SRT_ATTR_EXCLUDES(m) SRT_ATTR_ACQUIRE(m)
inline void enterCS(Mutex& m) { m.lock(); }

SRT_ATTR_EXCLUDES(m) SRT_ATTR_TRY_ACQUIRE(true, m)
inline bool tryEnterCS(Mutex& m) { return m.try_lock(); }

SRT_ATTR_REQUIRES(m) SRT_ATTR_RELEASE(m)
inline void leaveCS(Mutex& m) { m.unlock(); }
#else

inline void enterCS(Mutex& m) SRT_ATTR_EXCLUDES(m) SRT_ATTR_ACQUIRE(m) { m.lock(); }
inline bool tryEnterCS(Mutex& m) SRT_ATTR_EXCLUDES(m) SRT_ATTR_TRY_ACQUIRE(true, m) { return m.try_lock(); }
inline void leaveCS(Mutex& m) SRT_ATTR_REQUIRES(m) SRT_ATTR_RELEASE(m) { m.unlock(); }
#endif
```

**Comment by maxsharabayko** [comment]
So you are not running code analysis, just observe the warning during regular compiling, right?
Thanks for the patch!

**Comment by marakew** [comment]
yes
