### ISSUE TITLE
[FR] Ability to "abandon" current buffer, and start again following the next send call

### ISSUE THREAD

**Issue by oviano** [Haivision/srt#2447]
By default, my server application only sends a key frame at the start of the stream. When my player application detects it has lost packets, it requests, via a separate TCP channel, that a new keyframe be generated. This saves bandwidth (as most of the time, I do not send key frames at all) while still allowing the player to recover quickly enough.

To make it even better, I would like to be able to tell the SRT system that I no longer care about any pending sends, retransmits, etc until the new key frame is sent by the server. The fact packets have been lost and a key frame has been requested suggests the link is already struggling, so there would seem to be a benefit in being able to immediately cancel all this traffic.

Perhaps the way to achieve this would be a simple "clear_buffer" call. The player would call this at the same time it requests the new key frame. The server, on receipt of the key frame request could also then call clear_buffer(), and also cease any further sending until the encoder has generated the key frame. This would catch most of the data, if not all (the exception would be any data sent between the two calls to clear_buffer on each side of the link).

Maybe there is some already-existing functionality that would do something similar to the above?

**Comment by ethouris** [comment]
What mode are you using to send the stream? Because if live, it is completely useless. Normally you should have at worst 3 packets in your sender buffer - more you can only have if you have set up the bandwidth limit and you are exceeding it with the speed of sending particular packets.

In this mode then it's the application that should schedule single packets in time for sending and the application should simply stop it. Some function might be useful to force abandoning all loss lists on the sender side so that no more recorded lost packets will be retransmitted, and possibly then send the drop request to the receiver so that it doesn't request these packets anymore - but that's all. If you detect the problem quickly enough, the gain from such a call would be rather insignificant. Actually the biggest part of the packets that you would like to cancel are in the flight, and there you can do nothing.

**Comment by maxsharabayko** [comment]
@oviano I would say this feature is partially available. There is no API function to reset the sending buffer as of now. However, if you add such a function, the rest would be handled by SRT. If the receiver sends a loss report on a missing packet, the sender does not find this packet in its buffer, and would just reply with the [SND message drop request](https://datatracker.ietf.org/doc/html/draft-sharabayko-srt-01#section-3.2.9).
Of course, a better way would be for the sender to send those drop requests early when all packets are dropped from the buffer. That would improve efficiency.

**Comment by ethouris** [comment]
This could be done basing on what is currently being done in response to ACK reception, using the ACK value from the youngest sequence number from the sender buffer + 1, and additionally one DROPREQ packet could be sent (can be lost, of course, but since this moment every loss report for the abandoned packets will generate this message).

**Comment by oviano** [comment]
Ok thank you, I think I have a better understanding of what is/isn't possible. I can see that the send buffer is likely to be almost empty as everything is sent right away and likely to be in-flight. So really any benefit would be in preventing retransmission requests + retransmissions of lost packets and I understand the suggestions above as to ways to achieve that.

I will feedback further if I take this further! Thank you.
