### ISSUE TITLE
Stats file administation

### ISSUE THREAD

**Issue by GabTlc** [Haivision/srt#2472]
Hi there!
we just implemented a SRT server receiver, and to monitor it we are using the stats that we are saving in a json file, actually, we are accesing this file and representing some values in a grafana board without any problem. The limitation that we noticed, is that the stat file is incresing constantly so we want to move it to a file repository, compress it to save space, or just delete it, but the only way to generate the file again is restarting the srt service.

We also tried to delete the content of the json file after one day of being loging, the idea was to keep the same file in the same place,  but it was not updated anymore with new stats, so again it was necesary to restart again the service.

I will appreciatte someone can help with a suggest or a command, to maybe after a certain size, or amount of lines, just to generate a new file keeping the old one or generating a new one. It is not necesary to keep the stats because as I said, we are saving every new line in another server to use it in a grafana board.

thanks in advance!!

Best!

**Comment by ethouris** [comment]
I understand you are using `srt-live-transmit` application for this because this one has an ability to generate the stats in json format. If you don't use standard output for anything (like `file://con` as output in order to use the pipeline), then you can use the `-s` option without specifying the stats filename and the stats will be printed to the standard output (additionally `-q` option may be necessary to avoid any garbage).

Alternatively I'd encourage you to modify the application for your purpose. Note that this application isn't meant for production, but rather for demonstration and testing for the users, hence it has some limited capabilities towards what could be done with SRT.

**Comment by GabTlc** [comment]
Hi Ethouris, first of all, thanks for your prompt answer!

Its correct, I´m using the srt-live-transmit app with this commands to save the stats in a jason file **-pf json -statsout home/srt/stats.json -s 1000** and this is the file that we are accessing constantly to extract the metrics, but we can´r modify or regenerate automatically.

According what you are saying, I undestand that if we don´t specify a filename it will be printed in the standard output, sorry but here is where I´m lost, what do you mean with std output?

by the way, this is just a POC system, that we want to have available for testing pourpuse and of course to improve whatever we can, the problem is that we don´t have expertise coding so it is not so easy for us to modify the apps.

thanks again for your time.

reggards.
