### ISSUE TITLE
SRT Interoperability issue

### ISSUE THREAD

**Issue by dduquesne** [Haivision/srt#252]
Hello,

We have an interoperability issue regarding SRT.
I am used to work with different 1.2 implementation provided by some manufacturers.
These implementations are based on stransmit.
I have also my own implementation based on stransmit.
We already made strong interop test in the past to be sure that all these implementation work toogether. We ended up with something stable :
Me 1.2 <--> Me 1.2 : OK
Me 1.2 <--> Manufacturer A 1.2 : OK
Me 1.2 <--> Manufacturer B 1.2 : OK

On my side, i recently moved my implementation to 1.3 (Dev branch). 
Full 1.3 TX worked fine using this implementation on standard x86-64 servers.
But my interop tests with 1.2 manufacturers failled.
To summarize the result, we detected that the encryption is now an issue.
We were used to work with a strong 32B key. It was working fine with manufacturer A & B. Now, after many tests using 1.3 on our side, we discovered that :
Me 1.3 <--> Me 1.3 : OK
Me 1.3 <--> Manufacturer A 1.2 : KO. But OK if we disable encryption.
Me 1.3 <--> Manufacturer B 1.2 : KO. But OK if  we use 16B key instead of 32B.

Is there any change at the cipher level which can explain these results ?
Does the complexity of the SRT encryption increase with this new version ?
I don't have any relevant logs for the moment but i can try to get something.
In fact the issue is visual. The TX occures and the manufacturers boxes decode it but we can see artifacts on the screen (Looking to buffer underflow). This issue disapears if we reduce or desactivate encryption.

Any help is welcome :)

**Comment by ethouris** [comment]
This definitely is a regression; it is expected that older and newer version cooperate without problems.

What has changed in 1.3 around encryption is that since 1.3 the bidirectional live traffic is also possible over one connection, and this has affected encryption such a way that now it's the caller that creates the SEK and initiates the encryption key exchange (in 1.2 and earlier, it was the party that was declared as sender). But this happens only if both clients are >=1.3, otherwise the 1.3 version should do it the same, old way. I need to do more tests around this.

**Comment by ethouris** [comment]
Ok, I made some tests with the versions I have, using versions 1.2, 1.3 and earlier 1.1.3 version (pre-opening). There are some artifact problems with encryption and very high bitrate, but they seem to be simply due to reaching the performance limit of the source streamer device - SRT receiver (stransmit) reports no problems. When I made the device stream pure UDP, then transmitted this stream by stransmit between two machines - no problems were reported anywhere.

There's something specific in your configuration and we have to figure this out. This may be even the problem of reaching the performance limit, but even if so, we need at least to know where these limits might be.

Please tell me first, how you run your configuration and the parameters of the stream (actually bitrate is the most important information). And, as usual, make sure you are using the latest version (we had some performance issues in 1.3 due to changes in the logging system, we believe they are gone now).

**Comment by ethouris** [comment]
Ok, I made some tests with the versions I have, using versions 1.2, 1.3 and earlier 1.1.3 version (pre-opening). I tried various version combinations, and also higher bitrates and I have observed no problems that would be seen on the transport side.

There's something specific in your configuration and we have to figure this out. This may be even the problem of reaching the performance limit, but even if so, we need at least to know where these limits might be.

Please tell me first, how you run your configuration and the parameters of the stream (actually bitrate is the most important information). And, as usual, make sure you are using the latest version (we had some performance issues in 1.3 due to changes in the logging system, we believe they are gone now).

**Comment by dduquesne** [comment]
Thank for your reply ethouris
I was working with the commit below :
Commits on Jan 11, 2018
Fixed ThreadName constructor to restore old thread name in destructor.
jeandube committed 18 days ago
Added CMake options to map THREADHCHECK macros to application's functions.
Synched THREADCHECK and prctl thread names.

I just have updated my working directory with the latest version and run a first test.
Magic ! It seems that the issue disapeared.
I can see that cpu load is now lower and more stable.
I need to run my full test book but first result is promising.

**Comment by ethouris** [comment]
Especially this CPU low load sounds very good for me. :)

**Comment by dduquesne** [comment]
We made new test sessions with our 1.1 partners and i we saw that this issue disappeared since i have updated my 1.3 working dir to the latest commit. It seems that this log issue in 1.3 was the source of the problem.

**Comment by ethouris** [comment]
I've made a change in the logging system, which splits logging into "normal" and "heavy", whereas all debug logs undergo "heavy" category. The logging system was initially different, so I thought it should be enough to turn it off at compile time, but this was wrong, as even a condition check, whether particular log shall be displayed or not, was a burden, not even mentioning the argument expression evaluation. The error/warning/note logs are not that tough because they are displayed relatively rarely, but debug logs put a really heavy burden. So now by default the logs are turned on by default, but without heavy logging. Turning off logging makes the logging instruction simply evaluate to completely nothing.
