### ISSUE TITLE
[BUG] accepted socket reuse old passphrase

### ISSUE THREAD

**Issue by jeandube** [Haivision/srt#2582]
Listener set streamID-based passphrase in listen callback function.
Listener accepted 2 streams with different passphrase on same port.
Passphrase for one of the stream configuration is cleared and CONNECTED stream is disconnected.
Reconnecting caller (same old passphrase) will be accepted an decrypted properly.
The listening socket passphrase is a 3rd different passphrase. 

It is assumed that the passphrase set in the listen callback is kept and reused.
A tested workaround in the app is to force-set an empty passphrase in the listen callback when none is configured.
Listen_callback-set passphrase shall not be preserved since in the listening socket object since reconnection will always recall the listen_callback that will reset the configured passphrase.
This should at least be documented.

**Comment by ethouris** [comment]
Wait a moment. The listener callback gets the socket that is the ACCEPTED socket and you are setting the passphrase on this socket only. The listener socket should be completely unaffected. The accepted socket lives between the moment when it is created, then it is passed to the callback, then the conclusion handshake is interpreted and the passphrase checked, then in use until broken and closed. There's simply no place where this passphrase could be stored and survive destruction of the accepted socket - or, at least, if there is one, it's absolutely not expected.

Can you submit the repro procedure for this? Just the steps, the code is not that important.

**Comment by jeandube** [comment]
@ethouris 
Calling peer setup:
call SUT:9944 (System Under Test), STREAMID=sidA, PASSPHRASE=passphraseA
recall upon disconnect

SUT setup:
Listen on 9944, passphrase00,  default ENFORCEDENCRYPTION
listen_callback on 9944:
- Accept StreamID=sidA, set PASSPHRASE=passphraseA,
- Accept StreamID=sidB, set PASSPHRASE=passphraseB

When A is CONNECTED:
User (WCI) clears stream A passphrase and apply
- destroy streamA (srt_close()), keep listener which is shared with B
- Listen_callback on 9944 would now accept StreamID=sidA without setting a passphrase.
- Calling peer reconnects SECURED and SUT decrypt stream.

Workaround applied to have expected behavior (reject caller):
- Accept StreamID=sidA, set PASSPHRASE=""

**Comment by ethouris** [comment]
So, again, not sure if I understood correctly.

You setup a listener socket on 9944, set it "passphrase00" as SRTO_PASSPHRASE.

The listener callback on the reported sidA sets the accepted socket (the socket passed in the callback function parameters) passphraseA, then simiarly for reported sidB - passphraseB. Both are connected now.

Then stream A is closed, while stream B continues.

Then you connect again with a caller requesting sidA as a user, but without setting a passphrase.

The connection is established, even though for sidA the listener callback sets the "passphraseA" as a password, while ENFORCEDENCRYPTION is default value true.

If that above is correct, then I have questions:

1. What's the value of the ENFORCEDENCRYPTION option on the accepted socket in all cases inside the listener callback (field: `m_config.bEnforcedEnc`)?
2. What happens if you try to connect sidA without password in this environment as a very first connection?
3. In that repeated connection for sidA, what is the value of `m_config.CryptoSecret.str` in the socket passed to the listener callback?
(in the test code you may try to display contents in the `CUDT::runAcceptHook` function, right before the `CALLBACK_CALL` phrase).

And most important: do you set, under any kind of circumstances, the passphrase on the listener callback, and in which ones?

**Comment by ethouris** [comment]
So, first - random password might shed some light during testing, but if you are using a listener callback, you can simply reject the call from there (when a user wasn't set correctly by the caller), regardless of what passphrase is currently set as derived from the listener.

The most important question is whether you have configured any passphrase on the listener. And the ENFORCEDENCRYPTION option was interesting for me as a state at this moment - whether expected or not.
