### ISSUE TITLE
[BUG] undeclared identifier 'pthread_condattr_setclock'

### ISSUE THREAD

**Issue by yoobi** [Haivision/srt#2612]
**Describe the bug**
I'm using [srtdroid](https://github.com/ThibaultBee/srtdroid) which in turn use your library. I've tried running it using Android API 19 but it crash with the following stacktrace:
```
  srtcore/sync_posix.cpp:306:5: error: use of undeclared identifier 'pthread_condattr_setclock'; did you mean 'pthread_condattr_setpshared'?
      pthread_condattr_setclock(&CondAttribs, CLOCK_MONOTONIC);
      ^~~~~~~~~~~~~~~~~~~~~~~~~
      pthread_condattr_setpshared
  /usr/local/lib/android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/pthread.h:137:5: note: 'pthread_condattr_setpshared' declared here
  int pthread_condattr_setpshared(pthread_condattr_t* __attr, int __shared);
      ^
```

**To Reproduce**
https://github.com/ThibaultBee/srtdroid/issues/30 see the https://github.com/ThibaultBee/srtdroid/actions/runs/3918612479/jobs/6699102675

**Expected behavior**
Not to crash

**Desktop (please provide the following information):**
 - OS: Android API 19
 - SRT Version / commit ID: version 1.5.1

**Comment by ethouris** [comment]
Might be that this version of SDK doesn't support this feature. Not sure how it can be autodetected. You can try with adding `-DENABLE_STDCXX_SYNC=ON` for cmake.

**Comment by yoobi** [comment]
I'm using `srtdroid` which in turns use your lib, the CMAKE is the following: https://github.com/ThibaultBee/srtdroid/blob/feat/android-19-support/lib/src/main/cpp/CMakeLists.txt#L29

I'll try adding the line you mentioned and also should I change something else ?

**Comment by ethouris** [comment]
For managing the threads and time we are using a wrapper library that is implemented with the use of either POSIX primitives or the C++11 standard library. The POSIX version is default because some older compilers don't support C++11.

There's not much else I could tell you because the Android version is only unofficially supported by the community. You might find some interesting things in the android-specific documentation for SRT (in the `docs` directory).
