### ISSUE TITLE
FFMPEG+SRT how to handle listener process kill and restart

### ISSUE THREAD

**Issue by kevev** [Haivision/srt#2640]
I am using ffmpeg+SRT on sender and on listener systems. I sometimes want to kill the ffmpeg PID on the receiving system, and then start ffmpeg again. I notice that the sending ffmpeg shows an error and never recovers. Is there a way to have ffmpeg on the sender keep trying instead of just failing?

**Comment by ethouris** [comment]
Ok, if I understood correctly, you have a sending listener, which listens for a connection from the caller, but upon a break (in this case by killing the caller side) the restarted caller fails to reconnect to the listener side.

I think ffmpeg has some specific options to fix this problem. If this happens it means that likely the ffmpeg kills the listener socket once the connection is established, so after the connection is broken, there's no listener to connect to. Maybe this behavior is controlled by an option, but I don't know the details.

I found [this ticket](https://trac.ffmpeg.org/ticket/7512) in ffmpeg Trac, which seems to touch upon the exactly same problem. It was submitted by someone from us and it's 4 years old, so it might be just as well that ffmpeg has never fixed it.

To test a possible fix, you can also replace the listener side with `srt-live-transmit`, the application provided in this repository (I'm not sure how distros provide it). It can only flip between SRT and UDP or console pipeline (specified as `file://con`), but the latter gives you a possibility to link it to ffmpeg that would send the stream to the pipeline instead of SRT. This application has abilities to reestablish a broken connection and also restart listening, while data that cannot be sent over a broken connection simply fall on the floor.

**Comment by kevev** [comment]
Thank you for the response. What I am doing is sending an SRT feed using this command:

`ffmpeg.exe -hide_banner -hwaccel cuda -hwaccel_output_format cuda -f libndi_newtek -i $NDI_SRC -c:v hevc_nvenc -pix_fmt p010le -preset  p2 -bufsize 6000k -b:v 3000k -c:a aac -b:a 96k -g 60 -f mpegts srt://###.###.###.###:####?mode=caller&pkt_size=1316`

The listener uses this command:

ffmpeg -i srt://:####?mode=listener&latency=6000000&pkt_size=1316&transtype=live&smoother=live&linger=10&ffs=128000&rcvbuf=100058624 -c:v libx264 -c:a aac -b:v 6000k -bufsize 12000k -profile:v high -b:a 96k -tune animation -preset veryfast -g 60 -sc_threshold 0 -crf 15 -pix_fmt yuv420p -f flv rtmp://127.0.0.1:21936/live/stream_name

The re-encoded stream is forwarded to a local NGINX server using nginx-rtmp-module:

`exec_push /root/bin/ffmpeg -fflags discardcorrupt -i rtmp://127.0.0.1:#####/$app/$name -pix_fmt yuv420p -async 2 -vsync cfr -threads 0
        -c:v libx264 -c:a aac -b:v 256k -bufsize 512k -profile:v high -b:a 64k -vf "scale=480:trunc(ow/a/2)*2" -tune zerolatency -preset veryfast -g 60 -sc_threshold 0 -crf 23 -f flv rtmp://127.0.0.1:#####/show/$name_low
        -c:v libx264 -c:a aac -b:v 768k -bufsize 1536k -profile:v high -b:a 96k -vf "scale=720:trunc(ow/a/2)*2" -tune zerolatency -preset veryfast -g 60 -sc_threshold 0 -crf 23 -f flv rtmp://127.0.0.1:#####/show/$name_mid
        -c:v libx264 -c:a aac -b:v 1024k -bufsize 2048k -profile:v high -b:a 128k -vf "scale=960:trunc(ow/a/2)*2" -tune zerolatency -preset veryfast -g 60 -sc_threshold 0 -crf 23 -f flv rtmp://127.0.0.1:#####/show/$name_high
        -c:v libx264 -c:a aac -b:v 1920k -bufsize 3840k -profile:v high -b:a 128k -vf "scale=1280:trunc(ow/a/2)*2" -tune zerolatency -preset veryfast -g 60 -sc_threshold 0 -crf 23 -f flv rtmp://127.0.0.1:#####/show/$name_higher
        -c copy -f flv rtmp://127.0.0.1:#####/show/$name_src 2>>/var/log/ffmpeg.log;`

I then do a `pkill ffmpeg` on the listener so that I can archive the recording. This kills both ffmpeg commands on the listener server.

The sender ffmpeg command output is:

`frame=  873 fps= 30 q=19.0 size=   11192kB time=00:00:31.34 bitrate=2924.7kbits/s speed=1.07x    
frame=  888 fps= 30 q=18.0 size=   11271kB time=00:00:31.86 bitrate=2898.0kbits/s speed=1.07x    
frame=  904 fps= 30 q=18.0 size=   11463kB time=00:00:32.37 bitrate=2900.8kbits/s speed=1.07x    
frame=  919 fps= 30 q=18.0 size=   11536kB time=00:00:32.86 bitrate=2875.6kbits/s speed=1.07x    
frame=  934 fps= 30 q=17.0 size=   11585kB time=00:00:33.37 bitrate=2843.5kbits/s speed=1.07x    
frame=  949 fps= 30 q=17.0 size=   11632kB time=00:00:33.88 bitrate=2811.9kbits/s speed=1.07x    
frame=  964 fps= 30 q=17.0 size=   11856kB time=00:00:34.39 bitrate=2823.6kbits/s speed=1.07x    
frame=  979 fps= 30 q=16.0 size=   12076kB time=00:00:34.91 bitrate=2833.8kbits/s speed=1.07x    
frame=  995 fps= 30 q=17.0 size=   12268kB time=00:00:35.40 bitrate=2838.8kbits/s speed=1.06x    
frame= 1010 fps= 30 q=16.0 size=   12443kB time=00:00:35.91 bitrate=2838.4kbits/s speed=1.06x    
frame= 1025 fps= 30 q=17.0 size=   12681kB time=00:00:36.42 bitrate=2852.0kbits/s speed=1.06x    
frame= 1040 fps= 30 q=17.0 size=   12902kB time=00:00:36.93 bitrate=2861.5kbits/s speed=1.06x    
frame= 1056 fps= 30 q=17.0 size=   13078kB time=00:00:37.42 bitrate=2862.5kbits/s speed=1.06x    
frame= 1071 fps= 30 q=17.0 size=   13341kB time=00:00:37.91 bitrate=2882.2kbits/s speed=1.06x    
av_interleaved_write_frame(): I/O error
    Last message repeated 4 times
Error writing trailer of srt://157.230.176.218:####?mode=caller&pkt_size=1316: I/O error
frame= 1075 fps= 30 q=15.0 Lsize=   13362kB time=00:00:38.11 bitrate=2872.2kbits/s speed=1.06x    
video:12416kB audio:439kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 3.940049%
Error closing file srt://###.###.###.###:####?mode=caller&pkt_size=1316: I/O error
[aac @ 0000023f1b1e0540] Qavg: 340.430
Conversion failed!`

And the ffmpeg process just sits there and does not try to reconnect. Trying to make it reconnect.

**Comment by ethouris** [comment]
Well, I think this time you have reverted the caller/listener side, but no matter. You can still try to fix it the following way:

1. Use `srt-live-transmit` in the command that is **the other party** than the one you are killing.
2. If this party is sending to SRT medium, do `ffmpeg ...parameters... pipe:1 | srt-live-transmit file://con <srt-uri>`. If receiving from the SRT medium, then do `srt-live-transmit <srt-uri> file://con | `ffmpeg -i pipe:0 ...parameters...`.

If I understand correctly which command is running on this **other party** and fails to reconnect is the one on the caller side now, this should be the command:

`ffmpeg.exe -hide_banner -hwaccel cuda -hwaccel_output_format cuda -f libndi_newtek -i $NDI_SRC -c:v hevc_nvenc -pix_fmt p010le -preset  p2 -bufsize 6000k -b:v 3000k -c:a aac -b:a 96k -g 60 -f mpegts pipe:1 | srt-live-transmit file://con srt://###.###.###.###:####?mode=caller`

(note that transtype=live is a default value and `pkt_size` is named differently in this application, but still the default value for the equivalent option is also 1316 so you don't need to specify them).

If this configuration is working correctly, then it means that it's ffmpeg's problem. Still, this one you can always use as a workaround, should it work for you.

**Comment by kevev** [comment]
Is a binary available for srt-live-transmit on Windows? Or do I need to build it?

**Comment by kevev** [comment]
I was able to build Windows binaries. Now for testing.

**Comment by kevev** [comment]
Is this syntax correct? I am not able to push any video:

`
Caller:
ffmpeg.exe -hide_banner -hwaccel cuda -hwaccel_output_format cuda -f libndi_newtek -i $NDI_SRC -c:v hevc_nvenc -pix_fmt p010le -preset  p2 -bufsize 6000k -b:v 3000k -c:a aac -b:a 96k -g 60 -f mpegts pipe:1 | srt-live-transmit.exe file://con srt://###.###.###.###:####?mode=caller
Media path: 'file://con' --> 'srt://157.230.176.218:4888?mode=caller'


Listener:
/usr/local/bin/srt-live-transmit srt://:####?mode=listener file://con | /root/bin/ffmpeg -i pipe:0 -c:v libx264 -c:a aac -b:v 6000k -bufsize 12000k -profile:v high -b:a 96k -tune animation -preset veryfast -g 60 -sc_threshold 0 -crf 15 -pix_fmt yuv420p -f flv rtmp://###.###.###.###:####/live/stream1`

**Comment by ethouris** [comment]
Does the first command show any video if you replace the command after the pipe with "ffplay pipe:0" ?

You can also try this way: instead of using pipe:1/pipe:0 use udp with some local port and then `srt-live-transmit` can be set up separately to read from it or write to it (instead of file://con)  and the sender party will then send the packets as long as they are available. Actually I have no idea why you can't see any video, but some element of this pipe likely doesn't send to the next one.

Note also that local UDP on Windows happens to experience packet losses, so don't be surprised if you see scrapped video, this is only to be able to see if anything gets pushed.

**Comment by kevev** [comment]
I worked around this issue with custom log monitoring code. If specific errors are seen, or no new log entries for 10 seconds, kill ffmpeg, and restart. Thanks!

**Comment by matiaspl** [comment]
Just a comment based on my experience with libav - if you want to use just the ffmpeg command you can set a socket timeout short enough to have the ffmpeg process get an "EOF" on it's input (which results in graceful exit of the process) when there's nobody sending any stream and long enough in case of short stream dropouts. 

I tested this approach some time ago with ffmpeg and media source in OBS and it worked for me.
