### ISSUE TITLE
[FR]Add socket option to enable or disable send keepalive

### ISSUE THREAD

**Issue by xiaozhihong** [Haivision/srt#2653]
Currently `keepalive` is sent every 1 second,  the code is in https://github.com/Haivision/srt/blob/master/srtcore/core.cpp#L11312.

But it seems `keepalive` is in conflict with `peeridletimeout`.  If `pperidletimeout` is set to 2 seconds, the client may never timeout.

So can use srt socket option to enable/disable send keepalive?

**Comment by ethouris** [comment]
Excuse me but I understand nothing from it.

The keepalive is required to make the communication recent. It is being sent in case when for a time of this 1 second (not configurable AFAIR) there's no need to send any packet by any reason. This is required for the peer because if no packet has been received from the other party for the time set as SRTO_PEERIDLETIMEO, the connection is considered broken.

If you set SRTO_PEERIDLETIMEO to 2 seconds, you risk that if your keepalive packet is delayed on the network for more than 1 second towards the previous packet, your completely valid connection may be broken. Of course, if you are transmitting even in one direction, then you'll have transmission in one direction and UMSG_ACK in the opposite direction once per ~10ms, so no keepalive would be sent in any direction whatsoever.

If you turn off sending UMSG_KEEPALIVE message paackets - should that be your request - you need to have a constant sending activities at least once per minute in both directions or otherwise your connection will break due to inactivity.

**Comment by gou4shi1** [comment]
I think `peeridletimeout` is only designed for transport layer, but not application layer.

**Comment by xiaozhihong** [comment]
> Excuse me but I understand nothing from it.
> 
> The keepalive is required to make the communication recent. It is being sent in case when for a time of this 1 second (not configurable AFAIR) there's no need to send any packet by any reason. This is required for the peer because if no packet has been received from the other party for the time set as SRTO_PEERIDLETIMEO, the connection is considered broken.
> 
> If you set SRTO_PEERIDLETIMEO to 2 seconds, you risk that if your keepalive packet is delayed on the network for more than 1 second towards the previous packet, your completely valid connection may be broken. Of course, if you are transmitting even in one direction, then you'll have transmission in one direction and UMSG_ACK in the opposite direction once per ~10ms, so no keepalive would be sent in any direction whatsoever.
> 
> If you turn off sending UMSG_KEEPALIVE message paackets - should that be your request - you need to have a constant sending activities at least once per minute in both directions or otherwise your connection will break due to inactivity.

Thanks for your reply. I agree with @gou4shi1, `keepalive` and `peeridletimeout` is designed for transport layer.
I have no problem with it now.

**Comment by maxsharabayko** [comment]
There is still a possibility for a FR: to break a connection if no transmission is happening even if it is kept alive.  Although that's something an application can and probably should do.
