### ISSUE TITLE
[BUG] rendezvous with mismatched passphrase half-connects

### ISSUE THREAD

**Issue by jeandube** [Haivision/srt#2684]
SRT 1.5.2-rc.1 aarch64, live/async mode
mismatched passphrase/enforcedencryption may leave receiver app in limbo state.
case 1 (FAIL): 
sender/10.65.10.234:4002 no passphrase, enforced:false rendezvous with receiver/10.65.10.230:4002 passphrase, enforced:true

Receiver transits (EPOLL_OUT event) from CONNECTING to CONNECTED but while trying to get peer address fails with "Connection does not exist". Receiver app remains in SECURING limbo state.
Adding passphrase on sender side does not fix connection, since receiver is not CONNECTING (not knowing it has DISCONNECTED).
Possible app workaround: transit to DISCONNECT on API error.

case 2 (OK): change port to 4001
sender/10.65.10.234:4001 rendezvous 10.65.10.230:4001
If set with port 4001 instead: Initiator/responder side probably swapped.
Receiver transits (EPOLL_IN event) from CONNECTING to DISCONNECTED after 30 secs and app attempts reconnection (stays CONNECTING).
therefore: Adding passphrase on sender side permit connection establishment.

case 3 (OK): add enforcedencryption:true on sender side
sender/10.65.10.234:4001 no passphrase, enforced:true rendezvous with receiver/10.65.10.230:4002 passphrase, enforced:true
EPOLL_IN event right after connect CONNECTING->DISCONNECTED, app attempts reconnect after 5 secs.
therefore: Adding passphrase on sender side permit connection establishment.

**Comment by jeandube** [comment]
<<setting different values of enforcedencryption option on both sides may result in an undefined behavior in case of security failure.>>
Problem is: you may have no control of what the other side is setting. Specially when the option is set/unset by default without U/I knob.

**Comment by jeandube** [comment]
Added information. The side showing the issue is the one that won the cookie contest.

**Comment by ethouris** [comment]
Ok, so I retried the test and the result is:

1. The sender has exited with rejection. The sender was also RESPONDER (lost the cookie contest).
2. The receiver did the "late rejection" (broke the connection):
```
Binding rendezvous: ANY:4002 ...
Connecting to sullust:4002 ... [ASYNC] [EPOLL: 1 sockets]  connected.
Setting RCV blocking mode: false timeout=0
ENCRYPTION status: UNSECURED (SND:NOSECRET RCV:UNSECURED) PBKEYLEN=16
OPTIONS: maxbw=-1 rcvlatency=120 blocking{rcv=false snd=true} snddropdelay=0 packetfilter=
NON-BLOCKING MODE - SUB FOR [R]
EPOLL: creating eid=2 and adding @922517763 in source mode
STARTING TRANSMISSION: 'srt://sullust:4002?mode=rendezvous&blocking=no&enforcedencryption=yes&passphrase=niedlaidiotow' --> 'output.ts'
[. << ... AGAIN: - waiting for data by epoll(2)...
[Connection error reported on @922517763]
... epoll reported ready 1 sockets
 << 1316  ->  .] sent
[. << ... FAILURE
srt_recvmsg2: [2001.0] Connection was broken
STD EXCEPTION: error: srt_recvmsg2: Connection was broken
```

Important: the receiver has actually ACCEPTED the connection, but broke it immediately after being established and AFTER (interesting!) the first received packet the connection was broken.

I tried the same with `srt-live-transmit`, which works only in non-blocking mode, although it does automatic reconnection and indeed there's something weird there. Even though it retries and shows new socket IDs (so old ones were definitely closed), from the logs it turns out that it does it only because the peer has received AGREEMENT from the agent, while having not agreed actually and has received SHUTDOWN from the peer and only because of that the connection was broken. The workflow that is shown in the logs shows that there's something definitely wrong:

```
09:04:35.366482/SRT:RcvQ:w1!W:SRT.cn: processSrtMsg_KMRSP: received failure report. STATE: UNSECURED
09:04:35.366494/SRT:RcvQ:w1.N:SRT.cn: processSrtMsg_KMRSP: cmd=4(KMRSP) len=16 KmState: SND=NOSECRET RCV=UNSECURED
09:04:35.366502/SRT:RcvQ:w1*E:SRT.cn: @930994363: KMRSP failed - rejecting connection as per enforced encryption.
09:04:35.366513/SRT:RcvQ:w1 D:SRT.cn: @930994363: updateAfterSrtHandshake: HS version 5
09:04:35.366524/SRT:RcvQ:w1 D:SRT.cn: @930994363: updateAfterSrtHandshake: version=5 side=INITIATOR
09:04:35.366535/SRT:RcvQ:w1 D:SRT.cn: AFTER HS: Set Rcv TsbPd mode: delay=0.120s RCV START: 348D 17:27:31.367452 [STDY]
09:04:35.366548/SRT:RcvQ:w1 D:SRT.cn: AFTER HS: Set Snd TsbPd mode with TLPktDrop: delay=0.120s START TIME: 348D 17:27:32.991218 [STDY]
09:04:35.366559/SRT:RcvQ:w1 D:SRT.cn: @930994363: processRendezvous: COOKIES Agent/Peer: -1062042917/-1802279866 HSD:initiator STATE:connected ...
09:04:35.366571/SRT:RcvQ:w1 D:SRT.cn: @930994363: ... WILL SEND agreement without SRT HS extensions
09:04:35.366582/SRT:RcvQ:w1 D:SRT.cn: @930994363: updateAfterSrtHandshake: HS version 5
09:04:35.366592/SRT:RcvQ:w1 D:SRT.cn: @930994363: updateAfterSrtHandshake: version=5 side=INITIATOR
```

The logs say: "rejecting connection as per enforced encryption", but then... it proceeds with AGREEMENT? No, that's definitely not correct. I'll be checking it out.

**Comment by ethouris** [comment]
Ok, @jeandube if you could, please test on this branch. After providing this fix I get proper rejection state on both sides when trying with `srt-test-live`.

**Comment by jeandube** [comment]
@ethouris Early tests shows that I no longer get a CONNECTED state. so my receiver stays in reconnection mode and permit recovery upon peer password fix. 
Is the reject reason sent to peer? Locally can I get the reject reason without connect_callback? Is connect_callback usable for rendezvous?
