### ISSUE TITLE
stransmit: EOF character to sender process with wrong passphrase ends receiver process 

### ISSUE THREAD

**Issue by tbarron-xyz** [Haivision/srt#269]
Steps to reproduce:

* Terminal #1
    * `stransmit srt://:49000?passphrase=abc file://con`
* Terminal #2 
    * `stransmit file://con srt://localhost:49000` (note no passphrase; wrong passphrase also produces this behavior)
    * Press `Ctrl + D` to send an EOF character to the send
* Terminal #1
    * Observe that your stransmit process has exited

Expected behavior: Receiver process does not exit unless the sender process has the correct passphrase.

**Comment by ethouris** [comment]
I get kinda confused here.

First, AFAIK, the passphrase should have minimum 10 characters, otherwise the function setting the `SRTO_PASSPHRASE` option should return with error, which should lead your `stransmit` call to exit with error immediately. Not sure if you are observing this behavior.

Second, the current version of stransmit (alias to `srt-live-transmit`) is for live transmission only (for transmitting a file, you have `srt-file-transmit`), and with current form it interrupts when the connection is closed.

Third, when you have an application that reads from standard input running on console and you press Ctrl+D, it causes the descriptor bound to the standard input to be closed. This doesn't send any "EOF character", there's no such thing as "EOF character" at all. If you are confused by the `EOF` symbol used in the C standard library, mind that this is a value of 32-bit integer type (not of `char` type) that has -1 value, which a character (8-bit type) extended to integer (32-bit type) by filling the remaining space with zeros will never have. That's why you have the `fgetc`, `getc` and `getchar` functions returning the `int` type despite that they should return an 8-bit character. It's actually a kind-of tuple that returns you the character itself and the status simultaneously.

**Comment by tbarron-xyz** [comment]
> Third, when you have an application that reads from standard input running on console and you press Ctrl+D, it causes the descriptor bound to the standard input to be closed. This doesn't send any "EOF character", there's no such thing as "EOF character" at all. If you are confused by the EOF symbol used in the C standard library, mind that this is a value of 32-bit integer type (not of char type) that has -1 value, which a character (8-bit type) extended to integer (32-bit type) by filling the remaining space with zeros will never have. That's why you have the fgetc, getc and getchar functions returning the int type despite that they should return an 8-bit character. It's actually a kind-of tuple that returns you the character itself and the status simultaneously.

OK, thanks for the info. Didn't know.

> First, AFAIK, the passphrase should have minimum 10 characters, otherwise the function setting the SRTO_PASSPHRASE option should return with error, which should lead your stransmit call to exit with error immediately. Not sure if you are observing this behavior. 

Not observing this behavior. We have gotten working streams with six character passphrases (ubuntu amd64, built from https://github.com/Haivision/srt/commit/9623235837cbfbc6554466253545d46ec493f9e1 ).

> Second, the current version of stransmit (alias to srt-live-transmit) is for live transmission only (for transmitting a file, you have srt-file-transmit), and with current form it interrupts when the connection is closed.

Is this the intended behavior even in the case where the sender and receiver processes have different passphrases? Our plan was to have a machine in the public cloud with one instance of `stransmit srt://:port?timeout=-1&passphrase=xxx file://con` running with no senders sending data for potentially hours. A malicious entity that knew the IP address and SRT port range of our servers could kill any stransmit receiver (with no currently connected client - see below) by pointing an stransmit sender process with the wrong passphrase at every port on our server.

Or the malicious entity could just connect to our stransmit receiver with the wrong passphrase, and instead of Ctrl+D just idle and not send anything, which (just tested) prevents a sender with the correct passphrase from sending data.
* Terminal 1
    * `stransmit "srt://:49000?timeout=-1&passphrase=carlsagantheman" file://con`
* Terminal 2 (wrong passphrase)
    * `stransmit file://con srt://localhost:49000?passphrase=NotMyPassphrase`
* Terminal 3 (correct passphrase)
    * `ffmpeg -f lavfi -i life=s=60x60 -vframes 500 -f mpegts - | stransmit file://con srt://localhost:49000?passphrase=carlsagantheman`
    * Observe that the process instantly exits and that no data came out of Terminal 1's receiver process

I would naively expect that the Terminal 2 command `stransmit file://con srt://localhost:49000?passphrase=NotMyPassphrase` would fail to connect and immediately exit.

**Comment by ethouris** [comment]
The stransmit application has grown up initially as a testing tool only. We are working currently on providing the stransmit application that is more suitable for users, and e.g. supports reconnecting and can be reliably interrupted. Note that the most "fresh" version is in `dev` branch, although we plan to merge it back to `master` soon.

The older version did not reject the connection on wrong passphrase because of the old handshake implementation, which actually did the connection handshake the old UDT-derived method, and any SRT extended things (which includes latency exchange and encryption) were done after the connection is established. The newest version contains the "integrated handshake", so the processing of encryption things are in the handshake, so error in this process causes connection to be rejected. Both sides must be version 1.3.0 at least, otherwise the process runs the old way. The SRTO_MINVERSION socket option can be used to reject connection when the peer's version is older than given one.

**Comment by thomasbarronchurchill** [comment]
After upgrading to 1.3.0 (built from https://github.com/Haivision/srt/commit/d98c9d20c67f3f61029daa9ea0b2fe1d1256d803) we still observe the following behavior: a sender with the wrong passphrase can prevent a receiver from accepting a sender with the correct passphrase if the wrong passphrase connects first.

* Terminal #1
  * `stransmit "srt://:49000?timeout=-1&passphrase=carlsagantheman" file://con`
* Terminal #2 (wrong passphrase)
  * `ffmpeg -re -f lavfi -i life=s=60x60 -vframes 5000 -f mpegts - | stransmit file://con "srt://localhost:49000?passphrase=NotMyPassphrase"`
  * Terminal #2 stays open and does not immediately disconnect
  * Terminal #1 outputs "Accepted SRT source connection" (but no video output)
* Terminal #3 (correct passphrase)
  * (while above command is still executing) `ffmpeg -re -f lavfi -i life=s=60x60 -vframes 5000 -f mpegts - | stransmit file://con "srt://localhost:49000?passphrase=carlsagantheman"`
  * Terminal #1 does not output "Accepted SRT source connection" and does not output video
* (Optional step) Terminal #2 
  * `Ctrl+C` to end process
  * Terminal #1 outputs "SRT source disconnected", "Accepted SRT source connection", begins outputting video from Terminal #3

**Comment by ethouris** [comment]
Please retest with 1.3.3. There have been developed some test cases that embrace the above cases and they all pass.

Note that this version contains already the new option (`SRTO_STRICTENC`, to be renamed to `SRTO_ENFORCEDENCRYPTION`), which is on by default, and causes rejection on wrong password.
