### ISSUE TITLE
Why can't we change the FEC matrix rows/cols values when srt is running

### ISSUE THREAD

**Issue by yxungh** [Haivision/srt#2695]
Hello, everyone！
I want to judge the network condition to dynamically adjust the FEC redundancy.
I use a direct approach that changes the FEC redundancy packet size by changing the FEC matrix size while the program is running.
by resetting snd.row, snd.cols, rcv.colq, rcv.rowq[0], and rcv.cell/rcv.cell_base ..., but it gave fatal errors.

`SRT:SndQ:w1!!FATAL!!:SRT.pf: FEC:feedSource:  base = 1299317106 packet.getSeqNo = 1299317108 baseoff = 2 vert_gx = 2 vert_base = 1299317097 vert_off = 11 sizeRow = 15 sizeCol = 5 vert_off % sizeRow() = 11`

Or just disconnect

```
SRT:RcvQ:w1 D:SRT.cn: worker_ProcessAddressedPacket: resending to QUEUED socket @997345117
SRT:RcvQ:w1 D:SRT.cn: RID: NO CONNECTOR FOR ADR:36.111.36.147:14866 while looking for  AGENT @997345117 (0 connectors total)
SRT:RcvQ:w1 D:SRT.cn: AsyncOrRND: no sockets expect socket 997345117 from 36.111.36.147:14866 - POSSIBLE ATTACK, ignore packet
```

Why can't we change the FEC matrix rows/cols values when srt is running?

**Comment by ethouris** [comment]
The configuration is agreed upon during connection and the internal structures for factoring and interpreting FEC are intended to work with the fixed configuration. There's also packet history length and the expected order at the receiver side (there's some obvious overlapping between the already sent packets and packets to be sent in regard of the FEC control packet). That's not even possible to implement any smooth switching between packet size because the FEC control packet doesn't have the information for which packets it's created - only horizontal/vertical flag and the sequence number that begins the group, rest of the information results from the configuration.

To achieve this the only way would be to completely stop sending, sending reconfiguration information that would be about to start since some next given sequence number.

You can achieve the same result by establishing a new connection and closing the old one (you can also bind the caller side to a port explicitly to make sure you are using the exactly same UDP link). Of course, you'd have to handle somehow the transition.

**Comment by yxungh** [comment]
> The configuration is agreed upon during connection and the internal structures for factoring and interpreting FEC are intended to work with the fixed configuration. There's also packet history length and the expected order at the receiver side (there's some obvious overlapping between the already sent packets and packets to be sent in regard of the FEC control packet). 

@ethouris Thank you for your reply!
During the handshake, information such as rows, cols, arq, layout, and sequence number was exchanged. I understand.
I reset all of this information, first by resetting the client, and then by notifying the server via a custom control message. There may be an overlap for a while, but won't it go away after a while? (or the overlap will cause all subsequent packets to be unrecoverable, and the error will always be there), which is something I don't understand.
It is also important to note that the FEC control packet only records the XOR of the data packets, and does not affect the data packets. The impact is that FEC cannot recover the lost data packets.

**Comment by ethouris** [comment]
I know how it works because I have implemented it ;)

The problem here is the history - in order to be able to recover one lost packet in a group, you need to keep the history of all packets in the group. The FEC control packet contains the XOR value of all packets in the group, that's true, but to recover you need to know which packets belong to the group (it doesn't save the packet contents, of course, only the incremental XOR value, but still it must know prematurely from which packets it was made). If you want to change the FEC parameters, everything must be reset at this moment, all internal data must be restored to the state after connection and start afresh.

If you want to experiment further with this (which needs unfortunately some code modification), you may try to use the socket groups of type BROADCAST. You can start transmitting having only one group member in the beginning, and then add a new connection to the group, even over the same link. The problem is that the code doesn't allow all options to be set on individual member sockets, and SRTO_PACKETFILTER isn't one of them, so you'd have to modify the `SRT_SocketOptionObject::add` function in `socketconfig.cpp` file. Then the applcation, in case when it wants to change parameters, establishes a new connection within the group and once it is up closes the old one. This may cost you a small temporary packet burst, but as long as the network withstands the bitrate, it will be smooth.

**Comment by yxungh** [comment]
> The problem here is the history - in order to be able to recover one lost packet in a group, you need to keep the history of all packets in the group. The FEC control packet contains the XOR value of all packets in the group, that's true, but to recover you need to know which packets belong to the group (it doesn't save the packet contents, of course, only the incremental XOR value, but still it must know prematurely from which packets it was made). If you want to change the FEC parameters, everything must be reset at this moment, all internal data must be restored to the state after connection and start afresh.

@ethouris Thanks for the reply
I can understand that if I forcibly change the FEC parameter, the consequence is that if the packet is lost in the current group, it will not be recovered. The change is not smooth, which is definitely not feasible for SRT, but if I can accept this phenomenon, this solution is feasible.

> If you want to experiment further with this (which needs unfortunately some code modification), you may try to use the socket groups of type BROADCAST. You can start transmitting having only one group member in the beginning, and then add a new connection to the group, even over the same link. The problem is that the code doesn't allow all options to be set on individual member sockets, and SRTO_PACKETFILTER isn't one of them, so you'd have to modify the `SRT_SocketOptionObject::add` function in `socketconfig.cpp` file. Then the applcation, in case when it wants to change parameters, establishes a new connection within the group and once it is up closes the old one. This may cost you a small temporary packet burst, but as long as the network withstands the bitrate, it will be smooth.

Thanks for a good idea, but I haven't enabled `ENABLE_EXPERIMENTAL_BONDING` and I don't know much about it. Can I add a new connection inside SRT without relying on the call from the upper layer?

**Comment by ethouris** [comment]
It's `ENABLE_BONDING` now, it's no longer experimental.

The broadcast group type is intended to simply send the same stream over multiple links simultaneously. So normally you might like to establish two links so that if one gets broken, the other remains and continues. Of course broken links must be reestablished by the application, but that's because this solution is fully flexible - you can add a new link to the group at any time, also during transmission, as well as close an existing member socket, which will kill particular member link. This can be then as well used for establishing at first just one link in the group, and then add a new one, if you, for example, would like to switch to a different route.

**Comment by yxungh** [comment]
> It's `ENABLE_BONDING` now, it's no longer experimental.
> 
> The broadcast group type is intended to simply send the same stream over multiple links simultaneously. So normally you might like to establish two links so that if one gets broken, the other remains and continues. Of course broken links must be reestablished by the application, but that's because this solution is fully flexible - you can add a new link to the group at any time, also during transmission, as well as close an existing member socket, which will kill particular member link. This can be then as well used for establishing at first just one link in the group, and then add a new one, if you, for example, would like to switch to a different route.

Thanks. I'm going to try this solution.

**Comment by ethouris** [comment]
No, groups are intended for redundancy only - that is, always there's a single stream of data, just may utilize multiple links as needed.

Note though that in SRT you can utilize a single "UDP link" for multiple connections effectively. The listener side uses always one port for all its "child sockets" accepted off this listener. On the caller side you can also achieve this by explicitly binding the socket before connection to a certain port. Sharing the port between SRT sockets (which actually shares the queues and the internally used UDP socket) is by default possible, it's controlled by `SRTO_REUSEADDR` option. The `srt-test-multiplex` testing application is using this feature.

**Comment by yxungh** [comment]
close it
