### ISSUE TITLE
How to set the maximum number of retransmissions?

### ISSUE THREAD

**Issue by yuchengmao** [Haivision/srt#2763]
How to set the maximum number of retransmissions?

**Comment by ethouris** [comment]
There is no such setting. There are two possibilities of how and whether the retransmissions are repeated:

1. If SRTO_NAKREPORT option is on, retransmission request is repeated, if it didn't result in a successful retransmission in a specifically calculated time based on RTT (that is, repeating happens when the retransmitted packet was considered lost again). Otherwise this repeating is done only if ACK period passed and new packets are still coming, while the decision for retransmission is undertaken autonomously by the sender side ("TCP style").
2. If SRTO_TLPKTDROP option is on (required SRTO_TSBPDMODE=1), retransmissions are given up on the receiver side (no more requests are sent) when the packets already waiting in the buffer are ready to deliver basing on their arrival time and latency. Also the sender side may also stop retransmitting the lost packet if it calculated that it won't reach the receiver before it decides to drop this packet. This mechanism can be controlled on the sender side using SRTO_SNDDROPDELAY option. Otherwise retransmissions can be repeated until the lost packet is recovered, as long as the connection is running. 

With the default settings for live mode, SRTO_NAKREPORT=1 SRTO_TLPKTDROP=1 SRTO_TSBPDMODE=1.

In file mode, all these three options are set to 0.

**Comment by maxsharabayko** [comment]
Related FRs: #2701, #591.

**Comment by yuchengmao** [comment]
Got it, thanks for the reply!

**Comment by maxsharabayko** [comment]
Closing this in favor of the remaining FRs #2701 and #591, and PR  #2714
