### ISSUE TITLE
Question: stransmit and IPv4 fragmentation

### ISSUE THREAD

**Issue by leffe123** [Haivision/srt#280]
Hello everyone!
First of all thank you for the valuable work on this project (loss rate recovery of this algorithm is pretty impressive!).

To my question:
**Is there a possibility to use IPv4 fragmentation with this algorithm?** 

I have tested to send a UDP stream that includes a fragmented datagrams every 16th message through stransmit with the following two commands;
Source: `stransmit udp://:7777 srt://192.168.20.164:7778 -s:100 -r:100`
Sink: `stransmit srt://:7778 udp://192.168.97.6:11000 -s:100 -r:100`

Unfortunately the UDP stream will lose the fragmentation flags and offsets when it gets sent from SRT -> UDP again.

Thank you,
Leffe

**Comment by ethouris** [comment]
As long as I understand, the packet fragmentation and reassembly happen on the way between two endpoints. Therefore I believe that even if you ran the above stransmit commands with `udp` (not `srt`) in between, you'll get exactly the same (beside the fact that packets between two stransmit commands will not be recovered on loss).

This reassembly happens at the UDP level and probably SRT has even no chance to see it. I think there's nothing that SRT can do about it, although there could be multiple ways to achieve what you need, and some of them might be done by SRT.

As to what I know, IP fragmentation happens due to rules of routing packets on a specific routing pathway; a user can have little advantage of it (except that it slightly decreases the chance to drop the packet), and the whole process of fragmentation and reassembly should be "transparent" for a user.
