### ISSUE TITLE
Proper Usage For One-to-Many Streaming

### ISSUE THREAD

**Issue by BananaHemic** [Haivision/srt#281]
I currently have a server application that receives an MPEG-TS stream over SRT and then re-broadcasts that stream to a medium (<100) number of viewers over SRT.

Right now I have left blocking mode enabled and I just send the data to each client in a loop using srt_sendmsg2. Is this a proper configuration? I worry that if blocking mode is left enabled, a single client with a poor connection will cause all other viewers to drop frames. However, from testing I know that if I set blocking mode to disabled, then the client is likely to miss frames (I believe because the I-frame has a spike of corresponding packets, some of which are overwritten).

**Comment by ethouris** [comment]
It doesn't look that bad as you say, but still, you have take several things into consideration.

The `srt_sendmsg`* sending functions schedule the packet for sending. This packet is stored into the sending buffer. The sending thread picks them up and sends them using `::sendmsg`, although they are not removed from the sending buffer until the receiver party ACKs them. There's no specific delay for sending them, although the system facilities have also their buffer, and when it is full, the `::sendmsg` will fail (that failure is actually ignored; when it happens, the receiver party will simply not ACK up to this number). The blocking of `srt_sendmsg` will actually happen only in case when the sending buffer gets full, and this may still happen, of course, when the sending over UDP gets too slow, so the packets are not being removed from the sending buffer.

I'm not sure how likely it is to happen that the sending is slowed down when the network can't pass the packets through. AFAIR this may only happen on the local machine, when the first-shot router can't accept sent packets that fast, but once the first router receives them, they are "in the network", so worst case scenario, they will be dropped.

Although if by some reason `srt_sendmsg` may block, you can safely setup the socket as nonblocked for sending (`SRTO_SNDSYN`), just be prepared to handle an EAGAIN-kind of error (`SRT_EASYNCSND` in this case). In your case you probably want to ignore it. You may also experiment with sending timeout (`SRTO_SNDTIMEO`), but this may require you to know the exact time gap between the received packets split into the number of clients and wait only up to this time, so it may be harder in practice.

Just be careful because if you don't send packets to clients connected over different networks, you have simply one system queue for packets to be sent to the nearest router, and when this one gets choked causing the packet unable to be sent to one of the clients, it will choke for all other clients either.
