### ISSUE TITLE
[BUG] SRT_REJ_BADSECRET vs. listen_callback reason

### ISSUE THREAD

**Issue by jeandube** [Haivision/srt#2925]
The reject reason returned by the listen_callback function of a listener is ignored if a encryption is involved.
A listener filtering incoming call based on streamID may reject without setting a configured passphrase.
A listener accepting multiple connections for different StreamID may set a different passphrase for each to-be accepted socket.
If the listener socket itself has a random passphrase the peer will receive SRT_REJ_BADSECRET instead of SRT_REJX_UNACCEPTABLE returned by the listen_callback function, which is misleading to diagnose the connection problem on the peer side.

**Comment by ethouris** [comment]
Wait, I need some more reprox details.

I think I can see where the problem is. The code that was catching the case of the failed encryption process was done earlier than the code for custom rejection code handling and likely it overrides the already set code. I think I know how to fix it, but I need to be able to reproduce it myself. So, it's enough to have it when you have a custom listener callback handler and engage the connection as encrypted?

**Comment by jeandube** [comment]
@ethouris From memory: listener with passphrase and enforced encryption receives an call (encryption ON, bad passphrase) and a streamID to be rejected by listen_callback_fn(). rejection code returned to caller is not the one returned by listen_callback_fn()

**Comment by jeandube** [comment]
I could not reproduce this issue with custom-release/1.5.3a.
