### ISSUE TITLE
How is this warning caused and can it be ignored?

### ISSUE THREAD

**Issue by mycrl** [Haivision/srt#2956]
```
W:SRT.br: CRcvBuffer.readMessage(): nothing to read. Ignored isRcvDataReady() result?
```

Does this warning occur when reading data? My reading process is as follows:

```
srt_getsockstate == SRT_SOCKSTATUS::SRTS_CONNECTED
srt_recv
```

Every time before reading data, I check the status of the socket. Am I doing this wrong? I found that this warning will appear when the socket is disconnected at the remote end.

Does this warning have no impact on normal operation? Although I haven't found any impact yet, I would like to ask developers familiar with the srt kernel to confirm this issue.

Thanks!

**Comment by ethouris** [comment]
Being connected doesn't simultaneously mean that there are any data ready for extraction.

This warning is because you are calling one of `srt_recv*` function in non-blocking mode without prior checking that there are data ready for reception. You should either use blocking mode or call this function only after checking the read-ready flag (SRT_EPOLL_IN) is set in the epoll ID subscribed to this socket (you should create one yourself and subscribe to this socket).

**Comment by mycrl** [comment]
> Being connected doesn't simultaneously mean that there are any data ready for extraction.
> 
> This warning is because you are calling one of `srt_recv*` function in non-blocking mode without prior checking that there are data ready for reception. You should either use blocking mode or call this function only after checking the read-ready flag (SRT_EPOLL_IN) is set in the epoll ID subscribed to this socket (you should create one yourself and subscribe to this socket).

Thanks you!
