### ISSUE TITLE
Bitrate control to prevent socket disconnection

### ISSUE THREAD

**Issue by sinais54** [Haivision/srt#3045]
hello
I use srt-live-transmit to send a live video to an SRT relay server on a VPS.
My method of use is as follows: using ffmpeg, I take the video from the camera and after setting the bitrate, I send it to srt-live-transmit with UDP to be sent to the server.
The bandwidth of the network I use is low and fluctuates a lot, and its upload speed varies between 5Mbps and 0.2Mbps. When I increase the bitrate, the socket connection between vps and srt-live-transmit drops after a few seconds.
I think that this happens because of the decrease in network bandwidth and as a result, the bitrate value is higher than the bandwidth capacity.
My idea is to use the parameters in the srt-live-transmit logs to notice the bandwidth reduction and reduce the bitrate in ffmpeg before disconnecting.
Is such a thing possible? If so, how do I know when it's time to change the bitrate?

**Comment by ethouris** [comment]
It is not possible first of all because the times when sending packets are decided by the application. SRT doesn't regulate anything time-related here because this must be correlated with the timestamps in the live stream, of which SRT has no idea. All you can count on from SRT are the running statistics that you can read to have idea of what is going on on the link. If you need that your application temporarily reduce the bitrate, these statistics can hint you the necessity of doing it.

See statistics such as `pktFlightSize`, `pktFlowWindow` and `byteAvailSndBuf` (or better `pktSndBuf` if you know the size of the sender buffer expressed in packets).

**Comment by sinais54** [comment]
Thank you very much for your good and timely reply.
I apologize for this question, but I am a beginner in c++. What should I do if I want to print the parameters pktFlightSize, pktFlowWindow and byteAvailSndBuf in the console of the srt-live-transmit program? Which class or part of the code should I change?

**Comment by sinais54** [comment]
Thank you very much for your good and timely reply.
I use -pf:csv -s 1000 in srt-live-transmit, but the logs are displayed every 10 seconds. Shouldn't they be displayed every 1 second?

**Comment by sinais54** [comment]
According to the logs I posted above, could you elaborate on how to use pktSndBuf to achieve what I want?

**Comment by ethouris** [comment]
`pktSndBuf` shows you the number of packet units in the sender buffer. Note that in the live mode the use of the sender buffer is kinda specific (in comparison, for example, to file transmission, where you store the buffer full in the beginning and then sending is done as long as the link allows).

In the live mode you have the sender buffer split (logically) into two sections:

* SCHEDULED packets: packets that were scheduled by calling the `srt_send*` function, but they still wait for being transmitted even the firsttime
* HISTORY packets: packets that have been already sent at least once, just the ACK for these packets didn't come yet, so they remain for the needs of prospective retransmission

In live mode normally you should have at most 2 packets in the SCHEDULED section. More you can have only in case when you have bandwidth limitations applied and packets have to wait longer for a green light.

How much you should have in the HISTORY section, depends on the current RTT, but you can measure it at the time when you observe no lost packets - in which case ACK should come always for the very last packet received at the moment when the ACK is sent, so this way the HISTORY section represents packets in flight. This should be the tolerable size of the buffer.

If the size of the buffer grows enormously above this value, and simultaneously the number of lost packets increases, this is a signal that your link's capacity is currently too small to handle the signal at the current bitrate and it must be then quickly reduced.

**Comment by ethouris** [comment]
Ah this logging per socket ID - no, this isn't possible, but then if you are using only one SRT connection in the application this shouldn't matter. Note that not every part of the code even KNOWS the socket ID being used because SRT contains a special kind of object that functions as a wrapper over the UDP socket (called "multiplexer"), which allows the facilities using the UDP socket to be shared between SRT sockets (so that you can use a single UDP link to send multiple streams at a time).

**Comment by sinais54** [comment]
Thank you for your good explanation
