### ISSUE TITLE
Simulated multicast

### ISSUE THREAD

**Issue by tiagoliveira9** [Haivision/srt#309]
Hi,

In an SDN environment, I want to duplicate a stream when a second client wants to see the same stream (MPEG-DASH). Therefore two questions emerge:
- Is there any know implementation of NGINX/SRT/DASH? 
- Is SRT prepared for stream duplication?

**Comment by ethouris** [comment]
When you have the stream sender configured as a listener, you should be able to connect multiple receivers and receive the same stream by both simultaneously. I don't remember whether the current version of stransmit supports this, but at least you can do it in your application. Of course, the application should simply send each subsequent packet over every socket that represents an active connection.

Not sure what exactly feature you need from nginx. For encryption you have a passphrase setting - although it can only be just one passphrase for everyone, which is set in advance on the listener, then the same passphrase must be used by callers. For any authentication of type user/password or certificate-based, probably some higher level protocol would have to be defined.

**Comment by tiagoliveira9** [comment]
I talked about NGINX because my testbed is working with NGINX, serving MPEG-dash files. 
When you talk about Stransmit, you talk about stream duplication from the server right? The objective here is for an SDN-enabled switch to detect a second client (or more) requesting the same linear video (tv channel) and duplicate the stream on the switch saving bandwidth/requests on the origin server. But SRT for what I understand is session-like protocol, one-to-one. Therefore a raw stream duplication cannot be done using SRT right? 
Thanks for the insight.

**Comment by ethouris** [comment]
Well, at least when you use a second connection to the listener, you should receive the same data and as long as your application isn't lingering, this should be even synchronized in time. You can't recognize the places in the stream when they are at the same exactly position, however, any other than just trying to recognize the packet by data comparison.

**Comment by tiagoliveira9** [comment]
But that second connection to the listener is another "SRT session" but with the same stream? Because if I duplicate the stream on the switch but the stream packets are attached to a session... it's impossible for the second client to receive the stream well.

**Comment by ethouris** [comment]
The session term in case of SRT is exactly the same as in TCP. You have a connection, you send the data over that connection. If you want to have a second transmission line, you just make another connection.

Of course, this will send a separate stream, the UDP packets carrying the SRT transmission will be sent separately for every connection and with different information in the SRT header. Although there's one thing sure here: the boundaries for data being sent by subsequent packets will be identical anyway because SRT requires that every payload has a size limit and it's sending exactly the whole buffer that was passed to it in one UDP packet. So, every call to sending will result in receiving this exactly same buffer on the receiver side.

Just the duplication would have to happen exactly in the sending application (simply send the same buffer to every connected socket), not on the switch.

**Comment by tiagoliveira9** [comment]
That was what I was afraid of, being exactly like TCP. Thanks for the explanation and the time spent! My best regards.
