### ISSUE TITLE
instability due to RTT jitter

### ISSUE THREAD

**Issue by konimaru** [Haivision/srt#31]
This is an issue we experienced initially with UDT. That said - despite SRT using UDT underneath - the behaviour is slightly different.

setup 1
----
- UDP source (DVB-T stream)
- **stransmit** sender
- _link under test_
- **stransmit** reader
- UDP sink

setup 2
----
- UDP source (DVB-T stream)
- **stransmit** sender
- _link under test_
- Makito X Decoder + HDMI display

Under normal conditions what we put into the SRT link we get out. Increasing RTT to 500ms (at link level) is still OK. However, when we add a small percentage of jitter (10ms with 25% correlation) it's getting interesting. The sender increases its output to about 200% while the reader indicates lost traffic.

In general no payload is lost. For small bandwidth usage everything keeps running, above a certain level (e.g. 15Mbit) the SRT link **breaks down** after 10-20 seconds.

So what's going on here? How can a 2% variation in RTT have such odd effects? How - if possible - can this be avoided?

**Comment by heidabyr** [comment]
Hi Marko, we are aware of that behaviour, but it's not a real world problem. There are different simulators out there, some which do probably generate jitter by varying the distance between the different packets on the network, while others actually do a lot of reordering of the packets, latter leads to described problems. We have an algorithm that can take care of these massive re-orderings, but found that it extremely rarely applies in real world applications, even under terrible network conditions some of our customers have to handle. However, I'll as the guys to add some info on the mentioned algorithm to this discussion, so maybe you can give it a try. Thanks, Marc

**Comment by konimaru** [comment]
Thanks, much appreciated.

**Comment by ethouris** [comment]
Ok, I can see now: THE NETEM STRIKES BACK.

But there is a new hope. There is an experimental functionality that can help, and if you say that this can really increase the traffic into 200% of the data to be sent, it would be nice if you can at least test whether it could be worth a shot.

To turn this on, set the SRTO_LOSSMAXTTL option to some nonzero integer value - usually should work with 5, at most 10 (should be also available as `lossmaxttl` parameter in the URI, so you can test it also using `stransmit`). Now let me explain how it works.

There's a value of "loss tolerance", let's mark it LTTL. Initially it's 0, but when it is detected that a packet has arrived out of order - which is recognized by the fact that the sequence number is less than currently expected, it's a packet already seen as lost, but the REXMIT flag is NOT set - then LTTL is set to the difference of these sequences, however not more than LOSSMAXTTL.

Now when LTTL > 0, then every loss is recorded also as "fresh loss" with TTL = LTTL, and LTTL of all fresh loss records is decreased by 1 with every packet arriving, and when its TTL reaches 0, the lossreport is only then sent. Which means that a number of LTTL new packets must arrive after the loss so that lossreport can be sent. This is done in a hope that among the next LTTL packets the lost packet will be recovered, so we save sending a lossreport for it uselessly. The LTTL value also gets decreased by one after receiving 10 packets in a row in order and without loss.

This feature isn't corelated well with NAKREPORT and FASTREXMIT, so even though the lossreport is held for a moment, it may be still fired by NAKREPORT, and the retransmission may still happen even without lossreport, through FASTREXMIT. Not even mentioning TLPKTDROP, which will make the receiver resign this packet anyway, even though it's going to come back normally (increasing latency may help significantly prevent that).

When I was testing this thing using NETEM, there have been occurring several phenomena, such as:

* The retransmited packet arrived earlier than the packet sent normally :)
* There was only SLIGHTLY decreased the number of uselessly sent packets with increased lossmaxttl
* Increasing the latency gave the MOST significantly better results as it comes to uselessly sent packets, the increased LOSSMAXTTL has decreased their number by kinda 10% only

When testing this, it is very important that you turn on logs on "debug" level and the log FA flags contain at least "control" (note that by default all LOG FAs are turned on, so setting only debug level makes the logging pretty noisy). These logs will contain the information about how the decision for retransmitting is being made, whether the packet was retransmited corretly, or uselessly.

**Comment by konimaru** [comment]
Thanks for that explanation. I had a quick go this morning (adding **-max-loss-delay:10** to the receiver) but I still see the same behaviour (higher transmit volume). I'll investigate further. Could well be that the reordering required is out of recoverable range.

**Comment by konimaru** [comment]
OK, I had to move **srt_setsockopt(SRTO_LOSSMAXTTL)** into the POST configuration stage (**stransmit**). Reason being that once the connection is established I get another call to **CUDT::construct()** which resets the **MaxReorderTolerance** setting.

With that out of the way I can confirm that the **-max-loss-delay** option can then be used to decrease the high transmit volume caused by packet reordering.

**Comment by konimaru** [comment]
Turns out the _moving to POST configuration_ probably isn't the best solution. The two calls to **::construct()** I'm seeing are from two different constructors where the second one uses the first as an ancestor. IOW, certain settings shouldn't be set but copied. I'll leave the details to you.

**Comment by ethouris** [comment]
AFAIR the lossmaxttl option is definitely a PRE option... I'll take a look at this more closely at the opportunity of working around the integrated handshake.

**Comment by maxlovic** [comment]
Has "completed" label. Last activity 2 years ago. Closing.
