### ISSUE TITLE
cygwin: severe distortation and eventual failure after few seconds

### ISSUE THREAD

**Issue by mifritscher** [Haivision/srt#331]
We compiled master with cygwin and using following cmdlines:

sender (Win10):
`ffmpeg -i rtsp://root:root@<camera>/mpeg4/media.amp -f mpegts  udp://127.0.0.1:5555`
`stransmit.exe -v -s:500 -r:500 udp://:5555 srt://172.25.30.41:6666`

receiver (Win 7):
`stransmit -v srt://:6666 udp://localhost:7777`
vlc can read the stream, but with severe drops, and stransmit stops with 

>  << 376  ->   sent
> FAILURE
> recvmsg: [2001] Connection was broken.
> SrtCommon: DESTROYING CONNECTION, closing sockets

The connection is a wired 1 GBit network, so this shouldn't be a problem...

**Comment by ethouris** [comment]
Well, mind that Cygwin version was provided mainly in order to make it possible to compile it as Linux under Windows. We haven't tested it if it really works - although so far no problems were reported.

Try to repeat the test by streaming through standard pipe (its `pipe:1` in case of ffmpeg, AFAIK, for stransmit it's `file://con`) instead of through local UDP. With this configuration you have at least 3 pipes where you can lose packets, and losing a packet on a local UDP queue isn't unusual - this may happen if the system buffers are overloaded. VLC should also accept input from the pipe.

Remember also that especially if you run it on Windows, redirect the log into a file, otherwise the CPU burden through logs may severely impact the application.

And if you still have problems, please try to repeat the test on the version from `dev` branch.

**Comment by ethouris** [comment]
Ah, right I forgot this.

No, it's not that stransmit "does not handle overlapping packets". It's because the default packet size for Live mode in SRT is 1316 bytes. You can set higher size through an option (`payloadsize`), but not more than 1456 bytes. The maximum payload size for UDP is 1472 and it exceeds this maximum size anyway, so if ffmpeg sends UDP packets filled up to the cork, they cannot be transmitted over SRT (any other way by repackaging the data).

Why thorough splitting into packets in SRT is important, you can read in the `livestreaming.md` document (`docs` directory).
