### ISSUE TITLE
SRT in WebAssembly

### ISSUE THREAD

**Issue by johnluther** [Haivision/srt#341]
Has anyone explored implementing SRT in WebAssembly?

**Comment by heidabyr** [comment]
We‘ve discussed that idea, but didn’t agree on the underlying transport protocol to the browser, yet. WebRTC data channel in unprotected mode seems best, but still won’t allow a direct connection to a UDP based implementation and require a server side converter.

**Comment by mbakholdina** [comment]
Closing the issue as there is no updates on the topic.

**Comment by Niek** [comment]
Is there no update on this yet? A year ago [SRT P2P was announced](https://www.haivision.com/about/press-releases/haivision-announces-the-addition-of-peer-to-peer-low-latency-streaming-to-the-srt-framework/) with browser support, but I can't find any more info.

**Comment by MarcCymontkowski** [comment]
Hi Niek, it's one of those cases where you think you're almost ready and then the reality kicks in. However, the project is alive and we still plan to Open Source it, hopefully within the next few months.

**Comment by Niek** [comment]
@MarcCymontkowski that's great news, I would be very interested in testing it when it's ready.

**Comment by Phillipip** [comment]
Any news here?

**Comment by MarcCymontkowski** [comment]
Hi, it's important to mention that this ticket confuses two topics:
- SRT implementation in WebAssembly, so basically native SRT support in browsers. There is nobody working on this, as far as I'm aware.
- SRT p2p: A peer to peer project we announced to Open Source, which isn't actually related to the SRT protocol as you know it. We called it SRT p2p, as the plan is to add it to the SRT framework (repository location/project) on GitHub. It is a JavaScript peer to peer network implementation, which manages the network and is independent from the transport layer. This project dragged a lot longer than anticipated due to the nature of the technology.

**Comment by Phillipip** [comment]
OK, thank you very much for your quick answer!

**Comment by topilski** [comment]
Hello, do you have any updates?

**Comment by DDriggs00** [comment]
Yet another annual check-in for updates.

**Comment by maxsharabayko** [comment]
No updates as far as I can tell.

**Comment by itseramin** [comment]
Any updates? 👀
