### ISSUE TITLE
CC error at Listener output - intermittent

### ISSUE THREAD

**Issue by msanis** [Haivision/srt#372]
Hello,

We are facing intermittent CC error at Listener output
Here is a the setup:

RTT: 200ms
**Sender:**
Source Multicast - from professional encoder which shows clean on Streamxpert
stransmit "udp://@236.1.202.111:2001" "srt://123.1.2.3:12060?mode=caller&latency=3000" -t:-1 -r:100 -s:100

**Listener**
stransmit "srt://:12060?mode=listener" "udp://@225.150.220.99:2001?ttl=64" -t:-1 -r:100 -s:100

when we anlayse the output multicast at listener end on stream analyser, we see CC errors intermittently (2-4 CC error increase every 3-5 minutes). This is causing playback issue .

Any suggestion or if I am missing anything on command structure ?

Also we see intermittent below lines on the log:
11:46:01.520553/SRT:RcvQ:worker*E: SRT.c: IPE: ACK node overwritten when acknowledging 17999 (ack extracted: 0)

Any suggestion or if i am missing anything on command structure ?

**Comment by ethouris** [comment]
I've been researching this some time ago and it was for me unclear at that time why this ACK node might be missing and I thought it is something not expected to happen. My best bet is that it's "No big deal", and the error message should be probably demoted.

What is happening here is that the `UMSG_ACKACK` message is received on the receiver, in response to `UMSG_ACK` sent by the receiver back to the sender. When sending this latter message, the receiver remembers the "ACK node" (with appropriate "journal" number) for this very message so that it can match it later with the received `UMSG_ACKACK`, which is required to calculate the time between sending ACK and receiving ACKACK and calculate the average RTT out of this.

The container that keeps the aforementioned "ACK nodes" is a cyclic container and it may get full at some time in theory, although as I can see (the implementation didn't change since UDT, I just made a small code refactoring to minimize dynamic allocations) doesn't do any check if full, removal old unused nodes etc., it simply overwrites them without checking anything.

The only "bad thing" that happens due to this is that in this particular case it can't receive the original time when ACK was sent, so it can't calculate the RTT in this cycle. It might result in something troubling, as long as this was happening all the time or, say, at least once per 4 packets, but in all cases when I saw it it happens at worst once per 10 minutes.

I guess this might occur in case when the RTT resulting from ACK-ACKACK cycle had got some very large peak (which is even better to be dropped because it might confuse the average RTT calculations), which made it be received after a very long time ago ACK was sent and such a long time has passed that it has sent as many ACKs as required to refill the ACK node container.

Probably this problem deserves to be further studied, but we have deferred it as the impact was considered negligible.
