### ISSUE TITLE
measure units for parameters in command line 

### ISSUE THREAD

**Issue by mrbloom** [Haivision/srt#38]
Little questions:
ms           -t:<timeout=0> - connection timeout
bites        -c:<chunk=1316> - max size of data read in one step
bits          -b:<bandwidth> - set SRT bandwidth
per sec     -r:<report-frequency=0> - bandwidth report frequency
per sec     -s:<stats-report-freq=0> - frequency of status report
Am I right?

Because when I set timeout -t:60 
./stransmit -v -t:60  udp://@239.10.10.3:1234?adapter=10.10.70.50 srt://10.85.10.22:5000?latency=8000
I don't see that stransmit wait for 60 sec before exit, timeout is about only a few seconds

**Comment by ethouris** [comment]
(referring partially)
The `timeout` parameter is definitely in seconds. It's passed to the POSIX `alarm()` function (that's why this thing doesn't work on Windows) that makes it in result fire the SIGALRM signal in order to interrupt the sending. This timeout is just to make stransmit automatically exit when nothing is being sent.

I think the "connection timeout" is kinda mistake, or definitely unclear. It is not the time to wait for being connected to the other party, it is the time that it waits before it breaks connection AFTER it is successfully connected (if no data are being transmitted). Bears a better description, I admit.

If you are looking for a connection timeout, use the `conntimeo` option passed in SRT URI.

**Comment by ethouris** [comment]
The frequency of status report and bandwidth report is actually not even in any time units. It's in "times", that is, after how many packets transmitted the report should be printed. Effective frequency expressed in time will depend on the amount of sent data.

The Bandwidth (-b) is used the following way:
```        double expdur_ms = double(transfer_size)/conf_bw*1000;
        auto expdur = milliseconds(size_t(expdur_ms));
```
So it looks for me as this Bandwidth is in `B/s` unit. It's the maximum sending speed that is allowed for stransmit - if it's exceeded (sending used less time than expected), stransmit will use the remaining time for sleeping.

**Comment by mrbloom** [comment]
ethouris thanks for your answers.

May be timeouts can be separate issue.
Because if I plug out cable, admitted on the scheme with red cross for period longer then for 3-4 seconds, stransmit falls.

I set conntimeo to 8 or 8000

**source**
./stransmit -t:60 -b:7500000 -v  udp://@239.10.10.3:1234?adapter=10.10.70.50 srt://10.85.10.22:5000?latency=8000&conntimeo=8
 << 1316  ->  FAILURE
srt_sendmsg: [2001] Connection was broken.
SrtCommon: DESTROYING CONNECTION, closing sockets


**destination**
./stransmit -t:60 -s:1000 -r:1000 -v  srt://:5000?conntimeo=8 udp://239.10.10.10:1234?conntimeo=8
<< 1316  ->  FAILURE
recvmsg: [2001] Connection was broken.
SrtCommon: DESTROYING CONNECTION, closing sockets

  
![default](https://user-images.githubusercontent.com/3195401/27225050-24d53fa8-52a1-11e7-9a0e-b0ad60ebb129.png)

I think when the buffer of destinations is empty, stransmit needs reconnect .

As I read in Deployment Guide the maximum bandwith overhead is 50%, so if we have complete drop of channel we can retransmit through overhead only 4 sec

**Comment by ethouris** [comment]
I'd have to verify a little bit more how this conntimeo actually works, however AFAIR this is only to hold the connecting process for that time in case that the other party doesn't respond. If your connection is broken, you'll get the connection broken report immediately, basing on the premise that there's no mutual communication (timeout for receiving ACK or KEEPALIVE). When the socket is closed, it goes even faster due to receiving the SHUTDOWN message from the closing party.

There's a possibility to introduce a new socket option, which will control the connection persistence timeout. Currently it's hardcoded for 5 seconds, although the checkTimers() function would have to be called at least 16 times since the last received packet from the opposite party.

**Comment by karlbrowns** [comment]
Can I just ask, in the first example given by mrbloom, he uses parameter ?latency=8000 in is SRT URI.  Is this the correct syntax for specifying latency, and what units is it in?

**Comment by ethouris** [comment]
The unit is, AFAIR, milliseconds. And yes, this is the correct syntax - the paramters in the URI are translated into socket options that are set using `srt_setsockopt` (or `srt_setsockflag`). For example, `latency` parameter translates into `SRTO_LATENCY` option.
