### ISSUE TITLE
Difference in how latency is handled between v1.2.0 and v1.3.0

### ISSUE THREAD

**Issue by alexpeits** [Haivision/srt#390]
Upgrading from libsrt v1.2.0 to v1.3.0, we noticed a significant difference in the way the library behaves. We are using libsrt through the gstreamer bindings (https://github.com/GStreamer/gst-plugins-bad/tree/master/ext/srt). The bindings for v1.2.0 presented the following issues:

- passphrase was disregarded and there was no way to encrypt the stream
- latency was disregarded, and the reported negotiated latency from the srt stats was always 0

Upgrading to v1.3.0 with newer bindings, both those problems were solved. The thing is, despite those issues, v1.2.0 gave us good results when simulating bad network conditions: the received stream was very smooth, while the latency in the stream seems to automatically increase in accordance to packet loss.

With v1.3.0, simulating packet loss does the opposite: with the same amount of packet loss as before, the received stream freezes a lot, while there is no apparent increase of latency in the stream. The freezing decreases only with latency set at a value greater than ~500 (latency meaning both the `SRTO_RCVLATENCY` and the `SRTO_PEERLATENCY` flags).

Is there any significant change between those 2 versions that would cause that, and, if yes, what would the parameters be to get a behaviour similar to v1.2.0 (going through the changelogs shows no apparent issue)?

**Comment by ethouris** [comment]
Concerning the problem described for 1.2.0 version: please note that with this version (including when this version is only on one of the parties), the sender party must set the `SRTO_SENDER` flag to true. Without this the SRT parameters (including those for encryption) will not be set at all, although the stream in case of encryption turned on will be "scrambled" (sender will encrypt it, but the receiver won't decrypt it).

And just for information about the latency flags: if you are sending in one direction only, `SRTO_RCVLATENCY` is to be set on the receiver, and `SRTO_PEERLATENCY` on the sender (`SRTO_LATENCY` sets both, just the RCV* will be ineffective on the sender, and PEER* on the receiver - you can use it if this looks simpler, if you send in one direction).

As about this latency problem in 1.3.0, I'd keenly try to reproduce it myself. Can you please provide me with a description of how you simulate the packet loss? It looks like the retransmission happens too slowly, by unknown reason.

**Comment by alexpeits** [comment]
Thanks, I will try the `SRTO_SENDER` flag. To simulate packet loss we use `tc` and `tc-netem` on the sender box, for example `tc qdisc add dev eth0 root netem loss random 10%` for a 10% packet loss.

**Comment by ethouris** [comment]
I tried and this command doesn't accept `... netem loss random 10%` - but it does accept `... netem loss 10%` and the instruction says that it causes 10% loss of randomly selected packets. I tried with this and I can't see any problems. Must be something more in your setup.

Could you please compile SRT as release, but with `--enable-heavy-logging` and rerun with passing `-loglevel:debug` to `srt-live-transmit` (just stream the logs from 2 into a file)? If there are "freezes" on the stream, the debug logs at least shall show me the exact reason as to why it happens. Note that SRT may drop packets intentionally, if recovering too long delayed packet might exceed latency. It's strange for me also that you say that the stream "freezes" - I'd expect it to happen only when `SRTO_TLPKTDROP` is set to false, otherwise SRT shall simply drop data, which by extremely big number of shall result in artifacts.

**Comment by alexpeits** [comment]
Thanks for the feedback. I will try that once there is time and we get to testing with 1.3 again.
