### ISSUE TITLE
Question : SND-DROPPED

### ISSUE THREAD

**Issue by nawer56** [Haivision/srt#393]
Hello, I have a simple question : how to reduce SND-DROPPED ? 

My input is a camera stream over udp : 

` Stream #0:0[0x1011]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuvj420p(pc, bt709, progressive), 864x480 [SAR 1:1 DAR 9:5], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1[0x1100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 130 kb/s`

Do you think this error is due to the camera ? or my config maybe  ? 

Few log provide by my caller :
> 10:13:04.600773/ffmpeg*E: SRT.d: SND-DROPPED 1 packets - lost delaying for 1021ms
> 10:13:04.600950/ffmpeg*E: SRT.d: SND-DROPPED 3 packets - lost delaying for 1021ms
> 10:13:04.601077/ffmpeg*E: SRT.d: SND-DROPPED 1 packets - lost delaying for 1021ms
> 10:13:04.601175/ffmpeg*E: SRT.d: SND-DROPPED 2 packets - lost delaying for 1021ms
> 10:13:04.645467/ffmpeg*E: SRT.d: SND-DROPPED 10 packets - lost delaying for 1027ms
> 10:13:04.729010/ffmpeg*E: SRT.d: SND-DROPPED 10 packets - lost delaying for 1025ms
> 10:13:04.770748/ffmpeg*E: SRT.d: SND-DROPPED 18 packets - lost delaying for 1024ms
> 10:13:04.819055/ffmpeg*E: SRT.d: SND-DROPPED 99 packets - lost delaying for 1053ms

On my listener : 

> 
> 10:13:06.554165/SRT:RcvQ:worker*E: SRT.c: %535798677:No room to store incoming                                                                               packet: offset=69105 avail=7159 ack.seq=543025746 pkt.seq=543094851 rcv-remain=                                                                              1032
> 10:13:06.554204/SRT:RcvQ:worker*E: SRT.c: %535798677:No room to store incoming                                                                               packet: offset=69106 avail=7159 ack.seq=543025746 pkt.seq=543094852 rcv-remain=                                                                              1032

**Comment by ethouris** [comment]
SND-DROPPED appears in the following situation:
* TSBPDMODE is on (default)
* UDP Packet loss has happened
* For the lost packet that is about to be retransmitted:
    * The current time > Packet Timestamp + Single Trip Time + Latency
    * This means that there's no point in transmitting the packet because TSBPD facility on the receiver side has already forgotten this packet (will discard it anyway)

The time distance displayed in this log is a difference between the packet's timestamp and current time. This mechanism isn't even so strict to observe whether this delay exceeded the latency - the minimum value of tolerated delay is currently 1020ms.

We have observed some "suspicious" behavior of this mechanism some time ago, so if you retry the test with debug logs on (use `--enable-heavy-logging` for `configure` and `-loglevel:debug` option on `srt-live-transmit` app), it will be very helpful. For now I can only speculate that it might be packets lost again during retransmission, or loss report processing (from both sides) happened too slowly - but there can always be some not yet well determined reason, that's why it would be really useful if you collect the logs.

When "No room to store incoming packet" message appears, it means that the application using SRT doesn't read the packets as fast as they come in and the receiver buffer has gone full. In such a situations packets will be dropped, but when the application isn't applied enough flogging, the sequence gap between the top packet in the buffer and the incoming packet will grow up to the buffer size, and this will result in breaking the connection for safety reasons.

**Comment by nawer56** [comment]
Thinks for you time . 

I've added on both side (caller and listener) `tlpktdrop=0` then both error are removed. After a while. the stream quit due to a circular buffer overun. 

Ok i'm trying to adapt my ffmpeg command to your srt-live-transmit.

Listener:
` ffmpeg -v "debug" -i "srt://:1234?mode=listener&buffer_size=10485768&tlpktdrop=0" -c:v h264 -x264opts keyint=58 -r 29 -c:a aac -flags +cgop -hls_time 1 -hls_list_size 25  -hls_segment_filename 'pi/stream-%08d.ts' pi/stream.m3u8       `

Caller:
ffmpeg -v "trace" -f mpegts -i udp://10.5.5.9:8080 -f mpegts "srt://server.com:1234?pkt_size=530&buffer_size=1048576&mode=caller&oheadbw=50&inputbw=875000"

**Comment by ethouris** [comment]
Turning TLPKTDROP off will make this not happen, however it means that SRT will not sacrifice data in order to keep up with the data rate, that is, instead of dropping too late data, it will hold the whole stream until the data are retransmitted, which may make some frames not reassembled at the time when the decoder expects them.

The receiver buffer overflow is a different kind of problem. You may try to experiment with increasing the receiver buffer size, but this will only help if the receiving application suffers of only a temporary slowdown and it will surely speed up once the temporary problem is gone. It would be first of all interesting to see how there's shaping the time distance between the moment when the packet is given up to the application by SRT library (the "DELIVERED" message in the debug logs) and the moment when the application extracts this packet and passes it to further processing.

**Comment by maxlovic** [comment]
Closing due to long inactivity (more than a year).
