### ISSUE TITLE
Connection failed when using virtual IP address

### ISSUE THREAD

**Issue by ethouris** [Haivision/srt#431]
Connection cannot be made in the following conditions:

1. The current machine has such a network configuration that more than one local IP address refers to the same network (e.g.: 10.0.2.5/24 and 10.0.2.10/24 - both have the network designated as 10.0.2.0).
2. The listener socket is bound as default (to INADDR_ANY)
3. The connection attempt is made to a different address than the "first one" (the address that is the "first in the order" of addresses assigned to this network).

The reason is that in such a case the handshake packets returning from the listener to the caller have as the source address in the UDP packet the address that is this "first in the order", which doesn't match the address to which the caller was attempting to connect, and therefore the listener response is rejected by the caller on this premise (treated as an attack attempt).

Possible fix: the IP_PKTINFO cmsg ancillary data should be added to `msghdr` structure prepared for the call of `sendmsg` function. As it has been experimentally verified that this problem does not occur in case when the listener is bound to an explicit IP address, this needs to be only done in case of binding to INADDR_ANY. This "packet info" may be a structure recorded in the accepted socket's data and used every time with `sendmsg` call.

**Comment by ethouris** [comment]
The solution is waiting for performance tests of the solution. The solution is to use PKTINFO to extract the exact target address from the incoming connection request, then use it as a source address (enforce it) when sending back the listener response, and then also within connection.

**Comment by ethouris** [comment]
#456 is the fix.

**Comment by maxsharabayko** [comment]
Steps to reproduce via local switch (not checked):
1. Have two NICs connected to the same local switch.
2. Set IP addresses from the same subnet. E.g. 192.168.0.10 and 192.168.0.11
3. Run SRT listener not bound to a certain interface: e.g. 0.0.0.0:4200
4. Try to connect to one of the IP addresses from another machine. The connection should fail. In certain cases the SRT packet arrives on one NIC, but the reply will be sent from another NIC, because they are in the same subnet.
