### ISSUE TITLE
Unnecessary Namespace Pollution in the Public API and Public Facing Library Symbols

### ISSUE THREAD

**Issue by jlsantiago0** [Haivision/srt#443]
The SRT library has a significant amount of unnecessary namespace pollution in both the Public API and Publically exposed library symbol names.

Publically exposed library symbol names should be prefixed with ```SRT|srt|Srt```, etc or at least using only a few number of defined prefixes.

Publically exposed macros should be prefixed with ```SRT```or something similar.

Custom Macros with ```_``` prefixes should not be defined or exposed to the public API.

There are many examples. Brief look at:

srt/udt.h:
   - threadcheck is not used in the public API. Why have definitions for it in this file? The ```THREAD_*``` and ```INCREMENT_THREAD_*``` macros should be moved to a private header and not exposed in the public API at all..
   - ```__MINGW__``` is a non-standard macro with leading __ . It is defined in this file, but this file is not necessarily included in the files where the macro is used. This macro should not be defined in the public API headers. Check for  the ```defined(__MINGW32__)``` which will be unconditionally define by the toolchain instead and use a custom _ prefixed macro.
   - Macro ```NO_BUSY_WAITING``` is defined, but not used in the public API that I can find. So it shouldnt be here.
   - Publically Exposes symbols with names like ```logging::Log*, Logger, CPerf*``` , etc.

srt/srt.h:
   - Macro ```NO_BUSY_WAITING``` is defined here also, but not used in the public API that I can find. So it shouldnt be here.
   - Uses the ```__MINGW__```, but should check for the ```defined(__MINGW32__)``` which will be unconditionally define by the toolchain instead and use a custom ```_``` prefixed macro.
   - Non-prefixed identifiers in the public API: ```CodeMinor, CodeMajor, CByte*```, etc.

**Comment by ethouris** [comment]
The header file `udt.h` serves now as "Legacy & C++ extension API", so I think it should be enough if there is only added some awareness info about this problem. The `__MINGW__` macro if it's defined, probably should be taken care of.

The `NO_BUSY_WAITING` macro is something that spreads since UDT times. Since SRT it has always been defined. I think this could be removed together with all code that is conditioned for this turned off, but there should be a research done about this first.

For `CBytePerfMon` and `CPerfMon`, I think these names can be simply changed, they already have aliases with `SRT_` prefix.

The `CodeMajor` and `CodeMinor` may change names, I don't think they are used. Exposing them maybe is not necessary, but the problem is that the really intended to expose the `SRT_E*` values can be only easily composed out of them if they are in the same file (otherwise there would have to be made cross-file constants).

**Comment by maxsharabayko** [comment]
Closed together with #1924 as resolved. PR #2324.
