### ISSUE TITLE
Artifacts with SRT and RTP

### ISSUE THREAD

**Issue by oxfordpelican** [Haivision/srt#458]
When I use rtph264(de)pay in gstreamer with SRT I get a lot of artifacts on the receiving side. When I use mpegtsmux I don't have this problem. Why is this?

**Comment by premultiply** [comment]
You can not play an MPEG-TS via RTP as H.264 elementary via RTP. This is a missunderstanding and not an issue on SRT.

**Comment by oxfordpelican** [comment]
I think I have to give more details, this is the RTP pipeline:

sender:
v4l2src | omxh64enc | rtph264pay | udpsink

with srt-live-transmit in between

receiver:
udpsrc | rtpjitterbuffer | rtph64depay | avdec_h264 | xvimagesink

This is the mpegts pipeline:

sender:
v4l2src | omxh64enc | mpegtsmux | udpsink

with srt-live-transmit in between

receiver:
udpsrc | tsdemux | avdec_h264 | xvimagesink

Btw, the sender is a Raspberry Pi 3B+

**Comment by oxfordpelican** [comment]
I can reproduce this problem with these commands:

sender:
`./srt-live-transmit udp://127.0.0.1:8000 srt://127.0.0.1:1234/?mode=listener`

`GST_DEBUG=3 gst-launch-1.0 -v videotestsrc horizontal-speed=4 ! "video/x-raw,width=640,height=480,framerate=10/1" ! videoconvert ! x264enc ! rtph264pay pt=96 ! udpsink port=8000`

receiver:
`./srt-live-transmit srt://127.0.0.1:1234/?mode=caller udp://127.0.0.1:9000 -s:1000 -pf:json`

`GST_DEBUG=3 gst-launch-1.0 -v udpsrc caps="application/x-rtp,media=(string)video,clock-rate=(int)90000,encoding-name=(string)H264" ! rtph264depay ! h264parse ! avdec_h264 ! xvimagesink`
(or use VLC/mplayer)

VLC outputs these errors:
```
error while decoding MB 0 7, bytestream 3829
left block unavailable for requested intra4x4 mode -1 at 0 1
```

Without SRT, only RTP there are no errors.

This is tested on Ubuntu 16.04

[test.mp4.zip](https://github.com/Haivision/srt/files/2380592/test.mp4.zip)

**Comment by ethouris** [comment]
Wait. You are going to pass the UDP packets carrying the RTP protocol over SRT, am I reading that correctly?

Then please note that the default maximum payload size for SRT is 1316, which is 7*188, and this is the size that suits sending MPEG-TS over UDP. Here you are sending something else than MPEG-TS and the payload size in a single UDP packet may exceed this 1316 bytes.

But there is a method to overcome this. The maximum possible single packet payload size in SRT is 1456 and you can change the maximum payload size up to this value using SRTO_PAYLOADSIZE option (also as `payloadsize` attribute in SRT URI). Still, you should keep in mind that a pure UDP packet has space for more bytes (1472) so transparent sending any data from UDP through SRT won't work. But with RTP it should be fine because it will still carry at maximum 1316 + RTP header, which will not exceed this maximum possible payload size in SRT.

Of course, I understand that you have built this pipeline only for testing because in the use case from the above it seems useless to wrap the stream additionally in RTP.

**Comment by maxlovic** [comment]
Also don't forget about the chunk size command line argument of `srt-live-trasmit` (`-c`).
```
./srt-live-transmit udp://127.0.0.1:8000 "srt://127.0.0.1:1234/?mode=listener&payloadsize=1456" -c:1456
./srt-live-transmit "srt://127.0.0.1:1234/?mode=caller&payloadsize=1456" udp://127.0.0.1:9000 -s:1000 -pf:json -c:1456
```
