### ISSUE TITLE
ASYNC

### ISSUE THREAD

**Issue by dduquesne** [Haivision/srt#521]
Hello,

I am trying to use SRT in ASYNC mode without looking at Epoll event.
So i have created Src and Tar with 
SRTO_RCVSYN = false
SRTO_SNDSYN = false

But connect / accept step does not success even into a loop.
Maybe i don't use the right criteria to break.
I am looking at the status and wait for "connected".
I see from the logs that a first packet exchange occurs but it does not go further.

Is it mandatory to instantiate Epoll, get a poll ID , add srt soks to the poll and use srt_epoll_wait like it is implemented in srt-live-transmit to use ASYNC ?

I would like to avoid that but keep using ASYNC mode.
I need a non blocking read/write but i want to work in a busy polling mode instead of using the event based Epoll system.

Thanks for any feedbacks,

**Comment by ethouris** [comment]
The rule for connection itself for async mode is:

1. Caller. You should call this function, although it will return immediately without making the real connection (it will continue in background). The "connected" state will simply make your socket at some point able to use. In the event world (epoll etc) the socket enters the connected state when it becomes ready to write.

2. Listener. You shall **not** try to call `srt_accept` until you are sure it will succeed. It will succeed when the listener socket becomes ready to read.

Although I don't know about any conditions that could spoil anything in the listener socket if you try to call `srt_accept` without having a pending connection - it should at some point return it. Mind only that if you are running a loop without any stops or even short sleeps, you will overload the system with your process's requests and this might slow down the whole background processing to the grade beside which it's impossible to continue. For example, the handshake process that engages the connection has also its timeout; if the listener process responds too slowly, the connection might never be established.

It is not mandatory to make an epoll for that, it's just currently the only reliable source of information about operation readiness and its status. For example, for a socket you could theoretically trace the values from `srt_getsockstate`, the problem is though that the connection failure will not be properly reported - the state will stay `SRTS_CONNECTED` even after the connection has failed and is no longer in progress. This is only known from `srt_epoll_wait`.

Note that you can call `srt_epoll_wait` with no waiting timeout (a >0 value defines the timeout, 0 exits immediately after the initial check, -1 waits indefinitely), that is, request to report the state immediately. If your application would like to do other productive things at the same time, but you'll have enouh often cases when you'd continue the job on SRT when it becomes ready, this should be the right solution.

**Comment by dduquesne** [comment]
Hello Ethouris,

Many thanks for this detailed answer.
It's clear.
I am moving forward.
