### ISSUE TITLE
Can I make a peer to peer connection using SRT?

### ISSUE THREAD

**Issue by jseun112** [Haivision/srt#548]
Actually, I'm implementing a voice call application using SRT.
But, I know P2P connection process is needed to connect between Peers.
Is there any way to connect between Peers on SRT?
Simply, I want to know there is any way such as WebRTC.

**Comment by maxlovic** [comment]
Hi @jseun112,
SRT v.1.3+ allows bidirectional communication and multiple client connections. So answering your question: in general, yes, you can. The devil in in details.

**Comment by jseun112** [comment]
Does it mean SRT have some APIs can connect between anonymous Peers such as ICE protocol ?

**Comment by MarcCymontkowski** [comment]
SRT is just the transport protocol to be used to transmit encrypted data with high throughput and low latency over UDP, end to end. The connection management has to be done separately.

**Comment by maxlovic** [comment]
Adding to Marcs reply, SRT can accept multiple connections and send the data in both directions. So exchanging the IPs of other peers is doable, but on top of SRT. Like, you just need a specified format of messages, that will contain the list of peers. What you will do with it - SRT does not care, it is stream agnostic. It is up to you how to parse them and establish further connections.

**Comment by ethouris** [comment]
In order to establish a connection using SRT API, you need the IP address of at least one party (the party that doesn't know the peer's address would be listener; you need to know both IPs on both parties if rendezvous). This is actually true in any case, so if your appliance needs to work without knowing it, there must exist either some point of information exchange from which it will be known, or there must exist some central point with public IP address to which both endpoints would connect (this is the only possibility if, for example, both parties are hidden behind NAT). Something that would simply do a bidirectional data passthrough.

**Comment by rmsoto** [comment]
> multiple client connections

On listener/server accepts multiple caller/client connections? IF yes, how?

Thanks!

**Comment by maxlovic** [comment]
@rmsoto 
`srt_listen(...)` to start listening on a socket. `srt_accept(...)` to accept a new connection.
Refer to the [API docs](https://github.com/Haivision/srt/blob/master/docs/API.md).

**Comment by maxlovic** [comment]
Closing.
Do not hesitate to reopen or add comments, would you have further questions.
