### ISSUE TITLE
sndqueue cost too many thread?

### ISSUE THREAD

**Issue by runner365** [Haivision/srt#559]
Hi, I read the code, find that each CSndQueue has one thread which is used to send packet based on timestamp.
void CSndQueue::init(CChannel* c, CTimer* t) {
.....
pthread_create(&m_WorkerThread, NULL, CSndQueue::worker, this)
.....
}
my question is when we setup a srt server for livestream and the server has 1000 different client connections at the same time, does it mean the srt server create 1000 different thread at the same time. 
For me, there is a large number of thread in server. If it's true, How can we solve it.

Thanks.

**Comment by maxlovic** [comment]
Hi @runner365,
There is only one thread to send data to the network, and one `CSndQueue`. `CSndQueue` has `CSndUList`, that handles different socket connections and decides which to process next (heap of sockets).

**Comment by ethouris** [comment]
It's not so unanimous. Generally each SRT socket has its own "multiplexer", but they can also be shared.

"Multiplexer" is a special object that, generally, "sits on a UDP socket", and it contains:
 - a Channel (wrapper over the UDP socket)
 - a Sender facility, with its
       - thread
       - queue
       - data buffer
 - a Receiver facility, with idem

In case of listener, the listener socket uses exactly one multiplexer, and so it is for all sockets that are "accepted off" the listener, and therefore exactly one instance of the above.

In case of caller, in general case every socket used as a caller has its own individual multiplexer - but optionally you can force multiple SRT caller sockets to share one multiplexer. To do that, you can either "borrow" a multiplexer from an existing SRT socket as long as this socket is bound.

The socket is bound either automatically if you perform `srt_connect` without binding it first, or you can do it yourself prematurely by calling `srt_bind` on it. With this you can:

 - decide to use some known as free UDP port, and bind every socket to this port (see how the `port` attribute is handled in the example application, find the `SrtCommon::SetupAdapter` function)
 - allow the system to autoselect the first found free port for you for the first socket (connect it without binding, or just bind to 0.0.0.0:0), then extract the system-selected port by `srt_getsockname` and use it for every next socket

To make this possible, `SRTO_REUSEADDR` must be set to true, which is default. Internally it works this way that if there is a socket attempted to be bound to a given address, and there's found an already existing multiplexer already bound to that very port, then this multiplexer is increased sharing instead of that a new multiplexer be created.

The `srt-multiplex` example application is created exactly to demonstrate this feature.

**Comment by maxlovic** [comment]
@runner365 
Closing. Do you hesitate to reopen if you still have questions.

**Comment by BananaHemic** [comment]
I have a question on how to make the listener sockets share a multiplexer, please let me know if this would be better placed in a separate issue.

When I receive new client connections from srt_accept, I still have to push data individually to each returned SRT_SOCKET, so I'm curious as to how each of those sockets is using a shared multiplexer, considering that every multiplexer has its own CSndQueue. Is there any additional work necessary to make the sockets all use the same multiplexer?

I've looked through the srt-multiplex file, but I haven't found anything that would suggest additional effort needed to make the listened sockets share a multiplexer.

**Comment by ethouris** [comment]
Again.

In case of a listener socket, there's ONE exactly multiplexer used for the listener socket (for the sake of accepting incoming connections) and it's shared with all sockets accepted off this listener (with every socket returned from `srt_accept` call made on this listener socket). This situation is always and there's even no possibility for them to use separate multiplexers.

Therefore there's one CSndQueue instance for all these sockets, scheduling a packet over any of these accepted sockets uses this one queue to send them. It doesn't matter that the same UDP socket is then used to send the payload to potentially different IP addresses. As the data come in from potentially various multiple remote machines, all of them are send to this UDP socket as per its bound address and port. To which exactly SRT socket particular packet is destined, it's recored in the SocketID field in the SRT header.

What you can't do is to make multiple listener sockets share one multiplexer because every SRT listener socket must be bound to a unique port for listening for a connection.

**Comment by BananaHemic** [comment]
Thank you for the clarification, I apologize that I made you reiterate some details.
Two quick clarifying questions:

1. If every socket accepted off the listener is using the same CSndQueue, does the SRTO_SNDBUF need to be increased based on the number of sockets that have been listened off the original socket?
2. Is there anyway to srt_sendmsg to all accepted-off sockets simultaneously, or is my best bet to just do srt_sendmsg to each socket individually?

**Comment by ethouris** [comment]
1. No. CSndQueue is rather a functional object that is responsible for picking up data to send them, and it is one per multiplexer. Sender buffer is individual for a single socket because it must keep data in the order of sequence number for prospective retransmission. The CSndQueue object has an underlying list of sockets that it manages and at appropriate time one of them is picked up to extract a packet from the buffer and send it. Might be that this "queue" word in this name is kinda misleading (we haven't changed the original names from UDT).

2. Unfortunately no, you'd have to simply send the same payload to all sockets in a loop.
