### ISSUE TITLE
srt-live-transmit crashes when multiple callers try to connect

### ISSUE THREAD

**Issue by alexanderdevm** [Haivision/srt#595]
Srt-live-transmit will crash in the following scenario:
- When srt-live-transmit is executed as listener
- When more than one srt caller tries to connect to the same listener

Expected scenario:
- Srt-live-transmit should reject other callers without crashing

Error message:
```
18:16:41.345889/SRT:RcvQ:worker*E:SRT.c: newConnection: listen backlog=1 EXCEEDED
18:16:41.346169/SRT:RcvQ:worker*E:SRT.c: UU:newConnection: rsp(REJECT): 1002
18:16:41.365694/SRT:RcvQ:worker*E:SRT.c: newConnection: listen backlog=1 EXCEEDED
18:16:41.365717/SRT:RcvQ:worker*E:SRT.c: UU:newConnection: rsp(REJECT): 1002
```

Srt command:
```
LD_LIBRARY_PATH=/tmp/ffmpeg/build/lib64/ /tmp/ffmpeg/bin/ffmpeg     \
-hide_banner     \
-loglevel panic    \
-re -f lavfi     -i testsrc     \
-f lavfi     \
-i "sine=frequency=200"     \
-t 60     \
-pix_fmt yuv420p     \
-c:a aac -strict -2     \
-c:v libx264     -g -25     \
-b:v 900k     \
-f mpegts pipe:1 | /tmp/ffmpeg/build/bin/srt-live-transmit -q     \
-t:60     \
file://con    \
"srt://0.0.0.0:49005?mode=listener&passphrase=pa$$word"
```

**Comment by maxlovic** [comment]
Have quickly checked the following scenario:
**Listener:**
`srt-live-transmit srt://:4200 udp://127.0.0.1:4950`
**Caller No.1:**
`srt-live-transmit udp://:4901 srt://127.0.0.1:4200`
**Caller No.2:**
`srt-live-transmit udp://:4901 srt://127.0.0.1:4200`

The first caller connects, the second does not. v.1.3.2 OS Windows localhost.

The issue might be that the passphrase should be at least 10 symbols in length.You are passing eight `passphrase=pa$$word`.
And the crash might be fixed by 1a97a3d3f4f448ed5be58b38f85f0707554f4396

@alexanderdevm, please check with the latest version of SRT.

**Comment by alexanderdevm** [comment]
@maxlovic Normally srtansmit rejects other callers. In my cause where I have up to 10 callers try to connect for a period of up to 5 min then disconnect and try to connect again and again between 20 to 60 min, that's when the issue happens.

**Comment by maxlovic** [comment]
Closing as abandoned.
