### ISSUE TITLE
[change request] Apps on IPv6 ?

### ISSUE THREAD

**Issue by Litrona** [Haivision/srt#633]
Can I use srt-live-transmit on IPv6 ? I have tested ok on IPv4 but seems cannot use [::] IPv6 addresses.

**Comment by ethouris** [comment]
Unfortunately, the application isn't prepared to handle IPv6 addresses. There's no problem in the library.

In particular, the utility function, `CreateAddrInet` handles only IPv4. This function is using `inet_pton` internally so this is theoretically possible to rework it so that it can handle both IPv4 and IPv6. Please submit an issue for this, or simply turn this one into a change request.

**Comment by maxsharabayko** [comment]
Saving this list for the future:
- `sockaddr_in sa;` -> `sockaddr_in6 sa;`
- `sa.sin_family = AF_INET;` -> `sa.sin6_family = AF_INET6;`
- `inet_pton(AF_INET, name.c_str(), &sa.sin_addr` -> `inet_pton(AF_INET6, "::1", &server_addr.sin6_addr)`
- `sa.sin_port = htons(port);` -> `server_addr.sin6_port = htons(port);`

**Comment by Litrona** [comment]
I have seen some steps on this way recently, such as:
- https://github.com/Haivision/srt/pull/1360 (https://github.com/Haivision/srt/commit/92abcd616c3fe13b0d0ce682043f83846d80c479)
- https://github.com/Haivision/srt/pull/1358 (https://github.com/Haivision/srt/commit/0aa49c7185eee6d7a404534f3632f8fb50c607d1)
- https://github.com/Haivision/srt/pull/1355 (still pendant)

Does this mean that my request will be done during v1.5.0 ?

**Comment by ethouris** [comment]
Well, yes, it's already in master, so it will be. The IPv6 support by the app was needed to test the fix.

The problem in 1355 is something that exists since UDT4 version. It didn't handle properly the situation that listener is IPv6 and caller is IPv4, and incorrectly interpreted the target IP address, which caused that `srt_getsockname()` on an accepted socket returned garbage in this case.

**Comment by ethouris** [comment]
As IPv6 support in the application is already provided, I'm closing this.
