### ISSUE TITLE
Interesting library. A couple of Qs!

### ISSUE THREAD

**Issue by oviano** [Haivision/srt#643]
I'm thinking of whether to integrate it into my project (emustream.tv) which currently uses a custom protocol based on TCP which is pretty much the same as HLS.

1. How easy would it to modify SRT to build without the SSL component, as I wouldn't need this and it would probably make building it easier on the platforms I use (Windows, macOS, iOS, tvOS)?

2. I can see it can be built for iOS, how about tvOS?

3. I mentioned above that my system is similar to HLS, how would SRT perform in that scenario i.e. lets say the server is generating segments of 1s each, and as each one is created it is sent to the player, would SRT use the "file" option for this? Or would my code be better off sending the data as a continuous stream as the encoder produces the packets, using the "live" mode to get the best out of SRT?

4. What are the differences between the original UDT and SRT without SSL running in file mode?

**Comment by ethouris** [comment]
Hello,

> 1. How easy would it to modify SRT to build without the SSL component, as I wouldn't need this and it would probably make building it easier on the platforms I use (Windows, macOS, iOS, tvOS)?

May take some effort. As I can see, it requires conditional turnoff in `core.cpp` in every place where `m_pCryptoControl` is referred to. Sometimes may need alternative code which should also react to a situation when the peer is trying encrypted connection. Might also need some extra change in the build file (`CMakeLists.txt`) so that the whole HaiCrypt wrapper isn't added to the library.

> 2. I can see it can be built for iOS, how about tvOS?

I could see some conditionals especially for the latter, so I guess at least someone tried.

> 3. I mentioned above that my system is similar to HLS, how would SRT perform in that scenario i.e. lets say the server is generating segments of 1s each, and as each one is created it is sent to the player, would SRT use the "file" option for this? Or would my code be better off sending the data as a continuous stream as the encoder produces the packets, using the "live" mode to get the best out of SRT?

SRT wouldn't use the "file" transmission mode unless you order it to, by setting `SRTO_TRANSTYPE` option to `SRTT_FILE`. You can use it, of course, although this isn't the mode predicted for live streaming (the live streaming features delivery time jitter elimination and conditional packet dropping; the file mode lacks these).

What would be the best option for you, it depends on where exactly you need your dedicated protocol to be used. One of the methods is that a live stream is being sent using plain mpeg-ts (possibly with encryption) over SRT to the farthest endpoint, and the latter is flipping it into some other TCP-based protocol, where TCP can do least harm.

> 4. What are the differences between the original UDT and SRT without SSL running in file mode?

From the transmission point of view, there should be none. The handshake works a little bit differently by obvious reasons, but rest of the functionality is unchanged (or, more precisely, the old code has been reused in the new framework).

**Comment by MarcCymontkowski** [comment]
Hey @oviano, the message mode is ideal for segmented workflows, e.g. to transmit HLS segments, where one segment is sent in one message. We did create a demo application, which adds a header to the messages, so that manifests and segments are transmitted with relevant metadata. If you'd use that approach, you would disable the live mode. However, you could also try to send a "live signal", depending on how your protocol actually works.

**Comment by oviano** [comment]
Thank you both for the feedback!

So up until now my system has basically worked much like HLS, except instead of publishing the segments to a web server, it just sends them down a TCP socket directly to the player. The player then buffers a certain amount of data before passing it to the underlying playback library.

It works pretty well, but I came across this library and its got me thinking about what actually is the optimum approach for live streaming, as I'm not contained to do things in a HLS-style way.

My requirements are fairly low latency, e.g. a few seconds. The app is a private "placeshifting" system,  so you capture the output from your STB, or tuner, and then the server app re-encodes that using HEVC and sends it down a private stream to the player. The latency shouldn't be too high otherwise things like channel changes on the remote STB then take an age, but it doesn't necessarily need to be super low latency.

The player can also adjust the video quality, which basically starts a new encoding session on the server. It's not a broadcast system, in the sense that it's only meant for one (or a limited number) of viewers.

Anyway, now I'm wondering whether the approach I'm taking is the best one. Even before considering SRT, I am wondering which of the possible two scenarios is best:

A. Write out segments, lets say 1s in duration. As each one is completed, send it as quickly as possible to the player.

B. Write out a continuous stream of data as the encoder produces it.

Which would be more reliable, I wonder?

B seems to then lend itself well to using SRT.

**Comment by oviano** [comment]
Just to answer @ethouris - in my case, I have servers in London and Istanbul, and stream from each from both locations, so either across Europe, or within the LAN at either location. Then also when out and about on mobile, connecting to either. Generally latency varies from 1ms across the LAN to 100+ms when streaming from Turkey to the UK.

But the system is free for anyone to use, so that's just an example.

**Comment by MarcCymontkowski** [comment]
I think both use cases - live continuous as most SRT users do with MPEG-TS or HLS fragments in messaging mode and data mode (live mode disabled) - should work.

**Comment by oviano** [comment]
Ok thanks.

I was just reading this from the "Live Streaming Requirements":

"Now, imagine the very first video frame in the stream, which is called an "I-frame". This frame is just a compressed picture, and it needs no additional information to decode it into a displayable pixmap. Several transport units (of 1316 bytes) are needed to transmit the I-frame over the network. The audio frames for the period of time corresponding to this video frame should also fit into this "duration". So, you will need to send several units of 1316 bytes to transmit all these data over a network. But you usually spend much less time to transmit than the actual "duration" (1/60s in our example). **This doesn't mean, however, that you should send the video and audio data as fast as possible and then simply "sleep" for the remaining time! It means that you should split the whole 1/60 second evenly across all single 1316-byte units.** There is a "unit duration" for every single 1316-byte unit, so you send the unit, and then "sleep" after every unit, if sending (as usually happens) has taken less time than the exact time predicted to be spent by sending this unit."

So is this describing how SRT works already, or is this how the TS data should be provided to the SRT socket?

I'm intrigued as to the reasons why the approach highlighted in bold is considered optimum. Is it to avoid saturating the link so that only the minimum required is used, and this somehow makes it more reliable/able to resend dropped packets etc? Just trying to understand :o)

**Comment by ethouris** [comment]
This is a description of how the live stream should be sent over the network - without even referring to SRT. From the SRT point of view, this is what should be given as input for SRT. This is because the only facility that can properly define these gaps between consecutively sent UDP packets is the facility that knows the content parameters. Without content awareness it's impossible to define appropriate bitrate, which maps to the rate at which single data portions - sent through single UDP packet - should be then sent over the network.

SRT does control the speed at which the data are being sent, but this is only in case when you have a bandwidth limit set from upside so that this limit isn't exceeded - and the only situation when this bandwidth might be exceeded is when you have some larger packet loss that needs to be recovered. Note that in Live mode, SRT doesn't do any speed measurement. For a live stream, either your network is capable of sending a live stream at given bitrate or your connection will get quickly broken - speed control makes no sense here, unlike in case of file transmission.

**Comment by oviano** [comment]
Ok thanks - so how smooth does the encoder output need to be? i.e. I've noticed that for example as NVIDIA NVENC outputs the packets, each frames-worth of data (lets say 16667 microseconds for 60fps content) doesn't arrive exactly 16667 apart, e.g. it might be smaller if the encode required less GPU and then larger if the the encode was more costly, of course it averages out to be real-time as it is being fed by a real time input capture, but would I need to regulate the encoder output somehow?

**Comment by ethouris** [comment]
If you have, let's say, one frame that splits into 240 packets then 9 difference frames that split into 30 packets (just as an example for one GOP), then with 60fps you have 10 frames with total of 510 packets to be delivered in 1/6s, which makes about 11.7ms time predicted for one packet. This is something that can be predicted from the stream parameters. Of course, the actual bitrate may vary during transmission, but as much as this is possible the "gain" you have from sending less data later should be at least partially given to the more dense data sent earlier.

What is required here is that this I-frame (as a biggest portion of data assigned to a single timestamp) is delivered on time to the last packet; rest of the (smaller) frames would then be delivered in complete much earlier than required, but there's nothing wrong with that.

Two things are important here:
 - ideally, the "remaining time" should be evenly distributed between packets
 - if there are any greater congestions, this will map to increased bandwidth usage at the moment

The absolute most important thing is the following: After the decoder receives the first I-frame (in particular, when the splitter delivers it, which means, it's when the packet with last portion of data comprising the same I-frame arrives), every next frame should be completed by splitter at least before the moment when it should be decoded and played. A belated one UDP packet may map to belated frame delivery from the splitter and make the decoder impossible to ship the next frame in the expected time.

**Comment by oviano** [comment]
Thank you for the detailed information, I really appreciate it.

I will integrate the library and see how I get on.

**Comment by ethouris** [comment]
Ok, I'm closing this; I rely on that old questions can be still found in the closed issue archive.
