### ISSUE TITLE
Client example on macOS requires "server" Sandbox entitlement in Xcode

### ISSUE THREAD

**Issue by oviano** [Haivision/srt#647]
I was trying to figure out why the bind that gets called down inside SRT was returning "operation not permitted" and it turns out I needed to turn on the "incoming connections (server)" entitlement in Xcode.

This doesn't seem to make much sense as I was attempting an outgoing connection to another machine running the server example...is it just an artefact of the way SRT works? When I use normal TCP BSD sockets I am able to connect out without needing to enable this entitlement.

**Comment by ethouris** [comment]
This is because TCP and UDP are system protocols and whatever you can see as "the same logics" works completely different way. UDP is a unidirectional protocol and also connectionless - so I have no idea what exactly someone had on their mind when writing "incoming connections (server)" for UDP, it's something completely misleading. What I guess they meant was that this socket would be meant to **receive** data - as just the term of "connection" is useless in UDP.

In TCP it completely makes sense - but it means something completely different, if not even completely unrelated. In TCP "server" means that it will be listening for connections there, but then, after it's connected, the data can be sent in whichever direction.

Unfortunately the system knows nothing about SRT and can operate only in the logics of UDP - and when matching this already mislead nomenclature used for UDP, for SRT it causes even bigger mess.

So, from the system perspective, your application using SRT is simply an application using UDP serving as both "incoming" and "outgoing", **always**, regardless of what connection arrangement your application is using and in which direction you are going to send the data.

What I guess this declares is that when UDP works as "sender" ("client"?) it should not bind any port and leave it with default 0, in case when you do binding just to select the network device to use (it will use the route-table preselected one otherwise). Of course, the system will still bind it internally and select a random port from the upper port range (32768-65535).

Theoretically `bind` is then not required to be called on a caller socket, if you don't bind it manually, but it's done, here (`CChannel::open`):

```
      if (0 != ::getaddrinfo(NULL, "0", &hints, &res))
         throw CUDTException(MJ_SETUP, MN_NORES, NET_ERROR);

      // On Windows ai_addrlen has type size_t (unsigned), while bind takes int.
      if (0 != ::bind(m_iSocket, res->ai_addr, (socklen_t) res->ai_addrlen))
         throw CUDTException(MJ_SETUP, MN_NORES, NET_ERROR);
      memcpy(&m_BindAddr, res->ai_addr, res->ai_addrlen);
```

That is, it tries to bind the socket to the address resolved as `"0"`. I don't know the exact reason why it is done (it's UDT legacy). Might be that it was about testing and pre-checking the socket before it's used.

But then, I think even if you replace this code and copy the `INADDR_ANY`-based address with port number 0 (that you will overwrite at the next call to `sendmsg`), if the application isn't allowed to be a "server for UDP", you'll get permission denied at the time when `recvmsg` is called.

**Comment by oviano** [comment]
Thanks for the explanation, that makes a lot of sense.

By the way, I am getting very good results with this library! Until now I have been able to use a bitrate of about 4mbps using TCP when streaming from a location in Istanbul, via a 4G connection, to London using my hobby streaming project (emustream.tv) Even then, I need a few seconds of buffering to keep it as stable as possible.

I integrated SRT over the weekend, and setting the latency at a conservative 1000ms straightaway I could get a solid 8mbps. I haven't tried higher, but that's a great result, and one I didn't think possible. Kudos!
