### ISSUE TITLE
IPv6 general status

### ISSUE THREAD

**Issue by ormike** [Haivision/srt#691]
API.md currently has this note:

"Please note that the use of SRT with AF_INET6 has not been fully tested; use at your own risk."

but I see there is good activity around IPv6 and significant support for it in the SRT core library.  Would you say that IPv6 support is nearing production readiness or is the note on API.md still current?  What are the known limitations?  

This question concerns the SRT core library, not the example applications.  Thanks

**Comment by jeandube** [comment]
SRT core library is used with IPv6 in products (linux ARM), including dual-stack (IPv4+IPv6).

**Comment by maxlovic** [comment]
@jeandube Do you think we can delete this note?

**Comment by OliverSchoen** [comment]
Hi,

--- Please don't just delete this note ---

It appears that **_IPv6 support in releases between 1.2.3 and 1.4.1 worked well_**, in the 1.4.1 there was a bug in `srtcore/channel.cpp` specifically in `void CChannel::setUDPSockOpt()` where IPv4 and IPv6 options got mixed up - that was fixed later on.

Now with the release of SRT version 1.4.2 the API `srt_socket(int af, int type, int protocol)` became deprecated and we are supposed to used to new API `srt_create_socket()`.
How does someone specify the address family such as `AF_INET` or `AF_INET6` ?

Can we have this API updated to support specifying the address family of `AF_INET` or `AF_INET6` as the srt_create first parameter previously supported.

Thank a lot.

**Comment by maxsharabayko** [comment]
Hi @OliverSchoen 
Thank you for such a good question!

To create IPv6 SRT socket using `srt_create_socket()` you would need to [bind](https://github.com/Haivision/srt/blob/master/docs/API-functions.md#srt_bind) it either to a specific IPv6 address or to IPv6 any (e.g. `IN6ADDR_ANY_INIT`).

I guess it is a bit less convenient compared to a single call to `srt_socket(int af, int type, int protocol)`.
The only valuable parameter of that deprecated function was `af` that allowed specifying socket family. The rest parameters were ignored. Although, in v1.4.2 all parameters are ignored.

Do you think an additional API function like `SRTSOCKET srt_create_socket_af(int af)` would be more convenient compared to `srt_create_socket(..)` and `srt_bind(..)`?

**Comment by jeandube** [comment]
srt_socket() was a mimic of BSD socket() function and was a no brainer for socket programmers. I had Zero problem with unused arguments. The BSD socket API might not be perfect but it is a de-facto standard. I don't see the advantage of having a no-family socket until it connects or binds. The same applies to the srt_get/setsockopt that might one day dissapear in favor of srt_get/setsockflag because some arguments are not used. It is a chance the SRT documentation has matured to compensate this going away from a well-known API, but apparently it was not enough for @OliverSchoen, which I have no doubt is a seasoned socket programmer.

**Comment by maxsharabayko** [comment]
### TODO

- [ ] Remove the note "... the use of SRT with AF_INET6 has not been fully tested; use at your own risk..." from the API documentation.

- [ ] Consider restoring `srt_socket(int af, ...)` API function.

SRT v1.4.2 deprecates the `srt_socket(int af, int type, int protocol)` API function because `type` and `protocol` were always the same. However, the `af` parameter might be useful to create IPv6-family sockets.

```c++
// Linux socket creation interface
int socket(int socket_family, int socket_type, int protocol);

// SRT
SRTSOCKET srt_socket(int, int, int) SRT_ATR_DEPRECATED; // marked deprecated in v1.4.2
SRTSOCKET srt_create_socket(void);
```

**Comment by ethouris** [comment]
Excuse me, but I don't understand the problem. What is exactly the reason that you want to specify the family when creating a socket? What exactly problem would it solve?

**Comment by maxsharabayko** [comment]
Possible advantages of specifying socket family in `srt_socket(..)`:

```c++
const int sock = srt_socket(AF_INTE4, .., ..);
srt_bind(sock, <some IPv6 address>); // Return ERROR
srt_connect(sock, <some IPv6 address>); // Return ERROR
```

```c++
const int sock = srt_socket(AF_INTE6, .., ..);
srt_bind(sock, <some IPv4 address>); // Return ERROR
srt_connect(sock, <some IPv4 address>); // OK - IPv4 over IPv6
```

Not sure though if it covers any use cases of SRT integrators.

**Comment by maxsharabayko** [comment]
It is not clear at the moment whether the use case described above is useful or not. And if some other behavior is useful related to socket family defined at socket creation time (`srt_socket(int af_family, ...`).
Also, there is no discussion on this topic, probably indicating not that much interest.

Closing this issue, and moving the discussion to #1789.
