### ISSUE TITLE
HI, Seeking Feedback for UAV Streaming w/ Raw Frame Injection on Open.HD

### ISSUE THREAD

**Issue by htcohio** [Haivision/srt#692]
Hello all,

I have been following this project for the better part of a year.  There are many aspects that I don't fully understand.  I have shared this project with other developers in our Open.HD project 

https://github.com/HD-Fpv/Open.HD

We have created an all-in-one UAV HD video downlink with bi-directional data and RC control protocols.   This project was branched last year from EZ-WIFIBROADCAST but the core architecture is the same.

this is a video of a long-range flight (30KM) however there have been many others even longer range than this...  

https://youtu.be/BH8Tro88P7c

None of this is transmitted over the internet..  we utilize Raspberry Pi SBC computers and a handful of compatible Wi-Fi USB chipsets such as the RTL8812/14AU, Atheros AR9271 and Ralink RT3572...

They are all capable of monitor mode and packet injection.  basically, we serialize the h264 hardware encoded video source from Raspberry Pi camera and achieve latency of 120ms with forward error correction.

I believe there is a combination of injection as well as raw UDP frames used.  the primary benefit with monitor mode is that it creates the single broadcaster multiple listener setup with reliability advantages similar to that of wireless analog video transmission.

The reason I'm here is to get some feedback about the possibility integrating SRT into our platform in some way.  With our system using monitor mode packet injection frames maybe there is nothing to be gained but, with UDP being unidirectional it seems from my basic understanding that SRT is developed to solve that problem.  

I would have to think that there could be some benefit in there.  So, anyways sorry so long, I just wanted to share our project to see if you guys had any feedback or possible advantages we could gain by integrating SRT into open HD. 

Cheers,

Justin

**Comment by maxlovic** [comment]
Hi @htcohio,
SRT was designed with live streaming over public networks in mind, reducing network overhead, and achieving best reliability of delivery. The main tool to recover lost packets is Automatic repeat request (ARQ). Assuming a fixed RTT of the network it takes `1/2 RTT` to deliver a packet to the receiver. If the packet is lost, the next packet arrives after `~8*MTU/bitrate`. The receiver detects the loss, and sends back a loss report to the sender. So the sender knows about the loss roughly after `(RTT +8*MTU/bitrate)`, and resends the lost packet. This gives a total latency of roughly `3/2*RTT+8*MTU/bitrate`.
Knowing that, you can set your desired latency e.g. to `2*RTT`, and SRT will drop the packets that are too late to be delivered withing the specified latency restriction.

SRT also has FEC in [experimental branch](https://github.com/Haivision/srt/tree/experimental/packet-filter-api). The drawback of FEC is that it produces high overhead, while being able to restore only low percentage of losses. But still it allows to improve the quality without increasing the latency. And in your case I think you don't really care about the overhead, because you use your own connection, right?

Would be interesting to know RTT and loss rates of yout link and how do they increase with the increase in physical distance. At the speed of light 30 km is nothing, but the level of interference, scattering and energy losses should increase the chances of loosing network packets.

**Comment by htcohio** [comment]
@maxlovic,

Below is a video showing the 2nd half of a 22kM flight...  You'll see that the video drops out gracefully around 20Km.

The typical configuration is as follows

12Mbps Fixed Wifi Data Rate
65% of channel  for video & FEC usage
Block Size: 1024  Bytes
8 Video Blocks
4 FEC Blocks
*Resulting video bitrate approx 4.5Mbps

I believe wifibroadcast originally years ago utilize some kind of continuous simultaneous transmission of the packets but of course it used a lot of bandwidth.

That led to the implementation of forward error correction which is when I found out about the project. 

With this being a UAV application, the most important factor is latency.  FEC adds some latency but it is still minimal (less than 250ms). 

Now my understanding of the SRT RTT is that it potentially opens up more bandwidth to use when the data link is solid and RTT is called upon during lossy situations.

Perhaps there could be some kind of hybrid solution where 1 FEC Packet is used and RTT Is used as a supplement allowing more video bitrate to be allocated during normal use? 

Of course I need to read through the documents much more... ;)

In the video on the top left corner you'll notice the green and red FEC indicator bar (OSD) near the Downlink rx rssi indicator.

https://youtu.be/eD7jcJl66_g
