### ISSUE TITLE
Documentation on Authentication schemes

### ISSUE THREAD

**Issue by zerog2k** [Haivision/srt#696]
I have scanned through whitepaper, deployment guide, and several docs here in repo, and trying to find some basic understanding of whether SRT supports any kind of authentication schemed. I do see there is encryption scheme, but from reading handshake docs, it sounds as if attacker/abuser can get "too far" past any gateway or decoder "front-door" provided by SRT, even if encryption could be considered implicit authentication functionality.

The assumption or hope here would be that a pattern for using SRT as an internet video ingress gateway (at scale, opened to public internet, e.g. hosted on the cloud) with robust authentication and encryption. Smaller scale solutions can manage rudimentary ip restriction as one possible solution, however at scale and the dynamic nature of calling systems (encoders, e.g. deployed on-site at some event with ephemeral network connectivity), make ip restriction management challenging.

Are there any docs or discussion on this subject?

**Comment by jeandube** [comment]
@zerog2k: Have a look at the SRTO_STRICTENC option. When set on a listener, it prevent connection of a caller without the right passphrase.

**Comment by maxlovic** [comment]
@zerog2k This [test set](https://github.com/Haivision/srt/blob/master/test/test_strict_encription.cpp) might also be helpfull.

**Comment by ethouris** [comment]
I'm not sure I understand what you said at the end of the first paragraph.

By the current default settings in SRT in order to have any transmission, your handshake should be first completed (packets that come out of connection are simply rejected without any processing). When you have encryption set up, the passphrase must be set the same on both sides or otherwise the connection is rejected. In case when you have a listener-sender (kinda "stream server" mode), the password check is done when the caller sends its handshake packet with WSEK to the listener and when the listener can't decrypt the WSEK using its passphrase, the connection is rejected at this moment.

This is the default with SRTO_STRICTENC option set to true. If you set this to false (required on BOTH sides), it is allowed that a side that has set a password receive an unencrypted stream, or it can receive an encrypted stream that it can't decrypt.

Please tell me some scenario you think might lead to any security breach from an attacker/abuser and we'll see how this can be mitigated.

**Comment by maxlovic** [comment]
Check [SRT Access Control Guidelines](https://github.com/Haivision/srt/blob/master/docs/AccessControl.md).

**Comment by zerog2k** [comment]
Thanks all
