### ISSUE TITLE
Bandwidth Loop Test

### ISSUE THREAD

**Issue by rmsoto** [Haivision/srt#697]
Hello @maxlovic ,

I´m ready to perform some tests about the BW issue I´m dealing, maybe you can show me how to read the filename.csv and how to tweak the commands to give me some clues.

I executed the commands you have in the readme:

Caller:

```
./srt-test-messaging "srt://80.84.129.197:4200?nakreport=true&sndbuf=12058624&smoother=live&maxbw=40000000" "" -bitrate 100000000 -msgsize 1456 -reply 0 -repeat 250000 -printmsg 0 -statsfile filename.csv -statsfreq 1
Connect to srt://80.84.129.197:4200?nakreport=true&sndbuf=12058624&smoother=live&maxbw=40000000

ERROR: Still have undelivered bytes 11648
```
 
Listener:

```
./srt-test-messaging "srt://:4200?nakreport=true&rcvbuf=12058624&smoother=live" -reply 0 -msgsize 1456 -printmsg 0

Listen to srt://:4200?nakreport=true&rcvbuf=12058624&smoother=live
```

I´m also attaching the filename.csv I got from the first test

[filename.zip](https://github.com/Haivision/srt/files/3201820/filename.zip)

Thanks!
Raúl.

**Comment by maxlovic** [comment]
@rmsoto The CSV file contains SRT stats. The namings are preserved. Refer to [`CBytePerfMon`](https://github.com/Haivision/srt/blob/master/srtcore/srt.h#L243) structure.

From the stats I see the sender is sending at ~350 Mbps, which is 25k packets. 20k packets are reported lost, and are being retransmitted.
RTT is 13 ms.
![sender_packets_plot](https://user-images.githubusercontent.com/12700120/58088830-c5454080-7bc3-11e9-991b-ebf9017e55a3.png)

The next step is to understand, if this happens due to the network throughput, of it is an issue with SRT. There is a number of utilities: [iperf](https://github.com/esnet/iperf), [ethr](https://github.com/microsoft/ethr).
If you are familiar with golang, `ethr` is quite functional.
To run UDP bandwidth test run server:
```
ethr -s -ports control=4287,tcp=4299,udp=4201,http=4289,https=4288
```
and client:
```
ethr -c 13.93.115.208 -n 1 -p udp -t b -ports control=4287,tcp=4299,udp=4201,http=4289,https=4288 -l 64KB
```
Although sometimes ethr does not show receiving speed in UDP tests.

There is also a simple UDP [`bwcheck`](https://github.com/maxlovic/bwcheck) utility, it will require you to build boost though.

**Comment by rmsoto** [comment]
Thanks!

**Comment by maxlovic** [comment]
Hi @rmsoto Do you have updates on this issue?

**Comment by rmsoto** [comment]
not yet, sorry. Hope to have something anytime soon.

**Comment by maxlovic** [comment]
@rmsoto Looking forward for your feedback on this issue. Will close for now.

**Comment by rmsoto** [comment]
Sorry for my late answer, finally we´ve found a switch in one of the sites that have one of his ports negotiating at 100Mbps :-S anyway I must continue testing! Thanks for the help!


[Overon]

RAÚL MANSILLA
Innovation | R&D


  [skype] <skype:raul_mansilla?call>   [linkedIn] <http://www.linkedin.com/profile/view?id=37659057&trk=tab_pro>    | OVERON <http://www.overon.es/>  | C/ Virgilio, 2 | Edificio Overon | 28223 | Madrid | Spain |





De: Maxim Sharabayko <notifications@github.com>
Enviado el: lunes, 24 de junio de 2019 7:20
Para: Haivision/srt <srt@noreply.github.com>
CC: Raul Mansilla Soto <raul.mansilla@overon.es>; Mention <mention@noreply.github.com>
Asunto: Re: [Haivision/srt] Bandwidth Loop Test (#697)


@rmsoto<https://github.com/rmsoto> Looking forward for your feedback on this issue. Will close for now.

**Comment by maxlovic** [comment]
Closing for now. Do not hesitate to reopen would you have an update.
