### ISSUE TITLE
srt-live-transmit vs stransmit

### ISSUE THREAD

**Issue by gmadeo** [Haivision/srt#746]
Hi,

I am using srt-live-transmit to read a UDP stream on one machine and transfer via SRT to another machine, where I receive SRT and output UDP with srt-live-transmit. I used v1.3.2 and it is working as expected.

When I use stransmit from 1.2.3(with libsrt from 1.3.2) on the machine reading UDP, instead of srt-live-transmit, I observe a 50-100% higher CPU usage by srt-live-transmit on the receiving machine.

I have also observed significantly lower(10x) RMS jitter when using stransmit to read UDP over srt-live-transmit.

I wonder what is stransmit doing differently than srt-live-transmit when reading UDP? Also why is the receiver having higher CPU usage? Considering the same version of the library is used in all cases.

Thanks!

**Comment by ethouris** [comment]
No idea why you might observe any differences because `stransmit` is a legacy name and currently used as a symbolic link to `srt-live-transmit` (on systems where symbolic links aren't supported, the file is simply copied).

Might be that you have different SRT versions in both, that's the only way how they could really differ.

**Comment by gmadeo** [comment]
I was actually using stransmit from 1.2.3, not the symlink from 1.3.

I was using the same library in both cases, but there must have been some difference. Now I managed to match the stransmit behaviour with srt-live-transmit.

Thanks!
