### ISSUE TITLE
Help in understanding live streaming requirements

### ISSUE THREAD

**Issue by oviano** [Haivision/srt#751]
Hi

On this page is a detailed description of how an application should pass MPEG-TS packets to the SRT library:

 https://github.com/Haivision/srt/blob/master/docs/live-streaming.md

I wonder if someone would help me understand this paragraph in particular:

"Now, imagine the very first video frame in the stream, which is called an "I-frame". This frame is just a compressed picture, and it needs no additional information to decode it into a displayable pixmap. Several transport units (of 1316 bytes) are needed to transmit the I-frame over the network. The audio frames for the period of time corresponding to this video frame should also fit into this "duration". So, you will need to send several units of 1316 bytes to transmit all these data over a network. But you usually spend much less time to transmit than the actual "duration" (1/60s in our example). This doesn't mean, however, that you should send the video and audio data as fast as possible and then simply "sleep" for the remaining time! It means that you should split the whole 1/60 second evenly across all single 1316-byte units. There is a "unit duration" for every single 1316-byte unit, so you send the unit, and then "sleep" after every unit, if sending (as usually happens) has taken less time than the exact time predicted to be spent by sending this unit."

What I am unsure about is why the transmitter needs to schedule the packets from a single video frame in this manner, because the player isn't going to be able to decode the frame until it has received them all anyway? So what is the benefit in scheduling the packets over 1/60s instead of just sending them all immediately?

Thanks in advance!

Oliver

**Comment by ethouris** [comment]
Let's make a comparison. When you drive through the city half an hour with 100km/h speed, and then wait still next half an hour, your average speed will be 50km/h - but when you drive one hour with a speed of 50km/h, you'll avoid a risk of causing an accident and getting photoed by a speed controller.

Same here. Except that the "speed limit" in the network is invisible, if you want to know it, you must measure it by getting conclusion from the fact of grown RTT and packet loss, and moreover, it can even change over time. That's why in File mode there's the whole facility that measures the network capacity constantly and adjusts the sending speed to utilize the link at maximum. In Live mode there's no such thing - here the transmission facility trusts the input source that it sends already with a speed below the network speed limit, and this speed isn't exceeded even momentarily.

Even though speed control could be done in Live mode, it makes no sense at all - because if your input speed is below the limit, there's nothing to control, and if it's above the limit, your live stream doesn't make sense because it must be live, that is, delivered when expected, not belated by some time temporarily, or the transmission doesn't makes sense anyway. That's why if there are any unexpected bad network conditions, it's preferred to let the packets drop and continue playing rather than stopping the playout to wait for missing packets.

There is a speed control for Live mode, but only as a predefined bandwidth limit - which is only meaningful for cases when retransmitting packets would temporarily increase the network speed above the given limit. Sending in this case is slowed down at the expense of delivering also the data packets slightly later. This bandwidth limit is also optional.

**Comment by oviano** [comment]
Nice explanation, but what would be the network infrastructure analogy then for "you'll avoid a risk of causing an accident and getting photoed by a speed controller."

Presumably network collisions, throttling etc less likely?

**Comment by maxlovic** [comment]
@oviano It is recommended to keep the average sending rate close to the stream bitrate (in live mode) to avoid network congestion. Although noone stops you from sending the whole I-frame as fast as possible, you will have spikes in network utilization. If you know your network can handle it, you can do it. In that case you will anyway have to wait the remaining time untill the following video frame is ready to be delivered. So the network utilization would be like:
```
 /\     /\          X Mbps
/  \___/  \____     0 Mbps
```
instead of
```
---------------  Y Mbps
                 0 Mbps
```

**Comment by oviano** [comment]
Makes sense, thank you both for your time.
