### ISSUE TITLE
Is there any Pull mode about SRT ?

### ISSUE THREAD

**Issue by AlexandreLicinio** [Haivision/srt#784]
Hi, 

Could be fantastic to have a pull mode about SRT in case we have NAT and/or Firewall and/or we can't have the public ip and do port forwarding. Is it in the roadmap ?

Thanks

**Comment by J-Rogmann** [comment]
HI Alexandre,

SRT has a pull mode already. Maybe it's not clear, since it's named differently: caller & listener.
To give you an example: you want to sent a stream from site A to remote site B, but site B has a firewall, which you cannot open and your receiving device is behind a NAT.
Site A has a firewall & NAT as well, but this site can be controlled by you. So you can open a port (e.g. UDP 5000) and create a portforward from your public IP to your local network IP. (e.g. 34.56.78.90 -> 192.168.1.2 )
Your sending device on Site A cannot "push" the stream to receiving site B in this scenario, so you turn the sender into a SRT-listener. The receiver then would act as SRT-caller, to actually "pull" the stream from the sender at site A. It would do a call to srt://34.56.78.90:5000 to stay in the picture above.

The beauty of caller listener mode is: it can be turned around! If your non-configureable site is site A, where the sender is located and site B is configurable: make the receiver at site B the SRT-listener and the sender at site A the caller.

If both sides are behind a firewall and can't be opened, there is still a chance with rendezvous mode. If the firewall is configured in a way allowing requests from inside towards the internet and also allowing the return answer to these particular requests back in, there is a good chance rendezvous will work. 

For rendezvous mode both sides need to know the others IP adress and will use the same port.

Did this answer you question so far?
Let me know, if you have problems in trying this.

best regards,
Justus

**Comment by AlexandreLicinio** [comment]
Thanks @J-Rogmann so i just have to put the sender (streaming encoder) in listener mode and the receiver (streaming decoder) in caller mode ? Let's try it, thanks

**Comment by AlexandreLicinio** [comment]
hmm this isn't working, be cause i get error when put the wan ip adress in the decoder as caller.

`ERROR: error: srt_bind: Connection setup failure: unable to create/configure SRT socket: Cannot assign requested address.`

So to resume, SITE-A is a VPS (the encoder), SITE-B is the decoder behind a NAT so let's say i can't access to wan ip or port forwarding at B side.

SITE-A:
./srt-live-transmit udp://239.127.0.1:11399 srt://<waniposSITE-A>:19919?mode=listener -t:-1 -v

SITE-B:
./srt-live-transmit  srt://<waniposSITE-A>:19919?mode=callerudp://239.127.0.1:11399 -t:-1 -v

In fact i want side B pull the stream from A like a rtmp or rtsp, and cross NAT without any port forwarding.

Thanks

**Comment by J-Rogmann** [comment]
Hi Alexandre,

I assume you try to run both srt-live-transmit processes on the same machine, which would result in error your get. Typically you cannot access the same socket twice on your machine.

If you would split up your test to two different machines it would look like following:
PC1 e.g. 192.168.1.1
PC2 e.g. 192.168.1.2

on PC1:
`./srt-live-transmit udp://239.127.0.1:11399 srt://:19919?mode=listener -t:-1 -v`

on PC2:
`./srt-live-transmit srt://192.168.1.1:19919?mode=caller udp://239.127.0.1:11340 -t:-1 -v`

Note: I increased the multicast port by one on PC2 for the outgoing stream, since I assume both PC's running on the same network. If PC1 and PC2 are at different locations with no multicast routing in between, you can use the same multicast IP&port of course, e.g. udp://239.127.0.1:11399

**Comment by AlexandreLicinio** [comment]
Sorry i did have issue about copy-paste with < > signs so the srt command was incomplete.
No both caller and listener aren't in same subnet/machine, wan is the bondary between them.

So how do i pull the encoder stream from the decoder, the decoder is behind NAT and i can't know the wan ip address. But i have access to it because ovpn remote management about the linux system.

thanks @J-Rogmann

**Comment by J-Rogmann** [comment]
Hi Alexandre,

to pull the stream from encoder, you need to use the example from above. The Encoder must be reachable on the UDP port you use for the Decoder. In caller/listener mode at least one side needs to be known by it's IP address and must be reachable on one UDP port. (NAT and port-forwarding works in that case.)

PC1:
` ./srt-live-transmit udp://239.127.0.1:11399 srt://:19919?mode=listener -t:-1 -v`

PC2:
`./srt-live-transmit srt://public.IP.of.Encoder:19919?mode=caller udp://239.127.0.1:11399 -t:-1 -v`

Just exchange `public.IP.of.Encoder` by the IP address or DNS-name. It doesn't matter, if the Decoder is behind a NAT and it's public is not known. As long as you know the Encoders IP or DNS-name and can ensure, it is reachable on the given UDP port (19919 in your case) everything is good.

**Comment by AlexandreLicinio** [comment]
wow this is impressive ! it works, the key was `srt://:19919?mode=listener` thanks a lot @J-Rogmann :)
