### ISSUE TITLE
non-debug causing visible tearing in the stream

### ISSUE THREAD

**Issue by fatpelt** [Haivision/srt#826]
i've got something of an odd issue that i'm not sure how to debug properly.  I've built commit 887bb6b (master HEAD) with heavy logging on.  when I run with the following command line i get what appears to be packet loss in the downstream multicast feed:

`./srt-live-transmit -logfa:all -loglevel:note -v 'srt://:8006?latency=7000&tlpktdrop=1&rcvbuf=48234496' udp://232.70.15.11:1234 -s:3000
`
however if i run it in debug logging mode the stream looks fine:

`./srt-live-transmit -logfa:all -loglevel:debug -v 'srt://:8006?latency=7000&tlpktdrop=1&rcvbuf=48234496' udp://232.70.15.11:1234 -s:3000`

i've tried a bunch of different options on the command line and can't seem to find the right incantation to make it not tear when not in debug mode.

**Comment by fatpelt** [comment]
platform information.  i'm only the receiver; no idea on what the sender is.

ubuntu 16.04
40 proc (hyperthreading) Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz
32G ram

this is currently the only process on the box.

**Comment by maxlovic** [comment]
Heavy logging introduces additional packet processing delay. UDP output, for example, might loose some packets in case of network congestion. Better to collect SRT stats with -pf:csv -statsfile:out.csv
What bitrate are you sending?

**Comment by fatpelt** [comment]
not sure exactly.  it's *way* less than another 90Mbps mpts i've got coming from another source though.  this one is in the 10Mbps range.  i do know it's being generated off an ffmpeg conversion from hls to mpegts then pipe'd into the transmit on the far end though.  that might be causing some issues.

as for the added delay, i was suspecting that the delay was the cause, and had hoped that the "latency=7000" would take care of being able to buffer anything missing?

maybe i'm not fully understanding how that works though

**Comment by maxlovic** [comment]
Latency option value set to 7000 ms would tell SRT to drop (cancel further re-transmissions) a packet that is too late to be delivered. Roughly, this is true for the packets that were added to the sending queue more than 7 seconds ago.
So this option does not really compensate the performance burdain of the heavy logging. But I would have expected the opposite: that with heavy logging you would have had higher rate of packet loss.
So I thought it might be due to UDP output. With debug logging the pace might be slower. But only a guess.
