### ISSUE TITLE
srt_listen: Listener's backlog exceeded, after all caller is closed.

### ISSUE THREAD

**Issue by justinjoy** [Haivision/srt#927]
I am learning to `srt_listen()` and its callback, `srt_listen_callback()`.
Although they are very convenient APIs to accept callers, I faced _backlog exceeding_  problem when the number of caller reaches backlog of `srt_listen()`. I was thinking, if a caller is accidentally closed, the number of receivers should be decreased so I can expect that another caller can connect to the listener.
The number seems to be adjusted by srt's garbage collector, but while my testing, no garbage collection was working.

My only solution is that the listener socket should be re-created when the number of callers reaches backlog. Is it correct approach to solve this problem?

## Steps to reproduce
In listener,

1. open listener socket by `srt_listen(sock, 1)`
1. add a callback function by `srt_listen_callback()`
1. when a caller is connected, start monitoring `sock` from callback function.

In caller,
1. try to connect to the listener
1. close socket forcedly
1. try to connect to the listener again

## Actual result

Masked IP adress. And I am not sure why _PASSING request from log_ is printed out twice by one caller connection request.

```
15:29:33.091332/SRT:RcvQ:worker.N:SRT.c: PASSING request from: ***.***.***.***:44632 to agent:27297270
15:29:33.091415/SRT:RcvQ:worker.N:SRT.c: Listener managed the connection request from: ***.***.***.***:44632 result:waveahand
15:29:33.091466/SRT:RcvQ:worker.N:SRT.c: PASSING request from: ***.***.***.***:44632 to agent:27297270
15:29:33.091709/SRT:RcvQ:worker.N:SRT.c: HSREQ/rcv: cmd=1(HSREQ) len=12 vers=0x10400 opts=0xbf delay=125
15:29:33.091747/SRT:RcvQ:worker.N:SRT.c: listen ret: -1 - conclusion
15:29:33.091751/SRT:RcvQ:worker.N:SRT.c: Listener managed the connection request from: ***.***.***.***:44632 result:waveahand

(hwangsae-agent:206799): HWANGSAE-WARNING **: 15:29:58.060: sock: 1a085f4, error: Success

(hwangsae-agent:206799): HWANGSAE-WARNING **: 15:29:58.061: Invalid SRT sink socket 1a085f4
15:30:10.490241/SRT:RcvQ:worker.N:SRT.c: PASSING request from: ***.***.***.***:48738 to agent:27297270
15:30:10.490271/SRT:RcvQ:worker.N:SRT.c: Listener managed the connection request from: ***.***.***.***:48738 result:waveahand
15:30:10.490301/SRT:RcvQ:worker.N:SRT.c: PASSING request from: ***.***.***.***:48738 to agent:27297270
15:30:10.490306/SRT:RcvQ:worker*E:SRT.c: newConnection: listen backlog=1 EXCEEDED
15:30:10.490310/SRT:RcvQ:worker*E:SRT.c: UU:newConnection: rsp(REJECT): 1005 - Listener's backlog exceeded
15:30:10.490320/SRT:RcvQ:worker.N:SRT.c: listen ret: 1005 - ERROR:BACKLOG
15:30:10.490324/SRT:RcvQ:worker.N:SRT.c: Listener managed the connection request from: ***.***.***.***:48738 result:INVALID
15:30:10.490387/SRT:RcvQ:worker.N:SRT.c: PASSING request from: ***.***.***.***:48738 to agent:27297270
15:30:10.490396/SRT:RcvQ:worker.N:SRT.c: Listener managed the connection request from: ***.***.***.***:48738 result:INVALID
```

**Comment by maxlovic** [comment]
> 2. add a callback function by srt_listen_callback()
> 3. when a caller is connected, start monitoring sock from callback function.

Could you please describe what do you mean by "Start monitoring socket from callback function when a caller is connected"?
The callback function takes place before the caller is finally connected.

If a caller was connected, and then you close the socket forcedly, the listener will need time to detect the connection is broken and close it. Therefore with backlog=1 other callers are not abe to connect.
By forcedly closing a caller, do you mean termination of the process, or a normal call to `srt_close()`?

Please also check the [SRT Access Control Guidelines](https://github.com/Haivision/srt/blob/master/docs/AccessControl.md) and the unit test for listener callback: [link](https://github.com/Haivision/srt/blob/master/test/test_listen_callback.cpp).

**Comment by ethouris** [comment]
If you can, please at best show the body of the listener callback handler, or at least please describe what exactly you are trying to do with the socket.

**Comment by justinjoy** [comment]
> Could you please describe what do you mean by "Start monitoring socket from callback function when a caller is connected"?

That was my mistake to use unclear terms. I meant I tried to read state(`srt_getsockstate()`) and wait for events via `srt_epoll_uwait()` from the accepted socket on a listener side.

What I am trying to do is to accept only a specific number of callers at a time by adjusting `backlog` parameter of `srt_listen()`.

> If a caller was connected, and then you close the socket forcedly, the listener will need time to detect the connection is broken and close it. Therefore with backlog=1 other callers are not abe to connect.

I understood, but the problem of mine is that I can't be sure when another caller can connect to the listener after the existing caller is disconnected regardless of accidentally or intentionally

> By forcedly closing a caller, do you mean termination of the process, or a normal call to `srt_close()`?

I am testing both ways by terminating (kill -9) or physically disconnecting(power off embedded board which runs caller).
I didn't check a case to call `srt_close()` on caller side because I assume that SRT community has tested normal case already.

> Please also check the [SRT Access Control Guidelines](https://github.com/Haivision/srt/blob/master/docs/AccessControl.md) and the unit test for listener callback: [link](https://github.com/Haivision/srt/blob/master/test/test_listen_callback.cpp).

Another question here. Do I need to enable access control to use `srt_listen_callback()` ?

Actually, I don't set`SRTO_STREAMID` and `SRTO_PASSPHRASE`  on both listener and caller for my testing. I assumed that I don't need to set the options for handling backlog of `srt_listen()` because `stream_id` is an empty string in callback function and I can receive data from caller.
is it a bad assumption?

**Comment by ethouris** [comment]
The use of `srt_listen_callback()` is simply that you install a handler that will be called at the moment when a socket is being connected and is about to be accepted. This gives you a chance to accept or reject a connection basing on your own premises, or configure some settings on the socket to make it acceptable. That's about all. Whether you use the access control rules, it's up to you.

**Comment by justinjoy** [comment]
> I didn't check a case to call `srt_close()` on caller side because I assume that SRT community has tested normal case already.

After writing the comment, I tried to call `srt_close()` in caller side by gstreamer command.

```console
$ gst-launch-1.0 videotestsrc num-buffers=10 ! x264enc tune=zerolatency ! mpegtsmux ! srtsink uri=srt://***.***.***.***:8888/?mode=caller
```
This command will send 10 buffers, then call `srt_close()`. but in listener, it seems to hold backlog count.

**Comment by ethouris** [comment]
Another question: do you give the caller enough time to make sure that the moment when you are trying to connect another caller is already past the moment when the first connection is accepted on the listener side?

**Comment by justinjoy** [comment]
> do you give the caller enough time to make sure that the moment when you are trying to connect another caller is already past the moment when the first connection is accepted on the listener side?

After the first caller is disconnected, I took dinner. Then, I did another try.

I also have another question: When GC is running? What is a condition to trigger GC?

**Comment by ethouris** [comment]
See `CUDTUnited::garbageCollect`; according to what I can see, it's rolling in a loop then sleeping for 1 second. It's running so in a separate thread, until the application exits. The most important part of a single run is `CUDTUnited::checkBrokenSockets`, which should remove all sockets that have seen a connection broken, unless there are still any operation underway.

That's actually not important, GC has completely nothing to do with it. This is most important:
```
   // exceeding backlog, refuse the connection request
   if (ls->m_pQueuedSockets->size() >= ls->m_uiBackLog)
```
Every incoming connection is being added to Queued Sockets. At the moment when the connection is accepted, this socket is moved from Queued Sockets to Accepted Sockets. Beside cases of broken listener socket, where a socket is removed from both these containers, there's only one case when it's removed from Queued Sockets only - it's `CUDTUnited::accept`, which is called indirectly from `srt_accept`. Even blocking-nonblocking mode doesn't matter here because in case of nonblocking you should call it only when you know that a new connection is waiting - and yes, it will occupy a place in Queued Sockets (and therefore potentially reach the backlog limit) until you call `srt_accept`.

What is then important for me is whether you are really sure that the second connection from the caller side has really started not earlier than when the socket has been returned by `srt_accept` on the listener side. Your log is unclear as to whether it happens at all.

**Comment by ethouris** [comment]
I'd say more: you shouldn't even have problem when one socket is connected and another is attempting to connect - without even breaking the first connection. The backlog defines the maximum number of PENDING not existing connections - that's why GC has nothing to do with it, on either side.

When you set backlog to 1 and you get "backlog exceeded" error, it simply means that at this moment you have one connection that is being processed at this time, that is, the caller has already sent the conclusion handshake and you simply hit this very moment when it's underway.

**Comment by justinjoy** [comment]
But my question is;  when can another caller connect to listener (backlog =1) after the existing caller is broken?

**Comment by ethouris** [comment]
Again: being broken or connected has nothing to do with it at all.

When you set the backlog to N, it is only allowed to have N queued sockets.

The socket is queued at the firstmost moment when it is spawned by receiving the CONCLUSION type handshake from the caller and lasts until the socket is returned by `srt_accept` function. During this whole time this one socket occupies one backlog slot.

In short: if your socket (at the listener side) was once used in transmission, there's no possibility that the next caller request be rejected - at least not because of the backlog excess.

Although I can think of a possibility of a socket being stuck in the connection pending mode - only theoretical one because it would have to be something like that the request has been sent to the listener, but the caller didn't respond due to that the connection was hard interrupted. The problem is that the listener doesn't expect any response from the caller - at the moment when the caller sends CONCLUSION handshake, the listener socket spawns the accepted socket, sends the CONCLUSION response and then waits for the application to call `srt_accept`. After this call returns, the socket is considered connected and the slot it was occupying in the backlog is freed.

In result: if you plug off the cable BEFORE the caller sends conclusion handshake, the listener won't even notice anyone pending for a connection. If you do it AFTER the caller sends the conclusion handshake, and your application has really "accepted" the connection, it will happen and the backlog slot will be freed from it, making a new pending connection still possible.

As we don't know at which moment the call to `srt_accept` returns in your application, I can't tell you what really happened in your scenario.

**Comment by justinjoy** [comment]
> Another question here. Do I need to enable access control to use srt_listen_callback() ?
>
> Actually, I don't set SRTO_STREAMID and SRTO_PASSPHRASE on both listener and caller for my testing.  I assumed that I don't need to set the options for handling backlog of srt_listen() because stream_id is an empty string in callback function and I can receive data from caller.
> is it a bad assumption?

It's not related to `SRTO_STREAMID` and `SRTO_PASSPHRASE`. Rather, they are related to `srt_listen_callback()` and `SRTO_PASSPHRASE`. 
As @maxlovic explained in #932,  `SRTO_PASSPHRASE` should bet set to use `srt_listen_callback()`.
