### ISSUE TITLE
Use SRT to send RTP Video Stream to Multicast Group

### ISSUE THREAD

**Issue by gurtajs4** [Haivision/srt#93]
Hi All,

I've been using SRT to transmit RTP Video Streams Packet to over one-to-one SRT Socket API's.

With this approach, I can only send video to few number of clients connected to Same router.
What I want to achieve here is to send the data using SRT to Multicast Group and Receiver subscribe to the group and start receiving data, given that I can still take the advantage of SRT Protocol ( packet recovery and re-transmit, latency)

Is that possible using SRT now?

Regards,
Gurtaj

**Comment by ethouris** [comment]
With multicast there is such a problem that it's unidirectional only. With SRT you have theoretically one data stream sent in one direction, but the control communication is bidirectional. The IGMP multicast group is something supported by the router of the local network, and there's no bidirectional communication possible here - even if you "send a packet back to the address from which a UDP packet has come", you'll at best send it to the multicast address from which the packet has come, and this will be redirected by the router to the subscribers (not sure what exactly happens when multiple machines are trying to send UDP packets to the same IP/port, but I guess that it's the same thing as with unicast). Even if this is possible this way to make the router send something "back to the stream sender", it won't know who the original sender was anyway. This simply doesn't work with the connection-oriented logic at all because it needs a "personal" (1-to-1) control communication at least.

You can use the following solutions:

1. SRT listener at the sender and callers at the receivers. But still, the client receiver would have to know the exact IP address of the stream sender. Some third-party software solution would have to be engaged additionally so that the multicast group address is somehow finally resolved into the "physical" (unicast) IP address of the stream server. This isn't impossible, just not out-of-the box.

2. The stream server may do caller connection to every client that would like to get the stream. However the stream server must be somehow contacted first - possibly through some dedicated type message sent over IGMP IP address - and the client would need to pass its IP and port where the stream server should connect.

Of course, this won't have the full advantage of multicast - that is, you are sending just one copy of data packet to the router, and the router then multiples them for resending, where your link to the router is loaded with only one stream. With SRT you'll load your link with as many streams as the receiving clients.

Sending one SRT packet to be distributed by the router to the clients is currently impossible because SRT header must contain the socket ID, where this socket ID is a random-generated number by the client, so for each client it's different. Whether appropriate change can be done to make it possible - long further study is required, definitely this wouldn't be so easy to do. Might be even easier to make an application running on the router that will do UDP(multicast) to SRT flipping, and add new outputs by IGMP request.
