### ISSUE TITLE
FR: Source time

### ISSUE THREAD

**Issue by maxsharabayko** [Haivision/srt#930]
The source time `srctime` can be set in `SRT_MSGCTRL` argument of the of `srt_sendmsg2(…)` function,
This time is currently ignored. PR #929 puts this time further aside.

A proper way to handle source time would be to state that an application should provide 64-bit time intervals with a microsecond accuracy.

The tricky part is to conform to the TSBPD mode of the receiver.
The value of `TsbPdTimeBase`  is initialized at the time of the handshake request (HSREQ ) is received. The timestamp of the sender's clock is taken from the handshake request.
Further on this `TsbPdTimeBase` is used to determine the time to deliver a packet to the app (via `srt_recvmsg`). This means that an app should provide the timestamp at the time a socket is created or a connection has started.

There are two potential use cases:
1. Passthrough timestamps of data packets for data forwarding. Sender -> Forwarder -> Receiver. Either SRT forwarding in a server/Gateway or RTP <--> SRT
2. The second use case is to explicitly set the source time of some data. For example, an encoded video frame is split into a number of SRT packets. All these packets should have the same timestamp, because they are to be read by the receiver at the same time. In case there are two video streams (digital signage), that have to be played simultaneously, the app should provide the source timestamp. Justus should know about this use case.

The first use case has a higher priority, and should not have direct conflicts with TSBPD base time.

**Comment by ethouris** [comment]
There are two ways how we can go on with this:

 - Make this time standard specified as monotonic clock and point out which functions could be used to obtain it. I think this would be the best solution.
 - Use externally the local time so that users can use any function to obtain it. This would be translated also from the tsbpd time that would be now monotonic clock.

Possible also combination of these two by selection from a socket option.

**Comment by colmaengus** [comment]
Not sure if this is related but we were looking at way to measure/confirm the e2e one way latency of SRT under simulated network impairment. Since we have a simulated environment we can make sure that the clocks are both ends of srt-live-transmit clocks are exactly in sync. Ideally our test source/sink would support https://webrtc.org/experiments/rtp-hdrext/abs-send-time/ but unfortunately it doesn't.
So we modified srt-live-transmit to prefix the payload with a timestamp and strip it on receive side. This allows us to report latency along with other SRT stats. Its a bit hacky but does the job for our use case.
Are there thoughts on allowing the sending to provide something similar to abs-send-time that would be available to receiver at the API level?

**Comment by maxsharabayko** [comment]
Just a drawing for me to remember
![Scan_20200123 (2)](https://user-images.githubusercontent.com/12700120/72972240-5b70dc80-3dcb-11ea-9cae-41665875f318.png)

**Comment by ethouris** [comment]
For the time specification, there could be used the following options:
* monotonic clock (default), with provided a function to obtain the "now" time from this clock
* a time relative to start time (that is, direct extraction of the timestamp, but including the segment value, maybe with the value of the time segment available separately)

This second possibility might allow various applications prepare the input time for stream generators. Another use of it would be for the use by interactive programs (including network games), which could use timestamps to define the time of event and could detect tampering with the transport UDP packets.

**Comment by maxsharabayko** [comment]
### TODO

- [ ] Add source time handling in SRT sender. PR #13354
- [ ] Add SRT API function to get SRT clock time in microseconds since epoch. `uint64_t srt_time_now()`
